### ISSUE TITLE
Error collecting output for singularity jobs

### ISSUE THREAD

**Issue by mwalzer** [common-workflow-language/cwltool#1054]
## Expected Behavior
Tell us what should happen
```
[job tar.cwl] completed success
{
    "example_out": {
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709", 
        "basename": "hello.txt", 
        "location": "file:///home/user/cwl/hello.txt", 
        "path": "/home/user/cwl/hello.txt", 
        "class": "File", 
        "size": 0
    }
}
Final process status is success
```
## Actual Behavior
```
[job tar.cwl] Job error:
Error collecting output for parameter 'example_out':
tar.cwl:18:7: Did not find output file with glob pattern: '['hello.txt']'
[job tar.cwl] completed permanentFail
{}
Final process status is permanentFail
```

## Workflow Code
Basically the tar output example [from here](https://www.commonwl.org/user_guide/04-output/) with added 
```
hints:
  DockerRequirement:
    dockerPull: alpine
```
and executed with `cwl-runner  --singularity --debug tar.cwl tar-job.yml`. Full cwl and yml see 
[tar.cwl.txt](https://github.com/common-workflow-language/cwltool/files/2833147/tar.cwl.txt)
[tar-job.yml.txt](https://github.com/common-workflow-language/cwltool/files/2833148/tar-job.yml.txt)
attachment.

## Full Traceback
```pytb
[job tar.cwl] Job error:
Error collecting output for parameter 'example_out':
tar.cwl:15:3: Traceback (most recent call last):
tar.cwl:15:3: 
tar.cwl:15:3:   File "/home/walzer/.local/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 601, in collect_output_ports
tar.cwl:15:3:     compute_checksum=compute_checksum)
tar.cwl:15:3: 
tar.cwl:15:3:   File "/home/walzer/.local/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 724, in collect_output
tar.cwl:15:3:     raise WorkflowException("Did not find output file with glob pattern: '{}'".format(globpatterns))
tar.cwl:15:3: 
tar.cwl:15:3:   File "/home/walzer/.local/lib/python2.7/site-packages/schema_salad/sourceline.py", line 166, in __exit__
tar.cwl:15:3:     raise self.makeError("\n".join(traceback.format_exception(exc_type, exc_value, tb)))
tar.cwl:15:3: 
WorkflowException: tar.cwl:18:7: Traceback (most recent call last):
tar.cwl:18:7: 
tar.cwl:18:7:   File "/home/walzer/.local/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 724, in collect_output
tar.cwl:18:7:     raise WorkflowException("Did not find output file with glob pattern: '{}'".format(globpatterns))
tar.cwl:18:7: 
tar.cwl:18:7: WorkflowException: Did not find output file with glob pattern: '['hello.txt']'
[job tar.cwl] completed permanentFail
[job tar.cwl] {}
[job tar.cwl] Removing input staging directory /tmp/tmpmec2oX
[job tar.cwl] Removing temporary directory /tmp/tmpqopYfp
Removing intermediate output directory /tmp/tmpWY1AEI
```
## Your Environment
* cwltool version: 
1.0.20180820141117

**Comment by mwalzer** [comment]
Probably related to #126
