### ISSUE TITLE
galaxy-lib > 18.9.2 isn't working with cwltool

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#1090]
expected:
```
$ cwltool --beta-use-biocontainers tests/seqtk_seq.cwl tests/seqtk_seq_job.json
/home/michael/cwltool/env3/bin/cwltool 1.0.20190228200117
Resolved 'tests/seqtk_seq.cwl' to 'file:///home/michael/cwltool/tests/seqtk_seq.cwl'
[job seqtk_seq.cwl] /tmp/45jzx_nc$ docker \
    run \
    -i \
    --volume=/tmp/45jzx_nc:/tmp/45jzx_nc:rw \
    --volume=/tmp/besqx9si:/tmp:rw \
    --volume=/home/michael/cwltool/tests/2.fastq:/tmp/tmp9873mdrk/stg7e8ad792-84b0-4d76-b469-44f5223fb94f/2.fastq:ro \
    --workdir=/tmp/45jzx_nc \
    --read-only=true \
    --log-driver=none \
    --user=1000:1000 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/tmp/45jzx_nc \
    --cidfile=/tmp/eswqfb2r/20190322152234-683794.cid \
    quay.io/biocontainers/seqtk:r93--0 \
    seqtk \
    seq \
    -a \
    /tmp/tmp9873mdrk/stg7e8ad792-84b0-4d76-b469-44f5223fb94f/2.fastq > /tmp/45jzx_nc/out
[job seqtk_seq.cwl] Max memory used: 0MiB
[job seqtk_seq.cwl] completed success
{
    "output1": {
        "location": "file:///home/michael/cwltool/out",
        "basename": "out",
        "class": "File",
        "checksum": "sha1$322e001e5a99f19abdce9f02ad0f02a17b5066c2",
        "size": 150,
        "path": "/home/michael/cwltool/out"
    }
}
Final process status is success
```

actual:

```
$ cwltool --beta-use-biocontainers tests/seqtk_seq.cwl tests/seqtk_seq_job.json
/home/michael/cwltool/env3/bin/cwltool 1.0.20190228200117
Resolved 'tests/seqtk_seq.cwl' to 'file:///home/michael/cwltool/tests/seqtk_seq.cwl'
Got workflow error
Traceback (most recent call last):
  File "/home/michael/cwltool/cwltool/executors.py", line 162, in run_jobs
    for job in jobiter:
  File "/home/michael/cwltool/cwltool/command_line_tool.py", line 396, in job
    j = self.make_job_runner(runtimeContext)(
  File "/home/michael/cwltool/cwltool/command_line_tool.py", line 250, in make_job_runner
    default_container = runtimeContext.find_default_container(self)
  File "/home/michael/cwltool/cwltool/main.py", line 897, in find_default_container
    use_biocontainers, builder)
  File "/home/michael/cwltool/cwltool/software_requirements.py", line 109, in get_container_from_software_requirements
    from galaxy.tools.deps.containers import ContainerRegistry, AppInfo, ToolInfo, DOCKER_CONTAINER_TYPE
ImportError: cannot import name 'AppInfo' from 'galaxy.tools.deps.containers' (/home/michael/cwltool/env3/lib/python3.7/site-packages/galaxy/tools/deps/containers.py)
Workflow error, try again with --debug for more information:
cannot import name 'AppInfo' from 'galaxy.tools.deps.containers' (/home/michael/cwltool/env3/lib/python3.7/site-packages/galaxy/tools/deps/containers.py)
```

**Comment by mr-c** [comment]
This has been working for a while lately
