### ISSUE TITLE
CWLtools throwing error upon usage of secondary files for capturing log files from star aligner on two different versions

### ISSUE THREAD

**Issue by ranijames** [common-workflow-language/cwltool#1110]
Dear All,

I have tried using java expression to capture all secondary files from STAR aligner in CWLtools version from 2018 October and 2019 February.

 **On 2018 October version it is running successfully without any issues**, whereas on **2019 February version it is throwing error.**

Any suggestions help is much appreciated!!
Thank you

## Actual Behavior

and on 2019 February version the same tool is throwing following error,

   ```
 Error collecting output for parameter 'star_bam':
star.cwl:172:2: Traceback (most recent call last):
star.cwl:172:2: 
star.cwl:172:2:   File "/cluster/home/user/software/anaconda/envs/tupro/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 624, in collect_output_ports
star.cwl:172:2:     compute_checksum=compute_checksum)
star.cwl:172:2: 
star.cwl:172:2:   File "/cluster/home/user/software/anaconda/envs/tupro/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 786, in collect_output
star.cwl:172:2:     primary["secondaryFiles"].append(sfitem)
star.cwl:172:2: 
star.cwl:172:2:   File "/cluster/home/user/software/anaconda/envs/tupro/lib/python2.7/site-packages/schema_salad/sourceline.py", line 247, in __exit__
star.cwl:172:2:     raise self.makeError("\n".join(traceback.format_exception(exc_type, exc_value, tb)))
star.cwl:172:2: 
WorkflowException: star.cwl:182:3: Traceback (most recent call last):
star.cwl:182:3: 
star.cwl:182:3:   File "/cluster/home/user/software/anaconda/envs/tupro/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 765, in collect_output
star.cwl:182:3:     if "$(" in sf["pattern"] or "${" in sf["pattern"]:
star.cwl:182:3: 
star.cwl:182:3: TypeError: string indices must be integers
[job star] completed permanentFail
[job star] {}
[step star] Output is missing expected field file:///cluster/work/lab/projects/temp/fastq_temp/pipeline_part1.cwl#star/star_bam
[step star] produced output {}
[step star] completed permanentFail
[workflow ] completed permanentFail
[workflow ] {
    "alignment_out": null
}
[job star] Removing input staging directory /tmp/tmpS6xqCk
[job star] Removing temporary directory /tmp/tmpmAznco
{
    "alignment_out": null
}
Final process status is permanentFail


```
## Workflow Code

```
    secondaryFiles: |
        ${
             var p=inputs.outFileNamePrefix?inputs.outFileNamePrefix:"";
             return [
               {"path": p+"Log.final.out", "class":"File"},
               {"path": p+"SJ.out.tab", "class":"File"},
               {"path": p+"Log.out", "class":"File"}
             ];
         }

```

## Your Environment
* cwltool version: 
Check using ``cwltool --version``
2019 cwltool 1.0.20190228155703

2018 cwltool 1.0.20181012180214

**Comment by mr-c** [comment]
@ranijames, how did you resolve this issue?

**Comment by ranijames** [comment]
@mr-c I have adapted the following:

For 2018, to get the log files (secondary files), my method was:

```
outputs:
 star_bam:
  type: File
  outputBinding:
   glob:
     ${
       var p = inputs.outFileNamePrefix?inputs.outFileNamePrefix:"";
     if (inputs.outSAMtype.indexOf("SortedByCoordinate") > -1) {
        return p+"Aligned.sortedByCoord.out.bam";
     }
     }
  secondaryFiles: |
    ${
         var p=inputs.outFileNamePrefix?inputs.outFileNamePrefix:"";
         return [
           {"path": p+"Log.final.out", "class":"File"},
           {"path": p+"SJ.out.tab", "class":"File"},
           {"path": p+"Log.out", "class":"File"}
         ];
     }
```

However, the above method was throwing error as I mentioned. Therefore, this is how I resolved the issue. By changing the above lines of code as following:

```
outputs:
 star_bam:
  type: File
  outputBinding:
   glob:
     ${
       var p = inputs.outFileNamePrefix?inputs.outFileNamePrefix:"";
     if (inputs.outSAMtype.indexOf("SortedByCoordinate") > -1) {
        return p+"Aligned.sortedByCoord.out.bam";
        return p+"Log.final.out";
     }
     }
  

```

**Comment by hubentu** [comment]
Hi @ranijames @mr-c ,

I got similar error when capturing the secondary file using cwltool 1.0.20190228155703. It works well with version 1.0.20180302231433.

My samtools_index script:
```
cwlVersion: v1.0
class: CommandLineTool
baseCommand:
- samtools
- index
requirements:
- class: InitialWorkDirRequirement
  listing:
  - $(inputs.bam)
inputs:
  bam:
    type: File
    inputBinding:
      position: 1
      separate: true
outputs:
  idx:
    type: File
    secondaryFiles: .bai
    outputBinding:
      glob: $(inputs.bam.basename)
```

Here are the error messages.
```
/home/qiang/.local/bin/cwltool 1.0.20190228155703
Resolved 'Idx.cwl' to 'file:///tmp/RtmpOfwOhl/tumor/Idx.cwl'
[job Idx.cwl] /tmp/vPC_4c$ samtools \
    index \
    /tmp/vPC_4c/test.bam
Could not collect memory usage, job ended before monitoring began.
[job Idx.cwl] Job error:
Error collecting output for parameter 'idx':
Idx.cwl:19:5: string indices must be integers, not str
[job Idx.cwl] completed permanentFail
{}
Final process status is permanentFail
```

This crashed my whole workflow... Any suggestion is appreciated!

**Comment by bogdang989** [comment]
Hi @hubentu, try switching secondaryFiles to be a list instead of a single string, i.e. 
```
outputs:
  idx:
    type: File
    secondaryFiles: 
    - .bai
    outputBinding:
      glob: $(inputs.bam.basename)
```

**Comment by hubentu** [comment]
Hi @bogdang989 ,
You fix works great! It makes sense because the outputs glob two files. Thanks!

**Comment by tetron** [comment]
Hmm, either that should not have passed validation or it should be handled correctly.

**Comment by ranijames** [comment]
@tetron Hello Peter,
My original question is not resolved yet, I am sorry, I am afraid, this issue is closed.

**Comment by bogdang989** [comment]
Hi @ranijames are you perhaps still running with the released version of cwltool? 
The fix is pushed to the master branch, but it is not yet released, so that may be why you still have the issue. You can wait for a new release, or you can install cwltool from source (please see the last command block here https://github.com/common-workflow-language/cwltool#install) and the original code you posted should work.

For the second approach you pasted:
```
outputs:
 star_bam:
  type: File
  outputBinding:
   glob:
     ${
       var p = inputs.outFileNamePrefix?inputs.outFileNamePrefix:"";
     if (inputs.outSAMtype.indexOf("SortedByCoordinate") > -1) {
        return p+"Aligned.sortedByCoord.out.bam";
        return p+"Log.final.out";
     }
     }
```
reason why log file is not captured is that when a `return` line is executed in JS, the expression is completed with the returned value, i.e.  `return p+"Aligned.sortedByCoord.out.bam";` will return the bam file and exit.
