### ISSUE TITLE
error message: Type property "stdout" not a valid Avro schema

### ISSUE THREAD

**Issue by wgerlach** [common-workflow-language/cwltool#1128]
I am not sure if that is my mistake or a bug in the cwltool.

## Expected Behavior
Tell us what should happen
CommandLineTool should run without error message.

## Actual Behavior
Got this error message:
```text
ERROR Tool definition failed validation:
cwl_tool.yaml:4:1: Type property "stdout" not a valid Avro schema: Could not make an Avro Schema object from stdout.
```

## Workflow Code
```
class: CommandLineTool
id: '#tool'
inputs: []
outputs:
- id: out
  type: stdout
hints:
- class: ResourceRequirement
  ramMin: 8
requirements:
- class: InlineJavascriptRequirement
  expressionLib:
  - function foo() { return 2; }
cwlVersion: v1.0
arguments:
- valueFrom: echo
- valueFrom: $(foo())
stdout: whatever.txt

```

## Full Traceback
```pytb
cwltool --debug  --validate cwl_tool.yaml 
INFO /usr/bin/cwltool 1.0.20190603140227
INFO Resolved 'cwl_tool.yaml' to 'file:///Users/wolfganggerlach/awe_data/work/e2/2d/d3/e22dd330-07bc-4a5a-96a6-28c3807a02c7__main_tool_0/cwl_tool.yaml'
ERROR Tool definition failed validation:
cwl_tool.yaml:4:1: Type property "stdout" not a valid Avro schema: Could not make an Avro Schema object from stdout.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/schema_salad/avro/schema.py", line 304, in __init__
    type_schema = make_avsc_object(cast(Dict[Text, Text], atype), names)
  File "/usr/lib/python3.6/site-packages/schema_salad/avro/schema.py", line 573, in make_avsc_object
    raise SchemaParseException(fail_msg)
schema_salad.avro.schema.SchemaParseException: Could not make an Avro Schema object from stdout.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cwltool/process.py", line 547, in __init__
    schema.convert_to_dict(self.outputs_record_schema), self.names)
  File "/usr/lib/python3.6/site-packages/schema_salad/avro/schema.py", line 556, in make_avsc_object
    return RecordSchema(name, namespace, fields, names, atype, doc, other_props)
  File "/usr/lib/python3.6/site-packages/schema_salad/avro/schema.py", line 501, in __init__
    field_objects = RecordSchema.make_field_objects(fields, names)
  File "/usr/lib/python3.6/site-packages/schema_salad/avro/schema.py", line 467, in make_field_objects
    other_props)
  File "/usr/lib/python3.6/site-packages/schema_salad/avro/schema.py", line 308, in __init__
    % (atype, e))
schema_salad.avro.schema.SchemaParseException: Type property "stdout" not a valid Avro schema: Could not make an Avro Schema object from stdout.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cwltool/main.py", line 682, in main
    tool = make_tool(uri, loadingContext)
  File "/usr/lib/python3.6/site-packages/cwltool/load_tool.py", line 354, in make_tool
    tool = loadingContext.construct_tool_object(processobj, loadingContext)
  File "/usr/lib/python3.6/site-packages/cwltool/workflow.py", line 51, in default_make_tool
    return command_line_tool.CommandLineTool(toolpath_object, loadingContext)
  File "/usr/lib/python3.6/site-packages/cwltool/command_line_tool.py", line 246, in __init__
    super(CommandLineTool, self).__init__(toolpath_object, loadingContext)
  File "/usr/lib/python3.6/site-packages/cwltool/process.py", line 547, in __init__
    schema.convert_to_dict(self.outputs_record_schema), self.names)
  File "/usr/lib/python3.6/site-packages/schema_salad/sourceline.py", line 249, in __exit__
    raise self.makeError(six.text_type(exc_value))
schema_salad.validate.ValidationException: cwl_tool.yaml:4:1: Type property "stdout" not a valid Avro schema: Could not make an Avro Schema object from stdout.
```

## Your Environment
* cwltool version: 1.0.20190603140227

**Comment by mr-c** [comment]
Notes from debugging, removing`id: #tool` removes the error. However `id: #tool` is valid as per https://www.commonwl.org/v1.0/SchemaSalad.html#Identifier_resolution & https://www.commonwl.org/v1.0/CommandLineTool.html#Identifiers

**Comment by mr-c** [comment]
And it isn't the relative `#` that is the problem, any `id` such as `id: mytool` has the same behaviour

**Comment by mr-c** [comment]
I also tested this with `cwlVersion: v1.1` and the behaviour persists.

Running with `--debug`

```
Traceback (most recent call last):
  File "/home/michael/schema_salad/schema_salad/avro/schema.py", line 309, in __init__
    type_schema = make_avsc_object(cast(Dict[Text, Text], atype), names)
  File "/home/michael/schema_salad/schema_salad/avro/schema.py", line 593, in make_avsc_object
    raise SchemaParseException(fail_msg)
schema_salad.avro.schema.SchemaParseException: Could not make an Avro Schema object from stdout.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michael/cwltool/cwltool/process.py", line 547, in __init__
    schema.convert_to_dict(self.outputs_record_schema), self.names)
  File "/home/michael/schema_salad/schema_salad/avro/schema.py", line 576, in make_avsc_object
    return RecordSchema(name, namespace, fields, names, atype, doc, other_props)
  File "/home/michael/schema_salad/schema_salad/avro/schema.py", line 521, in __init__
    field_objects = RecordSchema.make_field_objects(fields, names)
  File "/home/michael/schema_salad/schema_salad/avro/schema.py", line 481, in make_field_objects
    other_props)
  File "/home/michael/schema_salad/schema_salad/avro/schema.py", line 313, in __init__
    % (atype, e))
schema_salad.avro.schema.SchemaParseException: Type property "stdout" not a valid Avro schema: Could not make an Avro Schema object from stdout.
```

Running again using `ipdb3 $(which cwltool) --debug --validate 1128.cwl` and examining the critical line via `b cwltool/process.py:547`:

with `id: '#tool'`:
```
ipdb> p self.outputs_record_schema                                                                                                                                                                          
{'name': 'outputs_record_schema', 'type': 'record', 'fields': [ordereddict([('type', 'stdout'), ('name', 'out')])]}
```
without any `id`
```
ipdb> p self.outputs_record_schema                                                                                                                                                                          
{'name': 'outputs_record_schema', 'type': 'record', 'fields': [ordereddict([('type', 'File'), ('outputBinding', ordereddict([('glob', 'whatever.txt')])), ('name', 'out')])]}
```

So the error is earlier when `stdout` is parsed

Later I tried `cwltool --validate 1128.cwl#tool` and this succeeded. Likewise, removing the `type: stdout` but keeping the `id: #tool` and `cwltool --validate 1128.cwl` also succeeded.

**Comment by mr-c** [comment]
@tetron This feels like a cache miss in the Loader, yes?

**Comment by tetron** [comment]
@mr-c yes, I think instead of getting the updated CWL 1.1 document from the index it is missing and getting the 1.0 document.  From preliminary investigation I think somewhere it is constructing the identifier incorrectly and treating it as a relative reference instead of a did fragment so instead of `foo/bar.cwl#baz`

**Comment by wgerlach** [comment]
@tetron Why did you close this issue ?

**Comment by tetron** [comment]
Sorry about that, I was writing the previous comment on my phone on the train last night and my finger must have slipped.  However I believe this bug is fixed in master, would you like to give it a try?

**Comment by wgerlach** [comment]
I just tested it and it works, thanks!
