### ISSUE TITLE
Unhelpful error message when a parameter name is different in job file and in main workflow file.

### ISSUE THREAD

**Issue by jarnolaitinen** [common-workflow-language/cwltool#1134]
## Expected Behavior
Please give a clear error which row causes problem and what is the problem.
Now a typo in any output field paramater of any steps refers to the main workflow file so finding the place is hard. 

## Actual Behavior
ERROR I'm sorry, I couldn't load this CWL file, try again with --debug for more information.
**The error was: unhashable type: 'CommentedMap'**

## Workflow Code
Any working code, where the  parameter name is mismatching between the job file and the  name of the parameter  in the main workflow file. 

## Full Traceback
(venv) [jarno@jlcwl WesTest]$ cwltool --debug workflow.cwl workflow.yml
INFO /home/jarno/ve/venv/bin/cwltool 1.0.20190607183319
INFO Resolved 'workflow.cwl' to 'file:///home/jarno/WesTest/workflow.cwl'
ERROR I'm sorry, I couldn't load this CWL file.
The error was:
Traceback (most recent call last):
  File "/home/jarno/ve/venv/lib/python2.7/site-packages/cwltool/main.py", line 6                                                           83, in main
    tool = make_tool(uri, loadingContext)
  File "/home/jarno/ve/venv/lib/python2.7/site-packages/cwltool/load_tool.py", l                                                           ine 352, in make_tool
    tool = loadingContext.construct_tool_object(processobj, loadingContext)
  File "/home/jarno/ve/venv/lib/python2.7/site-packages/cwltool/workflow.py", li                                                           ne 55, in default_make_tool
    return Workflow(toolpath_object, loadingContext)
  File "/home/jarno/ve/venv/lib/python2.7/site-packages/cwltool/workflow.py", li                                                           ne 536, in __init__
    loadingContext.prov_obj))
  File "/home/jarno/ve/venv/lib/python2.7/site-packages/cwltool/workflow.py", li                                                           ne 570, in make_workflow_step
    return WorkflowStep(toolpath_object, pos, loadingContext, parentworkflowProv                                                           )
  File "/home/jarno/ve/venv/lib/python2.7/site-packages/cwltool/workflow.py", li                                                           ne 679, in __init__
    + "\n" + SourceLine(self.embedded_tool.tool, "outputs").makeError(
  File "/home/jarno/ve/venv/lib/python2.7/site-packages/cwltool/process.py", lin                                                           e 198, in shortname
    d = urllib.parse.urlparse(inputid)
  File "/usr/lib64/python2.7/urlparse.py", line 142, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib64/python2.7/urlparse.py", line 190, in urlsplit
    cached = _parse_cache.get(key, None)
TypeError: unhashable type: 'CommentedMap'

## Your Environment
cwltool 1.0.20190607183319

**Comment by mr-c** [comment]
Hello Jarno, and thanks for making this issue. Does the PR that was merged yesterday fix this for you?

https://github.com/common-workflow-language/cwltool/pull/1135

I'll make a new release of cwltool with that fix today.

**Comment by mr-c** [comment]
Ah, I just found your testing code; thanks @jarnolaitinen !

Looks like this is fixed now, thanks!

```
$ cwltool --validate https://github.com/jarnolaitinen/WesTest/raw/master/workflow.cwl
INFO /home/michael/cwltool/env3.7/bin/cwltool 1.0.20190618201008
ERROR Tool definition failed validation:
https://github.com/jarnolaitinen/WesTest/raw/master/workflow.cwl:22:9: Workflow step output 'unzipped_file' does not correspond to
https://github.com/jarnolaitinen/WesTest/raw/master/gunzip.cwl:20:1:   tool output (expected 'gunzipped_file')
```
