### ISSUE TITLE
Can't load directory with files having $ in filename

### ISSUE THREAD

**Issue by hubentu** [common-workflow-language/cwltool#1149]
Error happened when cwltool load directory with files that have "$" in filenames.

## Expected Behavior
To load directory with any files.

## Actual Behavior
If there is a file with "$" filename in a directory, the directory could not be loaded.
For example, we define a "ls" tool to list a directory.
```
$mkdir test
$touch test/1\$2
$ls test
1$2
```

## Workflow Code
ls.cwl
```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: ls
inputs:
  dir:
    type: Directory
    inputBinding:
      separate: true
outputs:
  output:
    type: stdout
```
ls.yml
```
dir:
  class: Directory
  path: /home/qhu/tmp/test
```

## Full Traceback
```pytb
/home/qhu/.local/bin/cwltool 1.0.20180721142728
Resolved 'ls.cwl' to 'file:///home/qhu/tmp/ls.cwl'
[job ls.cwl] initializing from file:///home/qhu/tmp/ls.cwl
[job ls.cwl] {
    "dir": {
        "class": "Directory", 
        "location": "file:///home/qhu/tmp/test", 
        "basename": "test"
    }
}
Workflow error:
Invalid filename: '1$2' contains illegal characters
Traceback (most recent call last):
  File "/home/qhu/.local/lib/python2.7/site-packages/cwltool/main.py", line 606, in main
    logger=_logger)
  File "/home/qhu/.local/lib/python2.7/site-packages/cwltool/executors.py", line 39, in __call__
    return self.execute(*args, **kwargs)
  File "/home/qhu/.local/lib/python2.7/site-packages/cwltool/executors.py", line 89, in execute
    self.run_jobs(process, job_order_object, logger, runtime_context)
  File "/home/qhu/.local/lib/python2.7/site-packages/cwltool/executors.py", line 141, in run_jobs
    for job in jobiter:
  File "/home/qhu/.local/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 402, in job
    visit_class([builder.files, builder.bindings], ("File", "Directory"), _check_adjust)
  File "/home/qhu/.local/lib/python2.7/site-packages/cwltool/utils.py", line 233, in visit_class
    visit_class(d, cls, op)
  File "/home/qhu/.local/lib/python2.7/site-packages/cwltool/utils.py", line 233, in visit_class
    visit_class(d, cls, op)
  File "/home/qhu/.local/lib/python2.7/site-packages/cwltool/utils.py", line 230, in visit_class
    visit_class(rec[d], cls, op)
  File "/home/qhu/.local/lib/python2.7/site-packages/cwltool/utils.py", line 233, in visit_class
    visit_class(d, cls, op)
  File "/home/qhu/.local/lib/python2.7/site-packages/cwltool/utils.py", line 228, in visit_class
    op(rec)
  File "/home/qhu/.local/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 207, in check_adjust
    file_o["basename"]))
WorkflowException: Invalid filename: '1$2' contains illegal characters

```

## Your Environment
* cwltool version: 
1.0.20180721142728

**Comment by tetron** [comment]
For cwltool specifically, you can use `--relax-path-checks`

**Comment by hubentu** [comment]
It works. Thanks!
