### ISSUE TITLE
Empty hints invalid

### ISSUE THREAD

**Issue by garyluu** [common-workflow-language/cwltool#1150]
## Expected Behavior
cwl v1.0 file that was valid before with cwltool 1.0.20181217162649 should be valid with cwltool 1.0.20190621234233

## Actual Behavior
```
$ cwltool --validate thing.cwl
ERROR I'm sorry, I couldn't load this CWL file, try again with --debug for more information.
The error was: argument of type 'NoneType' is not iterable
```

## Workflow Code
```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: [tar, xf]
hints: []
inputs:
  tarfile:
    type: File
    inputBinding:
      position: 1
  extractfile:
    type: string
    inputBinding:
      position: 2
outputs:
  example_out:
    type: File
    outputBinding:
      glob: $(inputs.extractfile)



```

## Full Traceback
```pytb
ERROR I'm sorry, I couldn't load this CWL file.
The error was: 
Traceback (most recent call last):
  File "/home/gluu/dockstore/venv/local/lib/python2.7/site-packages/cwltool/main.py", line 667, in main
    skip_schemas=args.skip_schemas)
  File "/home/gluu/dockstore/venv/local/lib/python2.7/site-packages/cwltool/load_tool.py", line 309, in resolve_and_validate_document
    processobj, document_loader, fileuri, loadingContext.enable_dev, metadata)))
  File "/home/gluu/dockstore/venv/local/lib/python2.7/site-packages/schema_salad/sourceline.py", line 188, in cmap
    d[k] = cmap(v, lc=d.lc.data[k], fn=fn)
  File "/home/gluu/dockstore/venv/local/lib/python2.7/site-packages/schema_salad/sourceline.py", line 195, in cmap
    if k in d.lc.data:
TypeError: argument of type 'NoneType' is not iterable

```

## Your Environment
* cwltool version: 
Before: cwltool 1.0.20181217162649
After: cwltool 1.0.20190621234233

**Comment by mr-c** [comment]
@garyluu Thanks for reporting this! This is a bug that needs fixing (and a conformance tests added).

**Comment by ballaneypranav** [comment]
Hi! I ran cwltool on this file, and it works perfectly. Has this bug been fixed?
(Installed v3.0.20200324120055 from source.)

**Comment by kyoai-zhao** [comment]
Verified against current main (baefdcb): a tool with only empty hints (`hints: []` or sole empty list items) now parses and validates fine — this issue appears fixed. Suggest closing.
