### ISSUE TITLE
misleading error message when string is passed where File is expected

### ISSUE THREAD

**Issue by pvanheus** [common-workflow-language/cwltool#1199]
## Expected Behavior
When a `string` type parameter is passed and a `File` or `Directory` is expected, `cwltool` should tell the user that the input parameter is the wrong type.

## Actual Behavior
cwltool shows the error message (for input named `input1`):

```
the `input1` field is not valid because
                 is not a dict
```
## Workflow Code
```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: CommandLineTool

inputs:
  input1:
      type: File
      inputBinding:
        position: 1

baseCommand: cat 

stdout: output.txt
outputs:
  output:
    type: stdout
```

or with `Directory`

```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: CommandLineTool

inputs:
  input1:
      type: Directory
      inputBinding:
        position: 1

baseCommand: ls

stdout: output.txt
outputs:
  output:
    type: stdout
```

and input YML:

```
input1: test1.cwl
```

## Full Traceback
```pytb
Traceback (most recent call last):
  File "/home/pvh/anaconda3/envs/cwltool/lib/python3.7/site-packages/cwltool/main.py", line 834, in main
    logger=_logger)
  File "/home/pvh/anaconda3/envs/cwltool/lib/python3.7/site-packages/cwltool/executors.py", line 46, in __call__
    return self.execute(*args, **kwargs)
  File "/home/pvh/anaconda3/envs/cwltool/lib/python3.7/site-packages/cwltool/executors.py", line 106, in execute
    self.run_jobs(process, job_order_object, logger, runtime_context)
  File "/home/pvh/anaconda3/envs/cwltool/lib/python3.7/site-packages/cwltool/executors.py", line 169, in run_jobs
    for job in jobiter:
  File "/home/pvh/anaconda3/envs/cwltool/lib/python3.7/site-packages/cwltool/command_line_tool.py", line 430, in job
    builder = self._init_job(job_order, runtimeContext)
  File "/home/pvh/anaconda3/envs/cwltool/lib/python3.7/site-packages/cwltool/process.py", line 657, in _init_job
    raise_from(WorkflowException("Invalid job input record:\n" + Text(err)), err)
  File "/home/pvh/anaconda3/envs/cwltool/lib/python3.7/site-packages/future/utils/__init__.py", line 400, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
cwltool.errors.WorkflowException: Invalid job input record:
test1.yml:1:1: the `input1` field is not valid because
test1.yml:1:1:   is not a dict
```

## Your Environment
* cwltool version: 1.0.20190915164430

**Comment by colindaven** [comment]
yes, this is a very cryptic error message. I'm a CWL beginner, trying the use the BD Rhapsody single cell pipeline, and getting this repeatedly.

```
the 'Reference_Genome' field is not valid because
                               is not a dict
```

Not a good user experience so far!

**Comment by mr-c** [comment]
New error message
```
$ cwltool   1199_file.cwl 1199_file.yml 
INFO /home/michael/cwltool/env3.11/bin/cwltool 3.1
INFO Resolved '1199_file.cwl' to 'file:///home/michael/cwltool/1199_file.cwl'
ERROR Workflow error, try again with --debug for more information:
Invalid job input record:
1199_file.yml:1:1: the 'input1' field is not valid because
                     is not a dict. Expected a File object.
```
