### ISSUE TITLE
only the last SchemaDefRequirement seems to be registered.

### ISSUE THREAD

**Issue by itajaja** [common-workflow-language/cwltool#1200]
## Expected Behavior
It should work

## Actual Behavior
instead received error:

```
ERROR Tool definition failed validation:
local-tests/workflow2.cwl:19:1: Type property "Foo" not a valid Avro schema: Could not make an Avro Schema object from Foo.
```

Now, if we remove the second `SchemaDefRequirement` then it works, or if we swap the order of the two `SchemaDefRequirement` entries. it feels like only the last `SchemaDefRequirement` is used in Avro. Not sure if this is a cwltool error or an schema_salad, or maybe it's by design.

## Workflow Code
```yml
cwlVersion: v1.0
class: Workflow
label: HelloWorld
requirements:
- class: StepInputExpressionRequirement
- class: InlineJavascriptRequirement
- class: MultipleInputFeatureRequirement
- class: SchemaDefRequirement
  types:
  - name: Foo
    type: enum
    symbols: [a, b]
- class: SchemaDefRequirement
  types:
  - name: Bar
    type: enum
    symbols: [c, d]

inputs:
  foo:
    type: Foo

outputs: {}

steps: {}
```

## Full Traceback
```pytb
Traceback (most recent call last):
  File "/Users/gtagliabue/.pyenv/versions/3.7.2/envs/cwltool/lib/python3.7/site-packages/schema_salad/avro/schema.py", line 297, in __init__
    type_schema = make_avsc_object(cast(Dict[Text, Text], atype), names)
  File "/Users/gtagliabue/.pyenv/versions/3.7.2/envs/cwltool/lib/python3.7/site-packages/schema_salad/avro/schema.py", line 599, in make_avsc_object
    raise SchemaParseException(fail_msg)
schema_salad.avro.schema.SchemaParseException: Could not make an Avro Schema object from Foo.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gtagliabue/workspace/qsi/cwltool/cwltool/process.py", line 542, in __init__
    schema.convert_to_dict(self.inputs_record_schema), self.names)
  File "/Users/gtagliabue/.pyenv/versions/3.7.2/envs/cwltool/lib/python3.7/site-packages/schema_salad/avro/schema.py", line 581, in make_avsc_object
    name, namespace, fields, names, atype, doc, other_props
  File "/Users/gtagliabue/.pyenv/versions/3.7.2/envs/cwltool/lib/python3.7/site-packages/schema_salad/avro/schema.py", line 524, in __init__
    field_objects = RecordSchema.make_field_objects(fields, names)
  File "/Users/gtagliabue/.pyenv/versions/3.7.2/envs/cwltool/lib/python3.7/site-packages/schema_salad/avro/schema.py", line 482, in make_field_objects
    atype, name, has_default, default, order, names, doc, other_props
  File "/Users/gtagliabue/.pyenv/versions/3.7.2/envs/cwltool/lib/python3.7/site-packages/schema_salad/avro/schema.py", line 300, in __init__
    'Type property "%s" not a valid Avro schema: %s' % (atype, e)
schema_salad.avro.schema.SchemaParseException: Type property "Foo" not a valid Avro schema: Could not make an Avro Schema object from Foo.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gtagliabue/workspace/qsi/cwltool/cwltool/main.py", line 690, in main
    tool = make_tool(uri, loadingContext)
  File "/Users/gtagliabue/workspace/qsi/cwltool/cwltool/load_tool.py", line 352, in make_tool
    tool = loadingContext.construct_tool_object(processobj, loadingContext)
  File "/Users/gtagliabue/workspace/qsi/cwltool/cwltool/workflow.py", line 58, in default_make_tool
    return Workflow(toolpath_object, loadingContext)
  File "/Users/gtagliabue/workspace/qsi/cwltool/cwltool/workflow.py", line 511, in __init__
    toolpath_object, loadingContext)
  File "/Users/gtagliabue/workspace/qsi/cwltool/cwltool/process.py", line 542, in __init__
    schema.convert_to_dict(self.inputs_record_schema), self.names)
  File "/Users/gtagliabue/.pyenv/versions/3.7.2/envs/cwltool/lib/python3.7/site-packages/schema_salad/sourceline.py", line 298, in __exit__
    raise_from(self.makeError(six.text_type(exc_value)), exc_value)
  File "/Users/gtagliabue/.pyenv/versions/3.7.2/envs/cwltool/lib/python3.7/site-packages/future/utils/__init__.py", line 400, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
schema_salad.validate.ValidationException: local-tests/workflow2.cwl:19:1: Type property "Foo" not a valid Avro schema: Could not make an Avro Schema object from Foo.
```

## Your Environment
* cwltool version: `1.0.20190915164430`

**Comment by itajaja** [comment]
I think the root cause is that `get_requirement` gets the latest requirement by requirement type, so it implicitly allow only one requirement. is there a spec for this behavior?

**Comment by itajaja** [comment]
I added a strawman PR https://github.com/common-workflow-language/cwltool/pull/1201

🙏

**Comment by mr-c** [comment]
@itajaja Hello, this is by design. You can only have one of each `class` under `requirements` as per CWL v1.x. To include multiple type definitions combine them under `types`:

``` cwl
cwlVersion: v1.0
class: Workflow
label: HelloWorld
requirements:
- class: SchemaDefRequirement
  types:
  - name: Foo
    type: enum
    symbols: [a, b]
  - name: Bar
    type: enum
    symbols: [c, d]

inputs:
  foo:
    type: Foo

outputs: {}

steps: {}
```

**Comment by itajaja** [comment]
Thanks @mr-c, a couple questions:
Where is the specification that explains that?

Secondly, if a schema that I don't own exports a SchemaDefRequrement, then I don't have any way to do that. let's say `https://example.com/types.cwl` exports the following:

```
class: SchemaDefRequirement
types:
- name: TypeA
  ...
- name: TypeB
  ...
- name: TypeC
  ...
- name: TypeZ
  ...
```

and if I want to use this, I do `$import https://example.com/types.cwl`, so I can't neither define my own types inline or import types from another file. The alternative would be to ask the provider of the schema to export the types one by one, but that would require a single `$import` line for each of the defined type, which could be awkward if the types are many. am I missing something?

**Comment by tetron** [comment]
> The alternative would be to ask the provider of the schema to export the types one by one, but that would require a single $import line for each of the defined type, which could be awkward if the types are many.

This may work as well, to import a single type from another file: `{$import: "https://example.com/types.cwl#TypeZ}`

However, as you mention, you would have to import each type separately into your own SchemaDefRequirement, which is awkward.

> am I missing something?

No, you have correctly described the current state.  This is an area of the specification that needs to be improved in future revisions.

**Comment by itajaja** [comment]
Great, thanks for the clarification 👏
