### ISSUE TITLE
'First example' fails with Python import error

### ISSUE THREAD

**Issue by stevekm** [common-workflow-language/cwltool#1217]
Trying to run through the intro guide's [first example](https://www.commonwl.org/user_guide/02-1st-example/index.html) and `cwl-runner` fails with an error:

```
$ cwl-runner 1st-tool.cwl echo-job.yml
Traceback (most recent call last):
  File "/Users/steve/projects/cwl-test1/conda/bin/cwl-runner", line 6, in <module>
    from cwltool.main import main
  File "/Users/steve/projects/cwl-test1/conda/lib/python3.6/site-packages/cwltool/main.py", line 18, in <module>
    import schema_salad.validate as validate
  File "/Users/steve/projects/cwl-test1/conda/lib/python3.6/site-packages/schema_salad/__init__.py", line 35, in <module>
    from past import autotranslate  # type: ignore
ImportError: cannot import name 'autotranslate'
```

## Your Environment
* cwltool version: 

```
$ cwltool --version
Traceback (most recent call last):
  File "/Users/steve/projects/cwl-test1/conda/bin/cwltool", line 11, in <module>
    load_entry_point('cwltool==1.0.20180225105849', 'console_scripts', 'cwltool')()
  File "/Users/steve/projects/cwl-test1/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/steve/projects/cwl-test1/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/Users/steve/projects/cwl-test1/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/Users/steve/projects/cwl-test1/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/steve/projects/cwl-test1/conda/lib/python3.6/site-packages/cwltool/main.py", line 18, in <module>
    import schema_salad.validate as validate
  File "/Users/steve/projects/cwl-test1/conda/lib/python3.6/site-packages/schema_salad/__init__.py", line 35, in <module>
    from past import autotranslate  # type: ignore
ImportError: cannot import name 'autotranslate'
```

Installed with `conda`;

```
conda install -y \
	conda=4.5.4 \
	bioconda::cwltool=1.0.20180225105849 \
	conda-forge::cwl_runner=1.0
```

I tried searching for this missing `autotranslate` package in `conda` but did not see it listed.  Any suggestions? Thanks.

**Comment by mr-c** [comment]
Hello @stevekm 

This `1.0.2018022510584` is a very old version of `cwltool`. Perhaps the problem is that you are installing from `bioconda` instead of `conda-forge`?

https://github.com/conda-forge/cwltool-feedstock#current-release-info

In this repository we only support `pip` based installs.

After trying the latest from conda I suggest filling an issue there if the problem remains.

Cheers,

**Comment by anujatayal** [comment]
How did you resolve the issue?
