### ISSUE TITLE
Workflow that passes validation fails to pack

### ISSUE THREAD

**Issue by KerstenBreuer** [common-workflow-language/cwltool#1238]
## Expected Behavior
If a workflow that passes validation (`cwltool --validate`) there should be no errors when packing.

## Actual Behavior
In this specific case, I tested the workflow https://raw.githubusercontent.com/Athanaseus/2gc-pipeline/master/selfcal_simulation.cwl .

It passes the validation (`cwltool --validate https://raw.githubusercontent.com/Athanaseus/2gc-pipeline/master/selfcal_simulation.cwl`) but fails when running:
```
cwltool --pack --debug \
https://raw.githubusercontent.com/Athanaseus/2gc-pipeline/master/selfcal_simulation.cwl > /dev/null
```

Also see CompEpigen/CWLab#38.
(@Athanaseus please have a look.)
## Workflow Code
Please find it at https://raw.githubusercontent.com/Athanaseus/2gc-pipeline/master/selfcal_simulation.cwl.

## Full Traceback
The error thrown was:
```
INFO /usr/local/bin/cwltool 1.0.20180809224403
ERROR I'm sorry, I couldn't load this CWL file.
The error was:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cwltool/main.py", line 916, in main
    print_pack(loadingContext.loader, processobj, uri, metadata)
  File "/usr/local/lib/python3.6/dist-packages/cwltool/main.py", line 563, in print_pack
    packed = pack(document_loader, processobj, uri, metadata)
  File "/usr/local/lib/python3.6/dist-packages/cwltool/pack.py", line 222, in pack
    import_embed(packed, set())
  File "/usr/local/lib/python3.6/dist-packages/cwltool/pack.py", line 118, in import_embed
    import_embed(d[k], seen)
  File "/usr/local/lib/python3.6/dist-packages/cwltool/pack.py", line 104, in import_embed
    import_embed(v, seen)
  File "/usr/local/lib/python3.6/dist-packages/cwltool/pack.py", line 118, in import_embed
    import_embed(d[k], seen)
  File "/usr/local/lib/python3.6/dist-packages/cwltool/pack.py", line 108, in import_embed
    if d[n] in seen:
TypeError: unhashable type: 'CommentedMap'
```

## Your Environment
* cwltool version: 1.0.20180809224403

**Comment by mr-c** [comment]
Can you try with a new `cwltool` Version 1.0.20180809224403 is almost a year and a half old :-)

**Comment by mr-c** [comment]
@KerstenBreuer Thanks for this issue! I've got a fix at https://github.com/common-workflow-language/cwltool/pull/1239 , can you try that out?

**Comment by KerstenBreuer** [comment]
Hi @mr-c,

thanks a lot for the supreme support. It's working perfectly.
