### ISSUE TITLE
Special characters in output file paths are not decoded / encoded correctly

### ISSUE THREAD

**Issue by ionox0** [common-workflow-language/cwltool#1260]
##  Expected Behavior

Output files with special characters in their path should be found correctly

## Actual Behavior

The error message received using Toil through `toil-cwl-runner` appears as:
```
WorkflowException: File is missing: file:///run_group_0-1.3.32%2B0.99935b2.dirty_6U6R8r_38847/tmp9uzFCO/e/6/out_tmpdir1rwz_m/out_tmpdir1rwz_m/info.txt
```

Note that the `+` seems to be converted to `%2B` and then interpreted literally instead of decoded back to `+`

## Workflow Code
Here is a minimally-reproducible example using cwltool:

##### tool.cwl
```
cwlVersion: v1.0
class: CommandLineTool
requirements:
  ShellCommandRequirement: {}

baseCommand: echo

arguments:
- test
- valueFrom: '>'
  shellQuote: false
- blah+blah

inputs: []

outputs:
  output_one:
    type: File
    outputBinding:
      glob: blah+blah
```

## Full Traceback
```pytb
/home/johnsoni/virtualenvs/pipeline_1.2.9/bin/cwltool 1.0.20181118133959
Resolved 'tool.cwl' to 'file:///ifs/work/bergerm1/Innovation/sandbox/ian/plus_test/tool.cwl'
[job tool.cwl] initializing from file:///ifs/work/bergerm1/Innovation/sandbox/ian/plus_test/tool.cwl
[job tool.cwl] {
    "test": "test"
}
[job tool.cwl] path mappings is {}
[job tool.cwl] command line bindings is [
    {
        "position": [
            -1000000, 
            0
        ], 
        "datum": "echo"
    }, 
    {
        "position": [
            0, 
            0
        ], 
        "datum": "test"
    }, 
    {
        "shellQuote": false, 
        "position": [
            0, 
            1
        ], 
        "valueFrom": ">"
    }, 
    {
        "position": [
            0, 
            2
        ], 
        "datum": "blah+blah"
    }
]
[job tool.cwl] initial work dir {}
[job tool.cwl] /scratch/tmpXOj9nb$ /bin/sh \
    -c \
    'echo' 'test' > 'blah+blah'
[job tool.cwl] Job error:
Error collecting output for parameter 'output_one':
tool.cwl:17:3: Traceback (most recent call last):
tool.cwl:17:3: 
tool.cwl:17:3:   File "/home/johnsoni/virtualenvs/pipeline_1.2.9/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 604, in collect_output_ports
tool.cwl:17:3:     compute_checksum=compute_checksum)
tool.cwl:17:3: 
tool.cwl:17:3:   File "/home/johnsoni/virtualenvs/pipeline_1.2.9/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 694, in collect_output
tool.cwl:17:3:     with fs_access.open(rfile["location"], "rb") as f:
tool.cwl:17:3: 
tool.cwl:17:3:   File "/home/johnsoni/virtualenvs/pipeline_1.2.9/lib/python2.7/site-packages/cwltool/stdfsaccess.py", line 41, in open
tool.cwl:17:3:     return open(self._abs(fn), mode)
tool.cwl:17:3: 
tool.cwl:17:3: IOError: [Errno 2] No such file or directory: '/scratch/tmpXOj9nb/blah%2Bblah'
[job tool.cwl] completed permanentFail
[job tool.cwl] {}
[job tool.cwl] Removing input staging directory /scratch/tmpbCtQN8
[job tool.cwl] Removing temporary directory /scratch/tmpjfvyet
{}
Final process status is permanentFail
```

## Your Environment
* cwltool version: `1.0.20181118133959`

**Comment by tetron** [comment]
Hi @ionox0 your reported version is from 2018, can you try a newer version?

**Comment by mr-c** [comment]
Fixed in https://github.com/common-workflow-language/cwltool/pull/1446
