### ISSUE TITLE
Error regarding cachedir ceation for job without 'success' status but still with a cachedir

### ISSUE THREAD

**Issue by jfouret** [common-workflow-language/cwltool#1267]
## Expected Behavior
After a crash I was expecting to go on with my analysis using cache dir

## Actual Behavior

When there is a cache dir with `.status` set to  `success` it does behave as expected. However when there is the `permanentFail` status, cwl tries to create a dir with the `os.makedirs(jobcache)` python instruction. Then a `FileExistsError` raises because the cachedir corresponding to the permanentfail already exists.

## Workflow Code
I used the option `--cachedir /media/hdd_storage/tmp/BATCH_NAME_._pipeline-name_._1585223540/d9106db4979617eaf77c35c474411088`

## Full Traceback
```pytb
[2020-03-27 09:05:18] INFO [job fastq_screen_20] Output of job will be cached in /media/hdd_storage/tmp/BATCH_NAME_._pipeline-name_._1585223540/d9106db4979617eaf77c35c474411088
[2020-03-27 09:05:18] ERROR Unexpected exception
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/cwltool/workflow.py", line 1043, in job
    runtimeContext,
  File "/home/user/.local/lib/python3.6/site-packages/cwltool/command_line_tool.py", line 530, in job
    os.makedirs(jobcache)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/media/hdd_storage/tmp/BATCH_NAME_._pipeline-name_._1585223540/d9106db4979617eaf77c35c474411088'
[2020-03-27 09:05:18] ERROR Cannot make scatter job: [Errno 17] File exists: '/media/hdd_storage/tmp/BATCH_NAME_._pipeline-name_._1585223540/d9106db4979617eaf77c35c474411088'
[2020-03-27 09:05:18] DEBUG 
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/cwltool/workflow.py", line 1043, in job
    runtimeContext,
  File "/home/user/.local/lib/python3.6/site-packages/cwltool/command_line_tool.py", line 530, in job
    os.makedirs(jobcache)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/media/hdd_storage/tmp/BATCH_NAME_._pipeline-name_._1585223540/d9106db4979617eaf77c35c474411088'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/cwltool/workflow.py", line 1124, in parallel_st
eps
    for j in step:
  File "/home/user/.local/lib/python3.6/site-packages/cwltool/workflow.py", line 265, in job
    for j in self.step.job(joborder, output_callback, runtimeContext):
  File "/home/user/.local/lib/python3.6/site-packages/cwltool/workflow.py", line 1051, in job
    raise WorkflowException(str(exc)) from exc
cwltool.errors.WorkflowException: [Errno 17] File exists: '/media/hdd_storage/tmp/BATCH_NAME_._pipeline-name_._1585223540/d9106db4979617eaf77c35c474411088'
```

## Your Environment
* cwltool version: 
`cwltool 3.0.20200324120055`

**Comment by jfouret** [comment]
## Workaround 
Delete all folders with permanentFail status : 
```
cd /media/hdd_storage/tmp/BATCH_NAME_._pipeline-name_._1585223540
for cachedir in $(ls | grep -v status) ; do echo "$cachedir:$(cat ${cachedir}.status)" ; done | grep permanentFail | cut -f 1 -d ':' > ../permanentFail.list
for cachedir in $(cat ../permanentFail.list) ; do sudo rm -rf $cachedir ${cachedir}.status ; done
```

## Potential source of the error
Files within cache folders were owed by root. This is a consequences of using docker container and lanching cwltool with the `--no-match-user` option.

To delete this folders I had to use `sudo`.

The fact that there is files owned by root is those folders is probably linked with the initial errors since it would be impossible for a non-root user to clean those folders.

**Comment by mr-c** [comment]
Hello @jfouret and thank you for sharing your experiences. I'm glad you figured out what was going on.

We should try to detect this situation and give a better error message, yes.

Beyond that, do you have any other suggestions? This situation is one of the reasons that `--no-match-user` is not recommended

**Comment by jfouret** [comment]
Yes,

I think that the problem is definitely linked with `--no-match-user` incompatibility with cache dir function and for obvious security reasons. 

Indeed, I think you the only safe thing to do is a more detailed error message.

Hence the final fix from my side was to update my docker image to allow user matching :-).
