### ISSUE TITLE
cwltool --pack throws error

### ISSUE THREAD

**Issue by thomasyu888** [common-workflow-language/cwltool#128]
```
git clone https://github.com/Sage-Bionetworks/SMC-RNA-Examples.git
cwltool --debug --pack SMC-RNA-Examples/workflow/smcFusion-tophat-workflow.cwl 
/usr/local/bin/cwltool 1.0.20160714182449
I'm sorry, I couldn't load this CWL file.  The error was:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cwltool/main.py", line 633, in main
    stdout.write(print_pack(document_loader, processobj, uri, metadata))
  File "/usr/local/lib/python2.7/site-packages/cwltool/main.py", line 517, in print_pack
    flatten_deps(deps, fdeps)
  File "/usr/local/lib/python2.7/site-packages/cwltool/main.py", line 476, in flatten_deps
    flatten_deps(s, files)
  File "/usr/local/lib/python2.7/site-packages/cwltool/main.py", line 478, in flatten_deps
    files.add(d["path"])
KeyError: 'path'
```

**Comment by mr-c** [comment]
@thomasyu888 Does the recently merged fix work for you?

**Comment by thomasyu888** [comment]
It works great! Thanks!  Just a note, `pip install cwlref-runner`, does not install the most recently merged version yet.  I had to install from source.

**Comment by thomasyu888** [comment]
Works now!
