### ISSUE TITLE
--leave-tmpdir doesn't work

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#129]
Use https://github.com/common-workflow-language/workflows/blob/58d006a14e4e599fdea19fc3cb65a7a04d31b403/tools/bwa-index.cwl

```
(env) michael@dan:~/workflows$ cwltool --debug --leave-tmpdir --no-container tools/bwa-index.cwl --reference_genome workflows/lobSTR/tmp_1.fq 
/home/michael/cwltool/env/bin/cwltool 1.0.20160713142504
Parsed job order from command line: {
    "blocksize": null, 
    "reference_genome": {
        "class": "File", 
        "location": "file:///home/michael/workflows/workflows/lobSTR/tmp_1.fq"
    }, 
    "id": "tools/bwa-index.cwl", 
    "algorithm": null, 
    "job_order": null
}
[job bwa-index.cwl] initializing from file:///home/michael/workflows/tools/bwa-index.cwl
[job bwa-index.cwl] {
    "blocksize": null, 
    "reference_genome": {
        "basename": "tmp_1.fq", 
        "class": "File", 
        "location": "file:///home/michael/workflows/workflows/lobSTR/tmp_1.fq"
    }, 
    "algorithm": null, 
    "job_order": null
}
[job bwa-index.cwl] path mappings is {
    "file:///home/michael/workflows/workflows/lobSTR/tmp_1.fq": [
        "/home/michael/workflows/workflows/lobSTR/tmp_1.fq", 
        "/tmp/tmpYZb5Ev/stg7a2e3e0f-9b84-48a3-9b0b-0c971831f897/tmp_1.fq", 
        "File"
    ]
}
[job bwa-index.cwl] command line bindings is [
    {
        "position": [
            -1000000, 
            0
        ], 
        "valueFrom": "bwa"
    }, 
    {
        "position": [
            -1000000, 
            1
        ], 
        "valueFrom": "index"
    }, 
    {
        "position": [
            0, 
            "algorithm"
        ], 
        "prefix": "-a", 
        "valueFrom": null
    }, 
    {
        "position": [
            0, 
            "blocksize"
        ], 
        "prefix": "-b", 
        "valueFrom": null
    }, 
    {
        "position": [
            3, 
            "reference_genome"
        ], 
        "valueFrom": {
            "basename": "tmp_1.fq", 
            "nameroot": "tmp_1", 
            "nameext": ".fq", 
            "location": "file:///home/michael/workflows/workflows/lobSTR/tmp_1.fq", 
            "path": "/tmp/tmpYZb5Ev/stg7a2e3e0f-9b84-48a3-9b0b-0c971831f897/tmp_1.fq", 
            "dirname": "/tmp/tmpYZb5Ev/stg7a2e3e0f-9b84-48a3-9b0b-0c971831f897", 
            "class": "File"
        }
    }
]
[job bwa-index.cwl] /tmp/tmpy6_35R$ bwa \
    index \
    /tmp/tmpYZb5Ev/stg7a2e3e0f-9b84-48a3-9b0b-0c971831f897/tmp_1.fq
Exception while running job
Traceback (most recent call last):
  File "/home/michael/cwltool/cwltool/job.py", line 178, in run
    self.outdir, separateDirs=False)
  File "/home/michael/cwltool/cwltool/pathmapper.py", line 90, in __init__
    self.setup(referenced_files, basedir)
  File "/home/michael/cwltool/cwltool/pathmapper.py", line 130, in setup
    self.visit(fob, stagedir, basedir)
  File "/home/michael/cwltool/cwltool/pathmapper.py", line 105, in visit
    self.visitlisting(obj.get("listing", []), stagedir, basedir)
  File "/home/michael/cwltool/cwltool/pathmapper.py", line 95, in visitlisting
    tgt = os.path.join(stagedir, ld["basename"])
TypeError: string indices must be integers, not str
[job bwa-index.cwl] completed permanentFail
[job bwa-index.cwl] {}
Final process status is permanentFail
[job bwa-index.cwl] Removing input staging directory /tmp/tmpYZb5Ev
[job bwa-index.cwl] Removing empty output directory /tmp/tmpy6_35R
Workflow error, try again with --debug for more information:
  Process status is ['permanentFail']
Traceback (most recent call last):
  File "/home/michael/cwltool/cwltool/main.py", line 707, in main
    **vars(args))
  File "/home/michael/cwltool/cwltool/main.py", line 218, in single_job_executor
    raise WorkflowException(u"Process status is %s" % (final_status))
WorkflowException: Process status is ['permanentFail']
(env) michael@dan:~/workflows$ ls /tmp/tmpy6_35R
ls: cannot access '/tmp/tmpy6_35R': No such file or directory

```

**Comment by mr-c** [comment]
`--leave-outputs` will preserve the working directory (`/tmp/tmpy6_35R` in the above example)

**Comment by MatthewRalston** [comment]
I am not observing the `--leave-outputs` work-around. This is still an issue IMO.

**Comment by mr-c** [comment]
Still failing as of `1.0.20170413194156`
