### ISSUE TITLE
cwltool failure when mixing cwlVersion tools in a workflow

### ISSUE THREAD

**Issue by pvanheus** [common-workflow-language/cwltool#1321]
---

## Expected Behavior
cwltool should be able to run a workflow with a mixture of cwlVersion 1.0 and cwlVersion 1.1 tools.

## Actual Behavior
This [repository](https://github.com/pvanheus/cwl-index-and-map) contains 2 tools, BWA-Index.cwl and BWA-Mem.cwl and a workflow file. The workflow can be run from the `test` folder with e.g. 

```
cwltool --debug ../index_and_map.cwl workflow_input.json
```
If both tools have `cwlVersion: v1.1` or `cwlVersion: v1.0` then the workflow completes successfully (this is with cwltool version 3.0.20200530110633 installed via conda.

If `BWA-Index.cwl` is set to `cwlVersion: v1.0` while keeping `BWA-Mem.cwl` on `cwlVersion: v1.1`, the following error happens:

```pytb
INFO /home/pvh/anaconda3/envs/cwltool/bin/cwltool 3.0.20200530110633
INFO Resolved '../index_and_map.cwl' to 'file:///home/pvh/Documents/code/SANBI/pvh-forks/cwl-index-and-map/index_and_map.cwl'
ERROR I'm sorry, I couldn't load this CWL file.
The error was: 
Traceback (most recent call last):
  File "/home/pvh/anaconda3/envs/cwltool/lib/python3.7/site-packages/cwltool/main.py", line 965, in main
    tool = make_tool(uri, loadingContext)
  File "/home/pvh/anaconda3/envs/cwltool/lib/python3.7/site-packages/cwltool/load_tool.py", line 455, in make_tool
    tool = loadingContext.construct_tool_object(processobj, loadingContext)
  File "/home/pvh/anaconda3/envs/cwltool/lib/python3.7/site-packages/cwltool/workflow.py", line 58, in default_make_tool
    return Workflow(toolpath_object, loadingContext)
  File "/home/pvh/anaconda3/envs/cwltool/lib/python3.7/site-packages/cwltool/workflow.py", line 145, in __init__
    param_to_step,
  File "/home/pvh/anaconda3/envs/cwltool/lib/python3.7/site-packages/cwltool/checker.py", line 216, in static_checker
    for p in sink.get("secondaryFiles", [])
  File "/home/pvh/anaconda3/envs/cwltool/lib/python3.7/site-packages/cwltool/checker.py", line 217, in <listcomp>
    if p.get("required", True)
AttributeError: 'str' object has no attribute 'get'
```

If `BWA-Index.cwl` is set to `cwlVersion: v1.1` and `BWA-Mem.cwl` is set to version `v1.0` then the following error happens:

```pytb
INFO /home/pvh/anaconda3/envs/cwltool/bin/cwltool 3.0.20200530110633
INFO Resolved '../index_and_map.cwl' to 'file:///home/pvh/Documents/code/SANBI/pvh-forks/cwl-index-and-map/index_and_map.cwl'
ERROR I'm sorry, I couldn't load this CWL file.
The error was: 
Traceback (most recent call last):
  File "/home/pvh/anaconda3/envs/cwltool/lib/python3.7/site-packages/cwltool/main.py", line 965, in main
    tool = make_tool(uri, loadingContext)
  File "/home/pvh/anaconda3/envs/cwltool/lib/python3.7/site-packages/cwltool/load_tool.py", line 455, in make_tool
    tool = loadingContext.construct_tool_object(processobj, loadingContext)
  File "/home/pvh/anaconda3/envs/cwltool/lib/python3.7/site-packages/cwltool/workflow.py", line 58, in default_make_tool
    return Workflow(toolpath_object, loadingContext)
  File "/home/pvh/anaconda3/envs/cwltool/lib/python3.7/site-packages/cwltool/workflow.py", line 145, in __init__
    param_to_step,
  File "/home/pvh/anaconda3/envs/cwltool/lib/python3.7/site-packages/cwltool/checker.py", line 222, in static_checker
    mylist = [p["pattern"] for p in src.get("secondaryFiles", [])]
  File "/home/pvh/anaconda3/envs/cwltool/lib/python3.7/site-packages/cwltool/checker.py", line 222, in <listcomp>
    mylist = [p["pattern"] for p in src.get("secondaryFiles", [])]
TypeError: string indices must be integers
```
## Workflow Code

See: https://github.com/pvanheus/cwl-index-and-map

## Full Traceback
See above

## Your Environment
* cwltool version: 3.0.20200530110633

**Comment by mr-c** [comment]
@pvanheus Can you test again with a recent `cwltool` version?  I feel like we might have fixed this, if not this is an important bug that we should address

**Comment by pvanheus** [comment]
This is bug no longer exists when tested with cwltool version 3.0.20200807132242.
