### ISSUE TITLE
schema_salad.exceptions.ValidationException: Not found:

### ISSUE THREAD

**Issue by reliscu** [common-workflow-language/cwltool#1335]
Trying to follow this tutorial:
https://www.commonwl.org/user_guide/02-1st-example/index.html

I got an error, and I have no clue where to go from here.

Files created:
1st-tool.cwl

```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: CommandLineTool
baseCommand: echo
inputs:
  message:
    type: string
    inputBinding:
      position: 1
outputs: []
```
echo-job.yml

```
message: Hello world!
```

command:
```
cwl-runner 1st.tool.cwl echo-job.yml
```

output:

```
INFO /Users/rebeccaeliscu/anaconda3/bin/cwl-runner 3.0.20200710214758
Traceback (most recent call last):
  File "/Users/rebeccaeliscu/anaconda3/bin/cwl-runner", line 8, in <module>
    sys.exit(main())
  File "/Users/rebeccaeliscu/anaconda3/lib/python3.8/site-packages/cwltool/main.py", line 905, in main
    uri, tool_file_uri = resolve_tool_uri(
  File "/Users/rebeccaeliscu/anaconda3/lib/python3.8/site-packages/cwltool/load_tool.py", line 100, in resolve_tool_uri
    raise ValidationException("Not found: '%s'" % argsworkflow)
schema_salad.exceptions.ValidationException: Not found: '1st.tool.cwl'
```

Notably, this command seemed to allow the workflow to run:
```
cwltool --preserve-environment PATH 1st-tool.cwl echo-job.yml 
```
Resulting in:
```
 /Users/rebeccaeliscu/anaconda3/bin/cwltool 3.0.20200710214758
INFO Resolved '1st-tool.cwl' to 'file:///Users/rebeccaeliscu/1st-tool.cwl'
INFO [job 1st-tool.cwl] /private/tmp/docker_tmp9vofkj1g$ echo \
    'Hello world!'
Hello world!
INFO [job 1st-tool.cwl] completed success
{}
INFO Final process status is success
```

If possible, can anyone help me understand what might be going on? 

## Your Environment
* cwltool version: 3.0.20200710214758
And, not sure if it's relevent, but:
Python version: Python 3.8.3
Conda version: conda 4.8.3

**Comment by tom-tan** [comment]
> command:
> ```
> cwl-runner 1st.tool.cwl echo-job.yml
> ```

Is it a typo of `1st-tool.cwl`?

**Comment by reliscu** [comment]
Yes, it is! Wow, that's embarrassing!

Thank you for seeing what I could not.
