### ISSUE TITLE
New cwltool error on expression in stdout

### ISSUE THREAD

**Issue by lijiayong** [common-workflow-language/cwltool#135]
A simple command line tool that directs word count of foo.txt to foo.txt.wc.
_wc.cwl_

```
cwlVersion: cwl:draft-3
class: CommandLineTool
baseCommand: wc
requirements:
  - class: InlineJavascriptRequirement
stdout: $(inputs.input_file.path.split('/').slice(-1)[0] + ".wc")
inputs:
  - id: input_file
    type: File
    inputBinding:
      position: 1
outputs:
  - id: output_file
    type: File
    outputBinding:
      glob: "*.wc"
```

_wc-job.yml_

```
input_file:
  class: File
  path: foo.txt
```

Error on the latest cwltool.

```
$ cwltool wc.cwl wc-job.yml 
/home/jiayong/miniconda2/bin/cwltool 1.0.20160708190014
Got workflow error
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/cwltool/main.py", line 203, in single_job_executor
    for r in jobiter:
  File "build/bdist.linux-x86_64/egg/cwltool/draft2tool.py", line 250, in job
    j.stdout = builder.do_eval(self.tool["stdout"])
  File "build/bdist.linux-x86_64/egg/cwltool/builder.py", line 205, in do_eval
    timeout=self.timeout)
  File "build/bdist.linux-x86_64/egg/cwltool/expression.py", line 146, in do_eval
    timeout=timeout)
  File "build/bdist.linux-x86_64/egg/cwltool/sandboxjs.py", line 173, in interpolate
    e = execjs(scan[w[0]+1:w[1]], jslib, timeout=timeout)
  File "build/bdist.linux-x86_64/egg/cwltool/sandboxjs.py", line 82, in execjs
    raise JavascriptException(u"Returncode was: %s\nscript was:\n%s\nstdout was: '%s'\nstderr was: '%s'\n" % (nodejs.returncode, fn_linenum(), stdoutdata, stderrdata))
JavascriptException: Returncode was: 8
...
```

It works on an earlier version.

```
$ cwltool wc.cwl wc-job.yml 
/home/jiayong2/miniconda2/bin/cwltool 1.0.20160427142240
[job 139854344405264] /data-sdc/home/jiayong2/cwl/test/wc$ wc /data-sdc/home/jiayong2/cwl/test/wc/foo.txt > /data-sdc/home/jiayong2/cwl/test/wc/foo.txt.wc
Final process status is success
{
    "output_file": {
        "size": 50, 
        "path": "/data-sdc/home/jiayong2/cwl/test/wc/foo.txt.wc", 
        "checksum": "sha1$60d6046bd05439599ff9f0d30c07fdb6c0e3c8e8", 
        "class": "File"
    }
}
```

**Comment by johnbradley** [comment]
I think this has been fixed in a more recent version.
Your example ran fine for me using the latest version (1.0.20160721123406).

I was able to reproduce a JavascriptException error with an older commit (445c18d3b7c78cb4d074fb5772c8791c1373d7e1) when running your example.

**Comment by lijiayong** [comment]
Yes, I'm really glad it's fixed. Thank you so much for letting me know!

**Comment by manu-chroma** [comment]
The example runs fine on my machine as well. Thanks, @johnbradley @lijiayong!
