### ISSUE TITLE
Error with --print-dot (Object of type date is not JSON serializable)

### ISSUE THREAD

**Issue by caballero** [common-workflow-language/cwltool#1379]
I am trying to create a graph for my workflow, but  using "cwltool --print-dot" with my CWL fails with this:

```
$ cwltool --print-dot long_read_assembly.cwl
INFO /usr/local/bin/cwltool 3.0.20200807132242
INFO Resolved 'long_read_assembly.cwl' to 'file:///mnt/c/Users/HP.ASUNA/EMBL/git/mgnify-lr/cwl/workflows/long_read_assembly.cwl'
WARNING Workflow checker warning:
long_read_assembly.cwl:30:5:  Source 'align_preset' of type ["null", "string"] may be incompatible
long_read_assembly.cwl:114:7:   with sink 'alignMode' of type "string"
long_read_assembly.cwl:34:5:  Source 'host_unmaped_reads' of type ["null", "string"] may be
                              incompatible
long_read_assembly.cwl:115:7:   with sink 'outReadsName' of type "string"
long_read_assembly.cwl:58:5:  Source 'predict_proteins_gbk' of type ["null", "string"] may be
                              incompatible
long_read_assembly.cwl:171:7:   with sink 'outGbkName' of type "string"
long_read_assembly.cwl:54:5:  Source 'predict_proteins' of type ["null", "string"] may be
                              incompatible
long_read_assembly.cwl:170:7:   with sink 'outProtName' of type "string"
long_read_assembly.cwl:46:5:  Source 'medaka_model' of type ["null", "string"] may be incompatible
long_read_assembly.cwl:152:7:   with sink 'medakaModel' of type "string"
long_read_assembly.cwl:66:5:  Source 'diamond_out' of type ["null", "string"] may be incompatible
long_read_assembly.cwl:180:7:   with sink 'outName' of type "string"
long_read_assembly.cwl:42:5:  Source 'polish_assembly_racon' of type ["null", "string"] may be
                              incompatible
long_read_assembly.cwl:143:7:   with sink 'outName' of type "string"
long_read_assembly.cwl:70:5:  Source 'ideel_out' of type ["null", "string"] may be incompatible
long_read_assembly.cwl:190:7:   with sink 'outFigName' of type "string"
long_read_assembly.cwl:38:5:  Source 'polish_paf' of type ["null", "string"] may be incompatible
long_read_assembly.cwl:133:7:   with sink 'outPAFname' of type "string"
long_read_assembly.cwl:30:5:  Source 'align_preset' of type ["null", "string"] may be incompatible
long_read_assembly.cwl:159:7:   with sink 'alignMode' of type "string"
long_read_assembly.cwl:50:5:  Source 'host_unmaped_contigs' of type ["null", "string"] may be
                              incompatible
long_read_assembly.cwl:160:7:   with sink 'outReadsName' of type "string"
long_read_assembly.cwl:18:5:  Source 'min_read_size' of type ["null", "int"] may be incompatible
long_read_assembly.cwl:103:7:   with sink 'minLength' of type "int"
long_read_assembly.cwl:22:5:  Source 'reads_filter_bysize_name' of type ["null", "string"] may be
                              incompatible
long_read_assembly.cwl:104:7:   with sink 'name' of type "string"
ERROR I'm sorry, I couldn't load this CWL file, try again with --debug for more information.
The error was: Object of type date is not JSON serializable
$ cwltool --debug --print-dot long_read_assembly.cwl
INFO /usr/local/bin/cwltool 3.0.20200807132242
INFO Resolved 'long_read_assembly.cwl' to 'file:///long_read_assembly.cwl'
WARNING Workflow checker warning:
long_read_assembly.cwl:70:5:  Source 'ideel_out' of type ["null", "string"] may be incompatible
long_read_assembly.cwl:190:7:   with sink 'outFigName' of type "string"
long_read_assembly.cwl:30:5:  Source 'align_preset' of type ["null", "string"] may be incompatible
long_read_assembly.cwl:159:7:   with sink 'alignMode' of type "string"
long_read_assembly.cwl:50:5:  Source 'host_unmaped_contigs' of type ["null", "string"] may be
                              incompatible
long_read_assembly.cwl:160:7:   with sink 'outReadsName' of type "string"
long_read_assembly.cwl:66:5:  Source 'diamond_out' of type ["null", "string"] may be incompatible
long_read_assembly.cwl:180:7:   with sink 'outName' of type "string"
long_read_assembly.cwl:30:5:  Source 'align_preset' of type ["null", "string"] may be incompatible
long_read_assembly.cwl:114:7:   with sink 'alignMode' of type "string"
long_read_assembly.cwl:34:5:  Source 'host_unmaped_reads' of type ["null", "string"] may be
                              incompatible
long_read_assembly.cwl:115:7:   with sink 'outReadsName' of type "string"
long_read_assembly.cwl:58:5:  Source 'predict_proteins_gbk' of type ["null", "string"] may be
                              incompatible
long_read_assembly.cwl:171:7:   with sink 'outGbkName' of type "string"
long_read_assembly.cwl:54:5:  Source 'predict_proteins' of type ["null", "string"] may be
                              incompatible
long_read_assembly.cwl:170:7:   with sink 'outProtName' of type "string"
long_read_assembly.cwl:46:5:  Source 'medaka_model' of type ["null", "string"] may be incompatible
long_read_assembly.cwl:152:7:   with sink 'medakaModel' of type "string"
long_read_assembly.cwl:18:5:  Source 'min_read_size' of type ["null", "int"] may be incompatible
long_read_assembly.cwl:103:7:   with sink 'minLength' of type "int"
long_read_assembly.cwl:22:5:  Source 'reads_filter_bysize_name' of type ["null", "string"] may be
                              incompatible
long_read_assembly.cwl:104:7:   with sink 'name' of type "string"
long_read_assembly.cwl:38:5:  Source 'polish_paf' of type ["null", "string"] may be incompatible
long_read_assembly.cwl:133:7:   with sink 'outPAFname' of type "string"
long_read_assembly.cwl:42:5:  Source 'polish_assembly_racon' of type ["null", "string"] may be
                              incompatible
long_read_assembly.cwl:143:7:   with sink 'outName' of type "string"
ERROR I'm sorry, I couldn't load this CWL file.
The error was:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cwltool/main.py", line 985, in main
    printdot(tool, loadingContext.loader.ctx, stdout)
  File "/usr/local/lib/python3.8/dist-packages/cwltool/cwlrdf.py", line 198, in printdot
    cwl_viewer = CWLViewer(printrdf(wf, ctx, 'n3'))  # type: CWLViewer
  File "/usr/local/lib/python3.8/dist-packages/cwltool/cwlrdf.py", line 26, in printrdf
    rdf = gather(wflow, ctx).serialize(format=style, encoding="utf-8")
  File "/usr/local/lib/python3.8/dist-packages/cwltool/cwlrdf.py", line 20, in gather
    tool.visit(visitor)
  File "/usr/local/lib/python3.8/dist-packages/cwltool/workflow.py", line 182, in visit
    op(self.tool)
  File "/usr/local/lib/python3.8/dist-packages/cwltool/cwlrdf.py", line 18, in visitor
    makerdf(t["id"], t, ctx, graph=g)
  File "/usr/local/lib/python3.8/dist-packages/schema_salad/jsonld_context.py", line 249, in makerdf
    g.parse(data=json_dumps(wf), format="json-ld", publicID=str(workflow))
  File "/usr/local/lib/python3.8/dist-packages/schema_salad/utils.py", line 111, in json_dumps
    return json.dumps(convert_to_dict(obj), **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
```

the tested file is this https://github.com/EBI-Metagenomics/mgnify-lr/blob/master/cwl/workflows/long_read_assembly.yml

thanks

**Comment by alexiswl** [comment]
I have reproduce this error:

Note: 
> the tested file is this https://github.com/EBI-Metagenomics/mgnify-lr/blob/master/cwl/workflows/long_read_assembly.yml
Should be:
> the tested file is this https://github.com/EBI-Metagenomics/mgnify-lr/blob/master/cwl/workflows/long_read_assembly.cwl

`--print-dot` seems to work reliably on a packed cwl file, but I cannot pack this cwl file to begin that process.  

```
cwltool --pack long_read_assembly.cwl > long_read_assembly.packed.cwl.json 2>pack.log
```

## pack.log

<details>

<summary>Click to expand</summary>

```bash
INFO /home/alexiswl/anaconda3/bin/cwltool 3.0.20200709181526
INFO Resolved 'long_read_assembly.cwl' to 'file:///tmp/tmp.lB99Btc5fw/mgnify-lr/cwl/workflows/long_read_assembly.cwl'
long_read_assembly.cwl:61:3: object id `long_read_assembly.cwl#final_assembly` previously defined
long_read_assembly.cwl:65:3: object id `long_read_assembly.cwl#final_assembly_stats` previously defined
long_read_assembly.cwl:69:3: object id `long_read_assembly.cwl#predict_proteins` previously defined
long_read_assembly.cwl:61:3: object id `long_read_assembly.cwl#final_assembly` previously defined
long_read_assembly.cwl:65:3: object id `long_read_assembly.cwl#final_assembly_stats` previously defined
long_read_assembly.cwl:69:3: object id `long_read_assembly.cwl#predict_proteins` previously defined
../tools/assembly_stats/assemblyStatsFastq.cwl:29:3: object id `../tools/assembly_stats/assemblyStatsFastq.cwl#outReport` previously defined
../tools/filterContigs/filterContigs.cwl:31:3: object id `../tools/filterContigs/filterContigs.cwl#outFasta` previously defined
../tools/assembly_stats/assemblyStatsFasta.cwl:29:3: object id `../tools/assembly_stats/assemblyStatsFasta.cwl#outReport` previously defined
ERROR I'm sorry, I couldn't load this CWL file, try again with --debug for more information.
The error was: Object of type date is not JSON serializable
```

</details>

I would recommend using different ids for your inputs and outputs for each step - In this case, for example, `final_assembly` is the input into your `long_read_assembly.cwl` workflow but also an output of the workflow.  

Kind regards,
Alexis.
