### ISSUE TITLE
Issues running the Docker examples on Windows

### ISSUE THREAD

**Issue by kinow** [common-workflow-language/cwltool#1401]
## Expected Behavior

`cwltool` should be able to run on Windows, and also run workflows with or without Docker.

## Actual Behavior

I have installed WSL2 on Windows 10 pro. Also installed Python with `sudo apt install python3 python3-dev python3-pip`.

```bash
kinow@DESKTOP-MEGD7DE:~/cwltool$ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

I am following the instructions from the README file for Windows. But before installing Docker, I want to get an error message saying that Docker was not found. So that after I install it, I know that the installation has fixed the issue.

The message appears to be complaining about the workflow schema?

## Workflow Code

https://github.com/common-workflow-language/common-workflow-language/blob/main/v1.0/v1.0/empty.json

## Full Traceback
```pytb
kinow@DESKTOP-MEGD7DE:~/cwltool$ cwltool --debug --user-space-docker-cmd=udocker https://raw.githubusercontent.com/common-workflow-language/common-workflow-language/mai
n/v1.0/v1.0/test-cwl-out2.cwl https://github.com/common-workflow-language/common-workflow-language/blob/main/v1.0/v1.0/empty.json
INFO /home/kinow/.local/bin/cwltool 3.0.20210129151325
ERROR Tool definition failed validation:
https://github.com/common-workflow-language/common-workflow-language/blob/main/v1.0/v1.0/empty.json:89:65: mapping values are
                                                                                                           not allowed here
Traceback (most recent call last):
  File "/home/kinow/.local/lib/python3.7/site-packages/schema_salad/ref_resolver.py", line 991, in fetch
    result = cast(CommentedMap, next(attachments))
  File "/home/kinow/.local/lib/python3.7/site-packages/ruamel/yaml/main.py", line 973, in load_all
    while loader._constructor.check_data():
  File "/home/kinow/.local/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 100, in check_data
    return self.composer.check_node()
  File "/home/kinow/.local/lib/python3.7/site-packages/ruamel/yaml/composer.py", line 58, in check_node
    if self.parser.check_event(StreamStartEvent):
  File "/home/kinow/.local/lib/python3.7/site-packages/ruamel/yaml/parser.py", line 140, in check_event
    self.current_event = self.state()
  File "/home/kinow/.local/lib/python3.7/site-packages/ruamel/yaml/parser.py", line 176, in parse_stream_start
    token.move_comment(self.scanner.peek_token())
  File "/home/kinow/.local/lib/python3.7/site-packages/ruamel/yaml/scanner.py", line 1778, in peek_token
    self._gather_comments()
  File "/home/kinow/.local/lib/python3.7/site-packages/ruamel/yaml/scanner.py", line 1806, in _gather_comments
    self.fetch_more_tokens()
  File "/home/kinow/.local/lib/python3.7/site-packages/ruamel/yaml/scanner.py", line 283, in fetch_more_tokens
    return self.fetch_value()
  File "/home/kinow/.local/lib/python3.7/site-packages/ruamel/yaml/scanner.py", line 656, in fetch_value
    self.reader.get_mark(),
ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
  in "https://github.com/common-workflow-language/common-workflow-language/blob/main/v1.0/v1.0/empty.json", line 89, column 65

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kinow/.local/lib/python3.7/site-packages/cwltool/main.py", line 941, in main
    tool_file_uri,
  File "/home/kinow/.local/lib/python3.7/site-packages/cwltool/main.py", line 337, in load_job_order
    job_order_object, _ = loader.resolve_ref(job_order_file, checklinks=False)
  File "/home/kinow/.local/lib/python3.7/site-packages/schema_salad/ref_resolver.py", line 532, in resolve_ref
    doc = self.fetch(doc_url, inject_ids=(not mixin))
  File "/home/kinow/.local/lib/python3.7/site-packages/schema_salad/ref_resolver.py", line 1000, in fetch
    raise to_validation_exception(e) from e
schema_salad.exceptions.ValidationException: https://github.com/common-workflow-language/common-workflow-language/blob/main/v1.0/v1.0/empty.json:89:65: mapping values are
                                                                                                           not allowed here
```

## Your Environment
* cwltool version: 
Check using ``cwltool --version``

```
kinow@DESKTOP-MEGD7DE:~/cwltool$ cwltool --version
/home/kinow/.local/bin/cwltool 3.0.20210129151325
```

Thank you
Bruno

**Comment by mr-c** [comment]
Hey Bruno.

https://github.com/common-workflow-language/common-workflow-language/blob/main/v1.0/v1.0/empty.json is a webpage, https://github.com/common-workflow-language/common-workflow-language/raw/main/v1.0/v1.0/empty.json is the actual file

**Comment by mr-c** [comment]
So this was our error in the README, thanks for finding this!

**Comment by mr-c** [comment]
Should be fixed in https://github.com/common-workflow-language/cwltool/commit/72733d9f97d791f17e8b20ee6601cbcdf69be14c

**Comment by kinow** [comment]
> So this was our error in the README, thanks for finding this!

Ah! That explains it! I thought I had copied the wrong URL. Thanks! Will continue with the windows testing today.
