### ISSUE TITLE
Creating input yaml - issue with ruamel comments.py

### ISSUE THREAD

**Issue by BJWiley233** [common-workflow-language/cwltool#1404]
Hi,
I am using cwltool version 3.0.20201203173111 that came with `pip install cwl-runner`.  This might be issue with ruamel or with my workflow but here is run command and trace:

`cwltool --make-template --debug tumor_only_exome.cwl > hiv_input.yml`

traceback:
```
Traceback (most recent call last):
  File "/home/coyote/anaconda3/envs/cwl/lib/python3.6/site-packages/cwltool/main.py", line 991, in main
    make_template(tool)
  File "/home/coyote/anaconda3/envs/cwl/lib/python3.6/site-packages/cwltool/main.py", line 744, in make_template
    generate_input_template(tool),
  File "/home/coyote/anaconda3/envs/cwl/lib/python3.6/site-packages/cwltool/main.py", line 301, in generate_input_template
    template.insert(0, name, value, comment)
  File "/home/coyote/anaconda3/envs/cwl/lib/python3.6/site-packages/ruamel/yaml/comments.py", line 722, in insert
    self.yaml_add_eol_comment(comment, key=key)
  File "/home/coyote/anaconda3/envs/cwl/lib/python3.6/site-packages/ruamel/yaml/comments.py", line 295, in yaml_add_eol_comment
    if comment[0] != '#':
IndexError: string index out of range
```

**Comment by mr-c** [comment]
Thank you @BJWiley233 for your report. Can you link to your `tumor_only_exome.cwl` file or upload it here?
