### ISSUE TITLE
CWLTool --validate error should highlight offending tool on error.

### ISSUE THREAD

**Issue by alexiswl** [common-workflow-language/cwltool#1438]
## Expected Behavior
Tell us what should happen

When a workflow fails validation because of a tool not being configured correctly, the validation error should highlight which tool has failed.

## Actual Behavior
Tell us what happens instead

## Workflow Code
I have taken from https://github.com/common-workflow-language/cwl-v1.1/blob/main/tests/count-lines1-wf.cwl

```yaml
#!/usr/bin/env cwl-runner
class: Workflow
cwlVersion: v1.1

inputs:
  file1:
    type: File

outputs:
  count_output:
    type: int
    outputSource: step2/output

steps:
  step1:
    run: wc-tool.cwl
    in:
      file1: file1
    out: [output]

  step2:
    run: parseInt-tool.cwl
    in:
      file1: step1/output
    out: [output]
```

In the tool `wc-tool` I have created an invalid 'hints' section:

```yaml
#!/usr/bin/env cwl-runner

class: CommandLineTool
cwlVersion: v1.1

hints:

inputs:
  file1: File

outputs:
  output:
    type: File
    outputBinding: { glob: output }

baseCommand: [wc, -l]

stdin: $(inputs.file1.path)
stdout: output
```

## Full Traceback
```pytb
INFO /home/alexiswl/anaconda3/envs/cwl/bin/cwltool 3.0.20210319143721
INFO Resolved 'count-lines1-wf.cwl' to 'file:///c/Users/awluc/OneDrive/GitHub/UMCCR-ILLUMINA/cwl-iap/share/validate/count-lines1-wf.cwl'
ERROR I'm sorry, I couldn't load this CWL file.
The error was:
Traceback (most recent call last):
  File "/home/alexiswl/anaconda3/envs/cwl/lib/python3.8/site-packages/cwltool/main.py", line 1035, in main
    tool = make_tool(uri, loadingContext)
  File "/home/alexiswl/anaconda3/envs/cwl/lib/python3.8/site-packages/cwltool/load_tool.py", line 460, in make_tool
    tool = loadingContext.construct_tool_object(processobj, loadingContext)
  File "/home/alexiswl/anaconda3/envs/cwl/lib/python3.8/site-packages/cwltool/workflow.py", line 51, in default_make_tool
    return Workflow(toolpath_object, loadingContext)
  File "/home/alexiswl/anaconda3/envs/cwl/lib/python3.8/site-packages/cwltool/workflow.py", line 105, in __init__
    self.make_workflow_step(
  File "/home/alexiswl/anaconda3/envs/cwl/lib/python3.8/site-packages/cwltool/workflow.py", line 150, in make_workflow_step
    return WorkflowStep(toolpath_object, pos, loadingContext, parentworkflowProv)
  File "/home/alexiswl/anaconda3/envs/cwl/lib/python3.8/site-packages/cwltool/workflow.py", line 233, in __init__
    self.embedded_tool = load_tool(toolpath_object["run"], loadingContext)
  File "/home/alexiswl/anaconda3/envs/cwl/lib/python3.8/site-packages/cwltool/load_tool.py", line 482, in load_tool
    return make_tool(uri, loadingContext)
  File "/home/alexiswl/anaconda3/envs/cwl/lib/python3.8/site-packages/cwltool/load_tool.py", line 460, in make_tool
    tool = loadingContext.construct_tool_object(processobj, loadingContext)
  File "/home/alexiswl/anaconda3/envs/cwl/lib/python3.8/site-packages/cwltool/workflow.py", line 47, in default_make_tool
    return command_line_tool.CommandLineTool(toolpath_object, loadingContext)
  File "/home/alexiswl/anaconda3/envs/cwl/lib/python3.8/site-packages/cwltool/command_line_tool.py", line 381, in __init__
    super().__init__(toolpath_object, loadingContext)
  File "/home/alexiswl/anaconda3/envs/cwl/lib/python3.8/site-packages/cwltool/process.py", line 605, in __init__
    self.hints.extend(self.tool.get("hints", []))
TypeError: 'NoneType' object is not iterable
```

## Your Environment
* cwltool version: 3.0.20210319143721
Check using ``cwltool --version``

**Comment by mr-c** [comment]
Hey @alexiswl , thanks for this nice report. I've put together a fix at https://github.com/common-workflow-language/cwltool/pull/1439
