### ISSUE TITLE
Singularity volume mapping fails

### ISSUE THREAD

**Issue by rupertnash** [common-workflow-language/cwltool#1441]
## Expected Behavior
CWL v1.2 conformance test 338 (iwdr_dir_literal_real_file) should work on both Docker and Singularity

## Actual Behavior
Fails on singularity with:
```
Test 338 failed: /home/runner/work/cwltool/cwltool/cwl-v1.2-main/cwltool_with_cov3 --parallel --singularity --outdir=/tmp/tmp_jvxdboq --quiet tests/iwd/iwdr_dir_literal_real_file.cwl tests/loadContents/input.yml
883
Test directory literal containing a real file
884
Returned non-zero
885
INFO:    Converting OCI blobs to SIF format
886
INFO:    Starting build...
887
Getting image source signatures
888
Copying blob sha256:79d3b412d7261ce15487ba01f99e99609855e5ceb3578b4513a2a96d6184352e
889
Copying config sha256:cc397186c1b59edd2076c8986f259e8ef49c2108afe9691817a52cc8cc3fa000
890
Writing manifest to image destination
891
Storing signatures
892
2021/04/23 18:01:42  info unpack layer: sha256:79d3b412d7261ce15487ba01f99e99609855e5ceb3578b4513a2a96d6184352e
893
INFO:    Creating SIF file...
894
ERROR Got workflow error: [Errno 2] No such file or directory: '_:f9e78fa6-0296-4398-9dde-fb7b2580145a'
895
Traceback (most recent call last):
896
  File "/home/runner/work/cwltool/cwltool/cwltool/executors.py", line 332, in _runner
897
    job.run(runtime_context, TMPDIR_LOCK)
898
  File "/home/runner/work/cwltool/cwltool/cwltool/job.py", line 827, in run
899
    (runtime, cidfile) = self.create_runtime(env, runtimeContext)
900
  File "/home/runner/work/cwltool/cwltool/cwltool/singularity.py", line 427, in create_runtime
901
    self.add_volumes(
902
  File "/home/runner/work/cwltool/cwltool/cwltool/job.py", line 700, in add_volumes
903
    self.add_file_or_directory_volume(runtime, vol, host_outdir_tgt)
904
  File "/home/runner/work/cwltool/cwltool/cwltool/singularity.py", line 296, in add_file_or_directory_volume
905
    shutil.copytree(volume.resolved, host_outdir_tgt)
906
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/shutil.py", line 555, in copytree
907
    with os.scandir(src) as itr:
908
FileNotFoundError: [Errno 2] No such file or directory: '_:f9e78fa6-0296-4398-9dde-fb7b2580145a'
909
ERROR Workflow error, try again with --debug for more information:
910
[Errno 2] No such file or directory: '_:f9e78fa6-0296-4398-9dde-fb7b2580145a'
911
```

There's clearly a bug in `cwl.singularity` around volume mapping. After a quick look, it appears to be related to `cwltool.singularity.SingularityCommandLineJob.add_file_or_directory_volume` which says in a comment 
```
            # workaround for lack of overlapping mounts in Singularity
            # revert to daa923d5b0be3819b6ed0e6440e7193e65141052
            # once https://github.com/sylabs/singularity/issues/1607
            # is fixed
```
(Introduced in 087594e8e22310830bc5b95a5fa01d869f6a1339)

That singularity issue appears to be fixed in more recent versions (3.4 or 3.5 according to S. contributors)
https://github.com/hpcng/singularity/issues/1607

**Comment by rupertnash** [comment]
Note that when this is resolved, we can remove the exclusion from `conformance-test.sh`.
