### ISSUE TITLE
--printrdf doesn't work for v1.0 documents

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#154]
as the `steps` field of `Workflow` is missing a `@id` https://github.com/common-workflow-language/cwltool/blob/master/cwltool/cwlrdf.py#L13

**Comment by mr-c** [comment]
```
(env) michael@dan:~/cwl-upgrader$ cwltool --print-rdf GATK-IndelRealigner.v1.0.cwl 
/home/michael/cwl-upgrader/env/bin/cwltool 1.0.20160809155826
	I'm sorry, I couldn't load this CWL file, try again with --debug for more information.
The error was: '@id'
(env) michael@dan:~/cwl-upgrader$ cwltool --debug --print-rdf GATK-IndelRealigner.v1.0.cwl 
/home/michael/cwl-upgrader/env/bin/cwltool 1.0.20160809155826
I'm sorry, I couldn't load this CWL file.  The error was:
Traceback (most recent call last):
  File "/home/michael/cwl-upgrader/env/local/lib/python2.7/site-packages/cwltool/main.py", line 651, in main
    printrdf(uri, processobj, document_loader.ctx, args.rdf_serializer, stdout)
  File "/home/michael/cwl-upgrader/env/local/lib/python2.7/site-packages/cwltool/cwlrdf.py", line 39, in printrdf
    stdout.write(makerdf(workflow, wf, ctx).serialize(format=sr))
  File "/home/michael/cwl-upgrader/env/local/lib/python2.7/site-packages/cwltool/cwlrdf.py", line 13, in makerdf
    url = v["@id"]
KeyError: '@id'
```

**Comment by mr-c** [comment]
Same result with https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/examples/1st-tool.cwl

**Comment by tetron** [comment]
Might need to bump to latest schema-salad package

**Comment by tetron** [comment]
Fixed in PR https://github.com/common-workflow-language/schema_salad/pull/48

Will need to publish new schema-salad and bump cwltool dependency.

**Comment by tetron** [comment]
See https://github.com/common-workflow-language/cwltool/pull/159

**Comment by mr-c** [comment]
Thanks!
