### ISSUE TITLE
better error message when step name is missing

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#1635]
``` cwl
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: Workflow
label: geoweaver workflow 

inputs:
  code_folder: 
    type: File
 
outputs: []

steps:
  run: HelloWorld.cwl
  in:
    folder: code_folder
  out: []  
```

```
$ cwltool --debug 568.cwl
INFO /home/michael/cwltool_clean/env/bin/cwltool 3.1.20220303191415
INFO Resolved '568.cwl' to 'file:///home/michael/cwltool_clean/568.cwl'
ERROR Tool definition failed validation:
mapSubject 'out' value 'None' is not a dict and does not have a mapPredicate.
Traceback (most recent call last):
  File "/home/michael/cwltool_clean/cwltool/main.py", line 1117, in main
    loadingContext, uri = resolve_and_validate_document(
  File "/home/michael/cwltool_clean/cwltool/load_tool.py", line 384, in resolve_and_validate_document
    document_loader.resolve_all(workflowobj, fileuri)
  File "schema_salad/ref_resolver.py", line 892, in resolve_all
  File "schema_salad/ref_resolver.py", line 595, in _resolve_idmap
schema_salad.exceptions.ValidationException: mapSubject 'out' value 'None' is not a dict and does not have a mapPredicate.
```

Missing the line number due to lack of use of `SourceLine` in https://github.com/common-workflow-language/schema_salad/blob/7d349529753243770ffb5395abdfd6558a735ed9/schema_salad/ref_resolver.py#L595

**Comment by mr-c** [comment]
Fixed in https://github.com/common-workflow-language/schema_salad/pull/562
