### ISSUE TITLE
working-fine wf breaks when running with the `--provenance` argument

### ISSUE THREAD

**Issue by hariszaf** [common-workflow-language/cwltool#1738]
## Expected Behavior

A working-fine workflow to perform smoothly with the `--provenance ` argument. 

## Actual Behavior

When the `--provenance` argument is used, the workflow breaks. 

## Workflow Code
This is our [CWL wf](https://github.com/emo-bon/pipeline-v5/blob/develop/workflows/gos_wf.cwl). 

This is how it runs fine: 
```
cwl-runner ${SINGULARITY} --outdir ${OUT_DIR} --debug ${CWL} ${RENAMED_YML} 
```
But in this case: 
```
cwl-runner ${SINGULARITY} --outdir ${OUT_DIR} --provenance ro --debug ${CWL} ${RENAMED_YML} 
```
it breaks. 

## Full Traceback
```pytb
[1;30mERROR[0m [31mGot workflow error[0m
Traceback (most recent call last):
  File "/mnt/big/miniconda3/envs/EOSC-CWL/lib/python3.7/site-packages/cwltool/executors.py", line 227, in run_jobs
    for job in jobiter:
  File "/mnt/big/miniconda3/envs/EOSC-CWL/lib/python3.7/site-packages/cwltool/workflow.py", line 165, in job
    runtimeContext.research_obj.create_job(builder.job)
  File "/mnt/big/miniconda3/envs/EOSC-CWL/lib/python3.7/site-packages/cwltool/provenance.py", line 901, in create_job
    self._relativise_files(copied)
  File "/mnt/big/miniconda3/envs/EOSC-CWL/lib/python3.7/site-packages/cwltool/provenance.py", line 974, in _relativise_files
    self._relativise_files(cast(CWLOutputType, val))
  File "/mnt/big/miniconda3/envs/EOSC-CWL/lib/python3.7/site-packages/cwltool/provenance.py", line 942, in _relativise_files
    alg, checksum = raw_checksum.split("$")
ValueError: not enough values to unpack (expected 2, got 1)
[1;30mERROR[0m [31mWorkflow error:
not enough values to unpack (expected 2, got 1)[0m
Traceback (most recent call last):
  File "/mnt/big/miniconda3/envs/EOSC-CWL/lib/python3.7/site-packages/cwltool/executors.py", line 227, in run_jobs
    for job in jobiter:
  File "/mnt/big/miniconda3/envs/EOSC-CWL/lib/python3.7/site-packages/cwltool/workflow.py", line 165, in job
    runtimeContext.research_obj.create_job(builder.job)
  File "/mnt/big/miniconda3/envs/EOSC-CWL/lib/python3.7/site-packages/cwltool/provenance.py", line 901, in create_job
    self._relativise_files(copied)
  File "/mnt/big/miniconda3/envs/EOSC-CWL/lib/python3.7/site-packages/cwltool/provenance.py", line 974, in _relativise_files
    self._relativise_files(cast(CWLOutputType, val))
  File "/mnt/big/miniconda3/envs/EOSC-CWL/lib/python3.7/site-packages/cwltool/provenance.py", line 942, in _relativise_files
    alg, checksum = raw_checksum.split("$")
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/big/miniconda3/envs/EOSC-CWL/lib/python3.7/site-packages/cwltool/main.py", line 1303, in main
    tool, initialized_job_order_object, runtimeContext, logger=_logger
  File "/mnt/big/miniconda3/envs/EOSC-CWL/lib/python3.7/site-packages/cwltool/executors.py", line 60, in __call__
    return self.execute(process, job_order_object, runtime_context, logger)
  File "/mnt/big/miniconda3/envs/EOSC-CWL/lib/python3.7/site-packages/cwltool/executors.py", line 143, in execute
    self.run_jobs(process, job_order_object, logger, runtime_context)
  File "/mnt/big/miniconda3/envs/EOSC-CWL/lib/python3.7/site-packages/cwltool/executors.py", line 261, in run_jobs
    raise WorkflowException(str(err)) from err
cwltool.errors.WorkflowException: not enough values to unpack (expected 2, got 1)
```

## Your Environment
* cwltool version: cwl-runner 3.1.20211107152837

**Comment by mr-c** [comment]
Thank you @hariszaf for your report

>  3.1.20211107152837

Can you try a newer release of cwltool?

https://anaconda.org/conda-forge/cwltool has v3.1.20220913185150 (as does PyPI: https://pypi.org/project/cwltool/3.1.20220913185150/  )

**Comment by hariszaf** [comment]
Thanks @mr-c for your reply! I will ask sys-admin to do so and let you know asap!

**Comment by hariszaf** [comment]
Hi again @mr-c! 
So, I was finally able to run the wf with the cwltool release you mentioned and the error remains the same.
When the `--provenance` is not there, the wf comes up with a `success` status. 
Any ideas this error comes from my cwl script and I could do anything to fix it or if it is cwltool-oriented onlye?

**Comment by steninidak** [comment]
Hi everyone, 
I am facing the same issue when I am running my workflow with `--provenance` argument. I have tested both the latest (v3.1.20220913185150) version of cwltool and previous versions and the issue remains the same. 

Any ideas on what causes that issue?

**Comment by hariszaf** [comment]
In my case, it was a schema issue. 
It seems it could not load the `.rdf` and that was leading to this behavior. 
Thanks a lot in any case.

**Comment by hariszaf** [comment]
It turned out that it was not the `secondaryFiles` the issue; that was just a bad coincidence. 
The issue was that the `checksum` was provided without the `sha1$` prefix. 
Apologies for the trouble.
