### ISSUE TITLE
Missing cwl-utils dependency when installing from conda (but not pip)

### ISSUE THREAD

**Issue by jfennick** [common-workflow-language/cwltool#1743]
This affects the latest 3.1.20220913185150 release.

In a brand new conda environment, `conda install cwltool` installs, but then `cwltool --version`gives the attached stack trace. If you additionally perform `conda install cwl-utils`, then `cwltool --version` succeeds.

Instead, if you `pip install cwltool` then `cwltool --version` correctly yields 3.1.20220913185150

## Full Traceback
```pytb
Traceback (most recent call last):
  File "/Users/jakefennick/opt/anaconda3/envs/cwl_test/bin/cwltool", line 7, in <module>
    from cwltool.main import run
  File "cwltool/main.py", line 47, in <module>
  File "cwltool/workflow.py", line 22, in <module>
  File "cwltool/command_line_tool.py", line 42, in <module>
  File "cwltool/builder.py", line 17, in <module>
ModuleNotFoundError: No module named 'cwl_utils'
```

## Your Environment
* cwltool version: 
Check using ``cwltool --version``
3.1.20220913185150

**Comment by mr-c** [comment]
Thank you @jfennick for the report; you can directly take this up with the conda-forge team for cwltool over at https://github.com/conda-forge/cwltool-feedstock/
