### ISSUE TITLE
Incompatibility between cwltools and singularity (also trying with udocker)

### ISSUE THREAD

**Issue by bioinfo-fiend** [common-workflow-language/cwltool#1777]
## Expected Behavior
Run cwltool with either singularity or udocker on an hpc environment

## Actual Behavior
I get an error when trying to run cwltool via udocker or singularity

## Workflow Code
```
cwltool --singularity https://raw.githubusercontent.com/common-workflow-language/common-workflow-language/main/v1.0/v1.0/v1.0/cat3-tool-mediumcut.cwl https://github.com/common-workflow-language/common-workflow-language/blob/main/v1.0/v1.0/cat-job.json
```

## Full Traceback
```
INFO /hpc/local/CentOS7/software/miniconda-4.12.0/envs/virtus2_env/bin/cwltool 3.1.20210922203925
While fetching https://github.com/common-workflow-language/common-workflow-language/blob/main/v1.0/v1.0/cat-job.json, got content-type of 'text/html'. Expected one of ['text/plain', 'application/json', 'text/vnd.yaml', 'text/yaml', 'text/x-yaml', 'application/x-yaml'].
ERROR Tool definition failed validation:
https://github.com/common-workflow-language/common-workflow-language/blob/main/v1.0/v1.0/cat-job.json:28:66: mapping values are
                                                                                                             not allowed here
Traceback (most recent call last):
  File "/hpc/local/CentOS7/software/miniconda-4.12.0/envs/virtus2_env/lib/python3.6/site-packages/schema_salad/ref_resolver.py", line 1004, in fetch
    result = cast(Union[CommentedSeq, CommentedMap], next(attachments))
  File "/hpc/local/CentOS7/software/miniconda-4.12.0/envs/virtus2_env/lib/python3.6/site-packages/ruamel/yaml/main.py", line 460, in load_all
    while constructor.check_data():
  File "/hpc/local/CentOS7/software/miniconda-4.12.0/envs/virtus2_env/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 109, in check_data
    return self.composer.check_node()
  File "/hpc/local/CentOS7/software/miniconda-4.12.0/envs/virtus2_env/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 56, in check_node
    if self.parser.check_event(StreamStartEvent):
  File "/hpc/local/CentOS7/software/miniconda-4.12.0/envs/virtus2_env/lib/python3.6/site-packages/ruamel/yaml/parser.py", line 146, in check_event
    self.current_event = self.state()
  File "/hpc/local/CentOS7/software/miniconda-4.12.0/envs/virtus2_env/lib/python3.6/site-packages/ruamel/yaml/parser.py", line 185, in parse_stream_start
    self.move_token_comment(token)
  File "/hpc/local/CentOS7/software/miniconda-4.12.0/envs/virtus2_env/lib/python3.6/site-packages/ruamel/yaml/parser.py", line 836, in move_token_comment
    token.move_old_comment(self.scanner.peek_token() if nt is None else nt, empty=empty)
  File "/hpc/local/CentOS7/software/miniconda-4.12.0/envs/virtus2_env/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 1810, in peek_token
    self._gather_comments()
  File "/hpc/local/CentOS7/software/miniconda-4.12.0/envs/virtus2_env/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 1838, in _gather_comments
    self.fetch_more_tokens()
  File "/hpc/local/CentOS7/software/miniconda-4.12.0/envs/virtus2_env/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 288, in fetch_more_tokens
    return self.fetch_value()
  File "/hpc/local/CentOS7/software/miniconda-4.12.0/envs/virtus2_env/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 661, in fetch_value
    self.reader.get_mark(),
ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
  in "https://github.com/common-workflow-language/common-workflow-language/blob/main/v1.0/v1.0/cat-job.json", line 28, column 66

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/local/CentOS7/software/miniconda-4.12.0/envs/virtus2_env/lib/python3.6/site-packages/cwltool/main.py", line 1015, in main
    tool_file_uri,
  File "/hpc/local/CentOS7/software/miniconda-4.12.0/envs/virtus2_env/lib/python3.6/site-packages/cwltool/main.py", line 358, in load_job_order
    content_types=CWL_CONTENT_TYPES,
  File "/hpc/local/CentOS7/software/miniconda-4.12.0/envs/virtus2_env/lib/python3.6/site-packages/schema_salad/ref_resolver.py", line 519, in resolve_ref
    doc_url, inject_ids=(not mixin), content_types=content_types
  File "/hpc/local/CentOS7/software/miniconda-4.12.0/envs/virtus2_env/lib/python3.6/site-packages/schema_salad/ref_resolver.py", line 1013, in fetch
    raise to_validation_exception(e) from e
schema_salad.exceptions.ValidationException: https://github.com/common-workflow-language/common-workflow-language/blob/main/v1.0/v1.0/cat-job.json:28:66: mapping values are
                                                                                                             not allowed here
```

## Your Environment

- apptainer/singularity version 1.1.3-1.el7 (latest version of singularity)
- cwltool version 3.1.20210922203925
- python 3.5 to 3.9

**Comment by mr-c** [comment]
Hello @bioinfo-fiend and thanks for letting us know about your issue

https://raw.githubusercontent.com/common-workflow-language/common-workflow-language/main/v1.0/v1.0/v1.0/cat3-tool-mediumcut.cwl is not a valid URL, I get a 404 not found ; perhaps you meant https://github.com/common-workflow-language/common-workflow-language/raw/main/v1.0/v1.0/cat3-tool-mediumcut.cwl instead?

Likewise https://github.com/common-workflow-language/common-workflow-language/blob/main/v1.0/v1.0/cat-job.json
is a webpage, not the raw `cat-job.json` file; you should use https://github.com/common-workflow-language/common-workflow-language/raw/main/v1.0/v1.0/cat-job.json instead

Using the fixed URLs works for me, with docker, `--singularity`, and `--udocker`

```
cwltool https://github.com/common-workflow-language/common-workflow-language/raw/main/v1.0/v1.0/cat3-tool-mediumcut.cwl https://github.com/common-workflow-language/common-workflow-language/raw/main/v1.0/v1.0/cat-job.json
```

I also see that you are running an old version of `cwltool` from September, 2021. I strongly urge you to upgrade :-)

We even added a warning about using webpage URLs instead of raw URLs in recent versions
```
While fetching https://github.com/common-workflow-language/common-workflow-language/blob/main/v1.0/v1.0/cat-job.json, got content-type of 'text/html'. Expected one of ['text/plain', 'application/json', 'text/vnd.yaml', 'text/yaml', 'text/x-yaml', 'application/x-yaml', 'application/octet-stream'].
```

If you got this example from a website, please let me know so we can correct it.

**Comment by mr-c** [comment]
Pardon me, looks like the bad URLs came from our README; I'm fixing that now

**Comment by bioinfo-fiend** [comment]
Thanks for the quick response, I took the example from your github directly https://github.com/common-workflow-language/cwltool#using-udocker). Yes indeed using an updated version of cwltools gave a better response and I get successful output.

With --docker I still get an issue 


I've been trying to use a cwl script from a separate github and I get an issue, unfortunately.

**Comment by mr-c** [comment]
@bioinfo-fiend Thanks again for bringing this to our attention! I'll add a note about `nodejs` to the `udocker` section
