### ISSUE TITLE
TypeError: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by Double-O-ren** [common-workflow-language/cwltool#18]
```
Traceback (most recent call last):
  File "/Users/oren/anaconda/bin/cwltool", line 9, in <module>
    load_entry_point('cwltool==1.0.20151026181844', 'console_scripts', 'cwltool')()
  File "/Users/oren/anaconda/lib/python2.7/site-packages/cwltool/main.py", line 337, in main
    t = load_tool(args.workflow, args.update, args.strict, makeTool, args.debug, args.print_pre)
  File "/Users/oren/anaconda/lib/python2.7/site-packages/cwltool/main.py", line 266, in load_tool
    workflowobj = update.update(workflowobj, document_loader, fileuri)
  File "/Users/oren/anaconda/lib/python2.7/site-packages/cwltool/update.py", line 88, in update
    (doc, version) = nextupdate(doc, loader, baseuri)
  File "/Users/oren/anaconda/lib/python2.7/site-packages/cwltool/update.py", line 70, in draft2toDraft3
    return (_draft2toDraft3(doc, loader, baseuri), "https://w3id.org/cwl/cwl#draft-3.dev1")
  File "/Users/oren/anaconda/lib/python2.7/site-packages/cwltool/update.py", line 53, in _draft2toDraft3
    s["id"] = "step%i" % i
TypeError: 'str' object does not support item assignment
```

**Comment by mr-c** [comment]
Hello @Double-O-ren, thank you for filing this issue. Can you share what command you ran?

**Comment by mr-c** [comment]
Hello @Double-O-ren . We haven't heard from you in a while so I am going to close this issue. Feel free to re-open it later.
