### ISSUE TITLE
Resource requirements fail if user does division (float vs int)

### ISSUE THREAD

**Issue by kellrott** [common-workflow-language/cwltool#1816]
## Expected Behavior

Resource allocation should accept all numeric values, including floats.

## Actual Behavior

User code (from requirements stanza):
```
tmpdirMin: $((2 * inputs.input_bam.size) / 1048576)
```
produces a floating number.  Which causes the error:
```
ERROR [step sort_markdup_bam] Cannot make job: Got incorrect return type <class 'float'> from resource expression evaluation of $((2 * inputs.input_bam.size) / 1048576).
```
This is probably returned from the function at https://github.com/common-workflow-language/cwltool/blob/main/cwltool/process.py#L524

## Workflow Code

https://github.com/NCI-GDC/gdc-dnaseq-cwl/blob/master/tools/samtools_sort.cwl

## Full Traceback
```pytb
Traceback (most recent call last):
  File "/home/users/ellrott/miniconda3/envs/cwl/lib/python3.9/site-packages/cwltool/workflow_job.py", line 821, in job
    for newjob in step.iterable:
  File "/home/users/ellrott/miniconda3/envs/cwl/lib/python3.9/site-packages/cwltool/workflow_job.py", line 751, in try_make_job
    yield from jobs
  File "/home/users/ellrott/miniconda3/envs/cwl/lib/python3.9/site-packages/cwltool/workflow_job.py", line 77, in job
    yield from self.step.job(joborder, output_callback, runtimeContext)
  File "/home/users/ellrott/miniconda3/envs/cwl/lib/python3.9/site-packages/cwltool/workflow.py", line 458, in job
    yield from self.embedded_tool.job(
  File "/home/users/ellrott/miniconda3/envs/cwl/lib/python3.9/site-packages/cwltool/command_line_tool.py", line 959, in job
    builder = self._init_job(job_order, runtimeContext)
  File "/home/users/ellrott/miniconda3/envs/cwl/lib/python3.9/site-packages/cwltool/process.py", line 940, in _init_job
    builder.resources = self.evalResources(builder, runtime_context)
  File "/home/users/ellrott/miniconda3/envs/cwl/lib/python3.9/site-packages/cwltool/process.py", line 984, in evalResources
    eval_resource(builder, cast(Union[str, int, float], rsc[a + "Min"])),
  File "/home/users/ellrott/miniconda3/envs/cwl/lib/python3.9/site-packages/cwltool/process.py", line 523, in eval_resource
    raise WorkflowException(
cwltool.errors.WorkflowException: Got incorrect return type <class 'float'> from resource expression evaluation of $((2 * inputs.input_bam.size) / 1048576).
INFO [workflow conditional_markduplicates] completed permanentFail
```

## Your Environment
* cwltool version: 
Check using ``cwltool --version``

3.1.20230302145532

**Comment by mr-c** [comment]
Hello @kellrott ; `tmpdirMin` can be a float only starting with CWL v1.2

See https://www.commonwl.org/v1.2/CommandLineTool.html#ResourceRequirement vs https://www.commonwl.org/v1.1/CommandLineTool.html#ResourceRequirement

That being said, that error will still trigger in that circumstance.
