### ISSUE TITLE
cwltool exits with a 0 code even when an error occurred

### ISSUE THREAD

**Issue by fbacall** [common-workflow-language/cwltool#1855]
Hi, noticed this issue :point_up: when updating the version of cwltool used by WorkflowHub. The previous version we used would return a `1`.

## Expected Behavior
Should return non-zero so consuming services know the command failed.

## Actual Behavior
Returns `0`.

## Workflow Code
```
$ python3.9 -m cwltool --skip-schemas --quiet --enable-dev --non-strict --pack README.md
  ERROR Tool definition failed validation:
  README.md:23:34: mapping values are not allowed here
$ echo $?
  0
```

## Full Traceback
Ran the above with `--debug` instead of `--quiet`:
```
INFO /home/finn/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cwltool/__main__.py 3.1.20230601100705
INFO Resolved 'README.md' to 'file:///home/finn/workspace/seek/README.md'
ERROR Tool definition failed validation:
README.md:23:34: mapping values are not allowed here
Traceback (most recent call last):
  File "schema_salad/ref_resolver.py", line 993, in fetch
  File "/home/finn/.pyenv/versions/3.9.13/lib/python3.9/site-packages/ruamel/yaml/main.py", line 461, in load_all
    yield constructor.get_data()
  File "/home/finn/.pyenv/versions/3.9.13/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 115, in get_data
    return self.construct_document(self.composer.get_node())
  File "/home/finn/.pyenv/versions/3.9.13/lib/python3.9/site-packages/ruamel/yaml/composer.py", line 66, in get_node
    return self.compose_document()
  File "/home/finn/.pyenv/versions/3.9.13/lib/python3.9/site-packages/ruamel/yaml/composer.py", line 102, in compose_document
    self.parser.get_event()
  File "/home/finn/.pyenv/versions/3.9.13/lib/python3.9/site-packages/ruamel/yaml/parser.py", line 168, in get_event
    self.current_event = self.state()
  File "/home/finn/.pyenv/versions/3.9.13/lib/python3.9/site-packages/ruamel/yaml/parser.py", line 252, in parse_document_end
    token = self.scanner.peek_token()
  File "/home/finn/.pyenv/versions/3.9.13/lib/python3.9/site-packages/ruamel/yaml/scanner.py", line 1810, in peek_token
    self._gather_comments()
  File "/home/finn/.pyenv/versions/3.9.13/lib/python3.9/site-packages/ruamel/yaml/scanner.py", line 1838, in _gather_comments
    self.fetch_more_tokens()
  File "/home/finn/.pyenv/versions/3.9.13/lib/python3.9/site-packages/ruamel/yaml/scanner.py", line 288, in fetch_more_tokens
    return self.fetch_value()
  File "/home/finn/.pyenv/versions/3.9.13/lib/python3.9/site-packages/ruamel/yaml/scanner.py", line 657, in fetch_value
    raise ScannerError(
ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
  in "file:///home/finn/workspace/seek/README.md", line 23, column 34

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/finn/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cwltool/main.py", line 1085, in main
    loadingContext, workflowobj, uri = fetch_document(uri, loadingContext)
  File "/home/finn/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cwltool/load_tool.py", line 133, in fetch_document
    loadingContext.loader.fetch(fileuri, content_types=CWL_CONTENT_TYPES),
  File "schema_salad/ref_resolver.py", line 998, in fetch
schema_salad.exceptions.ValidationException: README.md:23:34: mapping values are not allowed here
```

## Your Environment
* Current cwltool version: 3.1.20230601100705
* Previously used cwltool version: 3.1.20210616134059
* Python 3.9.13
* Linux Mint 19.3

**Comment by mr-c** [comment]
Hey @fbacall , if you run `cwltool`  as an installed script, then the exit code is correct. 

```
$ cwltool --skip-schemas --quiet --enable-dev --non-strict --pack README.rst ; echo $?
ERROR Tool definition failed validation:
while scanning for the next token
README.rst:2:1:   found character '`' that cannot start any token
1
```
vs.
```
$ python -m cwltool --skip-schemas --quiet --enable-dev --non-strict --pack README.rst ; echo $?
ERROR Tool definition failed validation:
while scanning for the next token
README.rst:2:1:   found character '`' that cannot start any token
0
```
