### ISSUE TITLE
cached cannot handle URLs as input files

### ISSUE THREAD

**Issue by jjkoehorst** [common-workflow-language/cwltool#1888]
## Expected Behavior
The files should download

## Actual Behavior
It cannot find the file but it will not download it

## Workflow Code
```
See the traceback for the input yaml file

```

## Full Traceback
```pytb
cwltool --debug --tmpdir $PWD/TEMP --cachedir CACHE fastqc.yaml

INFO /usr/local/bin/cwltool 3.1.20230624081518
INFO Resolved 'fastqc.yaml' to 'file:///Volumes/Git/m-unlock/cwl/tests/quality/fastqc.yaml'
DEBUG Parsed job order from command line: {
    "id": "fastqc.yaml",
    "fastq": [
        {
            "class": "File",
            "location": "http://download.systemsbiology.nl/unlock/cwl/test_data/amplicon/forward.fastq.gz"
        },
        {
            "class": "File",
            "location": "http://download.systemsbiology.nl/unlock/cwl/test_data/amplicon/reverse.fastq.gz"
        }
    ],
    "nanopore_reads": null,
    "threads": 1
}
ERROR Got workflow error
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cwltool/executors.py", line 217, in run_jobs
    for job in jobiter:
  File "/usr/local/lib/python3.9/site-packages/cwltool/command_line_tool.py", line 836, in job
    visit_class([cachebuilder.files, cachebuilder.bindings], ("File"), _checksum)
  File "/usr/local/lib/python3.9/site-packages/cwltool/utils.py", line 220, in visit_class
    visit_class(d, cls, op)
  File "/usr/local/lib/python3.9/site-packages/cwltool/utils.py", line 220, in visit_class
    visit_class(d, cls, op)
  File "/usr/local/lib/python3.9/site-packages/cwltool/utils.py", line 215, in visit_class
    op(rec)
  File "/usr/local/lib/python3.9/site-packages/cwltool/process.py", line 1345, in compute_checksums
    with fs_access.open(location, "rb") as f:
  File "/usr/local/lib/python3.9/site-packages/cwltool/stdfsaccess.py", line 38, in open
    return open(self._abs(fn), mode)
FileNotFoundError: [Errno 2] No such file or directory: 'http://download.systemsbiology.nl/unlock/cwl/test_data/amplicon/forward.fastq.gz'
ERROR Workflow error:
[Errno 2] No such file or directory: 'http://download.systemsbiology.nl/unlock/cwl/test_data/amplicon/forward.fastq.gz'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cwltool/executors.py", line 217, in run_jobs
    for job in jobiter:
  File "/usr/local/lib/python3.9/site-packages/cwltool/command_line_tool.py", line 836, in job
    visit_class([cachebuilder.files, cachebuilder.bindings], ("File"), _checksum)
  File "/usr/local/lib/python3.9/site-packages/cwltool/utils.py", line 220, in visit_class
    visit_class(d, cls, op)
  File "/usr/local/lib/python3.9/site-packages/cwltool/utils.py", line 220, in visit_class
    visit_class(d, cls, op)
  File "/usr/local/lib/python3.9/site-packages/cwltool/utils.py", line 215, in visit_class
    op(rec)
  File "/usr/local/lib/python3.9/site-packages/cwltool/process.py", line 1345, in compute_checksums
    with fs_access.open(location, "rb") as f:
  File "/usr/local/lib/python3.9/site-packages/cwltool/stdfsaccess.py", line 38, in open
    return open(self._abs(fn), mode)
FileNotFoundError: [Errno 2] No such file or directory: 'http://download.systemsbiology.nl/unlock/cwl/test_data/amplicon/forward.fastq.gz'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cwltool/main.py", line 1298, in main
    (out, status) = real_executor(
  File "/usr/local/lib/python3.9/site-packages/cwltool/executors.py", line 61, in __call__
    return self.execute(process, job_order_object, runtime_context, logger)
  File "/usr/local/lib/python3.9/site-packages/cwltool/executors.py", line 144, in execute
    self.run_jobs(process, job_order_object, logger, runtime_context)
  File "/usr/local/lib/python3.9/site-packages/cwltool/executors.py", line 251, in run_jobs
    raise WorkflowException(str(err)) from err
cwltool.errors.WorkflowException: [Errno 2] No such file or directory: 'http://download.systemsbiology.nl/unlock/cwl/test_data/amplicon/forward.fastq.gz'
```

## Your Environment
* cwltool version: 3.1.20230624081518
Check using ``cwltool --version``

**Comment by jjkoehorst** [comment]
Duplicate of https://github.com/common-workflow-language/cwltool/issues/1842 and https://github.com/common-workflow-language/cwltool/issues/1828 I think
