### ISSUE TITLE
Error with --outdir

### ISSUE THREAD

**Issue by mepstein-gh** [common-workflow-language/cwltool#205]
When I run the command:

cwltool --cachedir workflow_cache --outdir workflow_output completeWorkflow.cwl input.yml

I get:

Unhandled error, try again with --debug for more information:
  [Errno 2] No such file or directory: ''

Here's what I get with --debug:

Unhandled error, try again with --debug for more information:
  [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "/home/mepstein/.local/lib/python2.7/site-packages/cwltool/main.py", line 721, in main
    **vars(args))
  File "/home/mepstein/.local/lib/python2.7/site-packages/cwltool/main.py", line 230, in single_job_executor
    output_dirs, kwargs.get("move_outputs"))
  File "/home/mepstein/.local/lib/python2.7/site-packages/cwltool/process.py", line 215, in relocateOutputs
    stageFiles(pm, moveIt)
  File "/home/mepstein/.local/lib/python2.7/site-packages/cwltool/process.py", line 176, in stageFiles
    os.makedirs(os.path.dirname(p.target), 0755)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: ''

When I add some debugging print's to process.py, I see (just before the error):

MapperEnt(resolved='file:///home/mepstein/tmp/workflows/workflow_cache/9540f1f896b3ab1f435e83798bcf79f5', target='workflow_output', type='Directory')

so when it does os.path.dirname() on 'workflow_output', it's '', hence the error.

Is this a bug in cwltool?

Note that when I run the same command without --outdir, or I do a command like:

cwltool --cachedir /shared/mepstein/cachedir --outdir /shared/mepstein/workflow_output completeWorkflow.cwl input.yml

it works fine, there's no error.

**Comment by mr-c** [comment]
@mepstein-gh This is the workflow, yes? https://github.com/h3abionet/h3abionet16S/blob/master/workflows/completeWorkflow.cwl

**Comment by mr-c** [comment]
@mepstein-gh Does the output directory exist before running `cwltool`

**Comment by mepstein-gh** [comment]
Yes, that is the workflow, and while I had only previously tried the command without first creating the output directory, I just tried creating it first, and the error still happens.  (The output directory does get created if it doesn't already exist.)

The thing is, I don't think either of these things are relevant -- if you take a closer look at what I posted above, the error happens when --outdir is a subdirectory of the current working directory -- I think that is the most relevant thing (and it's not disallowed, is it?).  I just tried running it with a much simpler cwl file, with and without --cachedir, and in both cases the error occurs.  I'm guessing you can get the same behavior with any cwl file.

I don't have a complete understanding of what's going on here in the code, but at a low-level, this perhaps could be fixed by changing stageFiles() in process.py, to not call os.makedirs() if p.target is a bare name.  But whether that's a clean solution looking at things from a higher level, I'm not sure.

**Comment by mepstein-gh** [comment]
I did some more testing, and it does work with some cwl files.  Looks like whether it fails may depend on how much of a directory structure the cwl file creates for the output (that will need to be moved/copied to the output directory) -- with a single output file, it works; with a directory structure a couple levels deep, it fails.

**Comment by tetron** [comment]
Hi @mepstein-gh, do you have a small test case that reproduces this?

**Comment by mepstein-gh** [comment]
I think this will do it:

Start out in a clean/new directory.  Create a file: touch test.  Put it in a tar file: tar cf test.tar test.

Use this cwl file (tar.cwl):
`cwlVersion: v1.0
class: CommandLineTool
baseCommand: [tar, xf]
inputs:
  tarfile:
    type: File
    inputBinding:
      position: 1
outputs:
  report:
    type: Directory
    outputBinding:
      glob: "."
`

Issue the command: cwltool --outdir out tar.cwl --tarfile test.tar

**Comment by mepstein-gh** [comment]
Here's a diff/patch (on the function stageFiles() in the file process.py) I used to deal with this issue:

<pre>
--- process.py.orig     2016-07-26 08:55:35.000000000 -0500
+++ process.py  2016-10-12 10:30:42.357323872 -0500
@@ -172,8 +172,9 @@
 def stageFiles(pm, stageFunc, ignoreWritable=False):
     # type: (PathMapper, Callable[..., Any]) -> None
     for f, p in pm.items():
-        if not os.path.exists(os.path.dirname(p.target)):
-            os.makedirs(os.path.dirname(p.target), 0755)
+        dirname = os.path.dirname(p.target)
+        if dirname and not os.path.exists(dirname):
+            os.makedirs(dirname, 0755)
         if p.type == "File":
             stageFunc(p.resolved, p.target)
         elif p.type == "WritableFile" and not ignoreWritable:
</pre>

I don't have access to the environment where I made these changes, so I recreated them from memory (so it's untested and might have bugs/typos).  Also, as I commented before, this deals with things at the low level, but might not be correct/complete/clean when considered from a higher level
