### ISSUE TITLE
cwltool does not recognize length as a special field

### ISSUE THREAD

**Issue by sguthrie** [common-workflow-language/cwltool#235]
When not using the full javascript engine, cwltool doesn't recognize length as a special field in `$(input.files.length)` but it should.

I'm interested in requesting a maximum number of cores to be equal to the number of files in an input of type `File[]`. However, when I set `maxCores: $(input.files.length)`, I get the error `ERROR: Execution failed: list indices must be integers, not str`. 

CWL and yml inputs are provided in the zip attached: [fastqc.zip](https://github.com/common-workflow-language/cwltool/files/605465/fastqc.zip)

Full traceback is below:
```
$ cwltool fastqc.cwl fastqc_local_inputs.yml 
/usr/bin/cwltool 1.0.20161107145355
Got workflow error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cwltool/main.py", line 220, in single_job_executor
    for r in jobiter:
  File "/usr/lib/python2.7/dist-packages/cwltool/draft2tool.py", line 243, in job
    builder = self._init_job(joborder, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cwltool/process.py", line 508, in _init_job
    builder.resources = self.evalResources(builder, kwargs)
  File "/usr/lib/python2.7/dist-packages/cwltool/process.py", line 533, in evalResources
    mx = builder.do_eval(resourceReq[a+"Max"])
  File "/usr/lib/python2.7/dist-packages/cwltool/builder.py", line 206, in do_eval
    timeout=self.timeout)
  File "/usr/lib/python2.7/dist-packages/cwltool/expression.py", line 185, in do_eval
    jslib=jslib)
  File "/usr/lib/python2.7/dist-packages/cwltool/expression.py", line 143, in interpolate
    timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/cwltool/expression.py", line 126, in evaluator
    return next_seg(m.group(0)[m.end(1) - m.start(0):-1], obj[m.group(1)])
  File "/usr/lib/python2.7/dist-packages/cwltool/expression.py", line 112, in next_seg
    return next_seg(remain[m.end(0):], obj[m.group(0)[1:]])
  File "/usr/lib/python2.7/dist-packages/cwltool/expression.py", line 112, in next_seg
    return next_seg(remain[m.end(0):], obj[m.group(0)[1:]])
TypeError: list indices must be integers, not str
Workflow error, try again with --debug for more information:
  list indices must be integers, not st
```

**Comment by mr-c** [comment]
@sguthrie Thank you very much for your report!

I can confirm that `cwltool` with the full javascript engine and using a ECMAScript expression referencing the `length` property `ResourceRequirement: { coresMin: $(inputs.fastqfiles.length) }` fails when it should not.

As a workaround for `cwltool` you can instead use a `${...}` wrapped EMACScript function body as follows:
```
[...]
requirements:
  InlineJavascriptRequirement: {}
  ResourceRequirement:
    coresMin: ${return inputs.fastqfiles.length;}
[...]
```

As we stated in the [conversation in the CWL chat room](https://gitter.im/common-workflow-language/common-workflow-language?at=58330eccb7cf637f2aca7fba) to support the very reasonable use case of referring to the length of an array without the full javascript engine will require changes to the CWL specifications as we don't that say that any special fields are allowed in a CWL parameter reference. The issue to discuss that proposal is at https://github.com/common-workflow-language/common-workflow-language/issues/350

**Comment by tetron** [comment]
I think this is fixed but need to verify.
