### ISSUE TITLE
pip install --upgrade cwltool fails

### ISSUE THREAD

**Issue by prismofeverything** [common-workflow-language/cwltool#255]
Trying to upgrade to the latest cwltool fails with a strange error:

    > pip install --upgrade cwltool
```
Collecting cwltool
  Using cached cwltool-1.0.20161207161158.tar.gz
Collecting setuptools (from cwltool)
  Using cached setuptools-32.0.0-py2.py3-none-any.whl
Collecting requests>=1.0 (from cwltool)
  Using cached requests-2.12.4-py2.py3-none-any.whl
Collecting ruamel.yaml==0.12.4 (from cwltool)
  Using cached ruamel.yaml-0.12.4.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/local/lib/python2.7/site-packages/setuptools/extern/__init__.py:1: UserWarning: Module _ruamel_yaml was already imported from /usr/local/lib/python2.7/site-packages/_ruamel_yaml.so, but /private/var/folders/2m/0shxv04j04lcm1c0dddyf4qw0000gn/T/pip-build-ZgFmHv/ruamel.yaml is being added to sys.path
      from pkg_resources.extern import VendorImporter
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2m/0shxv04j04lcm1c0dddyf4qw0000gn/T/pip-build-ZgFmHv/ruamel.yaml/setup.py", line 733, in <module>
        main()
      File "/private/var/folders/2m/0shxv04j04lcm1c0dddyf4qw0000gn/T/pip-build-ZgFmHv/ruamel.yaml/setup.py", line 730, in main
        setup(**kw)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 326, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2384, in require
        reqs = self.dist.requires(self.extras)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2629, in requires
        dm = self._dep_map
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2685, in __getattr__
        raise AttributeError(attr)
    AttributeError: _dep_map
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/2m/0shxv04j04lcm1c0dddyf4qw0000gn/T/pip-build-ZgFmHv/ruamel.yaml/
```

**Comment by mr-c** [comment]
Hello @prismofeverything ; my apologies for the extremely late reply. We think this issue has been fixed https://github.com/common-workflow-language/cwltool/issues/253#issuecomment-268580880

Please feel free to reopen this issue if the problem is not fixed for you.

Thank you for reporting this!
