### ISSUE TITLE
Better Error message when cwl.output.json is invalid

### ISSUE THREAD

**Issue by bpmweel** [common-workflow-language/cwltool#291]
```Exception while running job
Traceback (most recent call last):
  File "/home/bweel/anaconda2/lib/python2.7/site-packages/cwltool/job.py", line 296, in run
    outputs = self.collect_outputs(self.outdir)
  File "/home/bweel/anaconda2/lib/python2.7/site-packages/cwltool/draft2tool.py", line 390, in collect_output_ports
    ret = json.load(f)
  File "/home/bweel/anaconda2/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/home/bweel/anaconda2/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/home/bweel/anaconda2/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/bweel/anaconda2/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 1 column 3 (char 2)```

**Comment by mr-c** [comment]
@bpmweel My memory is that your output had some non-JSON free text in front, and didn't quote the key value pairs, correct?
