### ISSUE TITLE
Error if prefix is absent

### ISSUE THREAD

**Issue by annam30** [common-workflow-language/cwltool#298]
Hello!
If there is no "prefix" in workflow.step.run.inputBinding: 
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cwltool/workflow.py", line 587, in job
    **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/cwltool/draft2tool.py", line 382, in job
    j.command_line = flatten(map(builder.generate_arg, builder.bindings))
  File "/usr/local/lib/python2.7/dist-packages/cwltool/builder.py", line 198, in generate_arg
    args.append(prefix + self.tostr(j))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[step varscan] Cannot make job: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by mr-c** [comment]
Hello @annam30 , thank you for reporting this!

I'm a bit busy with travel and meetings week, but I will look into this need

**Comment by mr-c** [comment]
Can you share your CWL workflow? I am a bit surprised by the error message as it isn't helpful as they normally are and I would like to fix that.

It isn't valid to have an `inputBinding` inside the `run` entry of a `WorkflowStep` http://www.commonwl.org/v1.0/Workflow.html#WorkflowStep, so I don't know what you mean by `workflow.step.run.inputBinding`

**Comment by kapilkd13** [comment]
Hi @annam30 Are you still facing this problem. If yes, can you provide us your CWL workflow so that we can replicate this issue. Or, we may have to close this issue due to lack of information to replicate this error.

**Comment by mr-c** [comment]
I think we should study the code & traceback to see if we can still reproduce the issue ourselves before closing this issue
