### ISSUE TITLE
KeyError: 'location' - Cannot make job: 'location'

### ISSUE THREAD

**Issue by gijzelaerr** [common-workflow-language/cwltool#303]
Looks like i found an other bug while writing these CWL files:

https://github.com/gijzelaerr/vermeerkat-cwl/tree/master/cwl

```
.virtualenv/bin/cwl-runner --outdir results --cachedir cache cwl/workflow.cwl cwl/job.cwl
.virtualenv/bin/cwl-runner 1.0.20170223161812
Resolved 'cwl/workflow.cwl' to 'file:///home/gijs/Work/vermeerkat-cwl/cwl/workflow.cwl'
[job curl] Using cached output in /home/gijs/Work/vermeerkat-cwl/cache/175791fc94a768e7e925838df7b083b2
[step curl] completed success
[job h5toms] Using cached output in /home/gijs/Work/vermeerkat-cwl/cache/106bf4457e4f2930c4189f9e7158d0ed
[step h5toms] completed success
Unexpected exception
Traceback (most recent call last):
  File "/home/gijs/Work/cwltool/cwltool/workflow.py", line 587, in job
    **kwargs):
  File "/home/gijs/Work/cwltool/cwltool/draft2tool.py", line 190, in job
    separateDirs=False)
  File "/home/gijs/Work/cwltool/cwltool/pathmapper.py", line 150, in __init__
    self.setup(dedup(referenced_files), basedir)
  File "/home/gijs/Work/cwltool/cwltool/pathmapper.py", line 104, in dedup
    if r["location"] not in marksub and r["location"] not in markdup:
  File "/home/gijs/Work/vermeerkat-cwl/.virtualenv/local/lib/python2.7/site-packages/ruamel/yaml/comments.py", line 595, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'location'
[step rfimasker] Cannot make job: 'location'
```

**Comment by gijzelaerr** [comment]
If I manually set the 'location' field in the job file, It complains I need to set basename also. If I also set that field it runs, but the variable field is empty.

**Comment by gijzelaerr** [comment]
AHA! I accidentally set the field name to `file`, not `File`.

**Comment by mr-c** [comment]
@gijzelaerr :-) All good now?

Can you link to the commit that gave you the above error? I would still like to improve `cwltool`'s error reporting

**Comment by gijzelaerr** [comment]
yeah it is working, but the error is a bit confusing.

Sorry, forgot to link to the commit directly:

https://github.com/gijzelaerr/vermeerkat-cwl/blob/5ce4b56269d4a854e9522fb17bd76eedc9a4edd2/cwl/job.cwl
