### ISSUE TITLE
cwltool fails with array of File as input

### ISSUE THREAD

**Issue by Welliton309** [common-workflow-language/cwltool#372]
I am trying to describe a tool that inputs many FASTQ files and outputs only one file. However, the cwltool fails when I define an array of File as input. I wrote a minimal example to reproduce this error using `cat` command.

`cat.cwl` file:

``` yml
cwlVersion: v1.0
class: CommandLineTool
baseCommand: [cat]
stdout: output.txt

inputs:
  files:
    type: File[]
    inputBinding: {}

outputs:
  output:
    type: stdout
```

`cat-test.yml` file:

``` yml
files:
  class: File
  path: [file1.txt, file2.txt, file3.txt]
```

Command:

``` bash
cwl-runner cat.cwl cat-test.yml
```

Error:

<details>

```
/usr/local/bin/cwl-runner 1.0.20170413194156
Resolved 'cat.cwl' to '/home/welliton/cat.cwl'
Traceback (most recent call last):
  File "/usr/local/bin/cwl-runner", line 9, in <module>
    load_entry_point('cwl-runner==1.0', 'console_scripts', 'cwl-runner')()
  File "/usr/local/lib/python2.7/dist-packages/cwltool/main.py", line 753, in main
    fetcher_constructor=fetcher_constructor)
  File "/usr/local/lib/python2.7/dist-packages/cwltool/main.py", line 509, in load_job_order
    normalizeFilesDirs(job_order_object)
  File "/usr/local/lib/python2.7/dist-packages/cwltool/pathmapper.py", line 78, in normalizeFilesDirs
    adjustFileObjs(job, addLocation)
  File "/usr/local/lib/python2.7/dist-packages/cwltool/pathmapper.py", line 41, in adjustFileObjs
    adjustFileObjs(rec[d], op)
  File "/usr/local/lib/python2.7/dist-packages/cwltool/pathmapper.py", line 39, in adjustFileObjs
    op(rec)
  File "/usr/local/lib/python2.7/dist-packages/cwltool/pathmapper.py", line 75, in addLocation
    parse = urllib.parse.urlparse(d["location"])
  File "/usr/lib/python2.7/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python2.7/urlparse.py", line 176, in urlsplit
    cached = _parse_cache.get(key, None)
TypeError: unhashable type: 'CommentedSeq'
````

</details>

Is there any example of using an array of File as input? I followed the [user guide](http://www.commonwl.org/v1.0/UserGuide.html#Array_inputs).

**Comment by mr-c** [comment]
Hello @Welliton309 , thank you for your report, I appreciate it!

The issue is with the input specification, it should be:
```
files:
  - class: File
    path: file1.txt
  - class: File
    path: file2.txt
  - class: File
    path: file3.txt
```

That wasn't a very helpful error message, so I'm going to rename this issue to remind us to fix that.

**Comment by Welliton309** [comment]
Thank you @mr-c . It worked very well!
