### ISSUE TITLE
cwl-runner says "The 'cwlref-runner==1.0' distribution was not found and is required by the application"

### ISSUE THREAD

**Issue by thefantasticdron** [common-workflow-language/cwltool#375]
I installed cwltool using the following commands:
```bash
[las2@lmem06 bin]$ pip install --install-option="--prefix=/my/dir" cwlref-runner
```
`/my/dir/` isn't the real directory name, just an example.
I tried using cwl-runner, and it threw the following error:
```bash
[las2@lmem06 bin]$ ./cwl-runner                                                                               
Traceback (most recent call last):
  File "./cwl-runner", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/python-2.7env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/opt/python-2.7env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/opt/python-2.7env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/python-2.7env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "/opt/python-2.7env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/python-2.7env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cwlref-runner==1.0' distribution was not found and is required by the application
```
Thanks!

**Comment by manu-chroma** [comment]
@thefantasticdron were you able to resolve your issue?

**Comment by ATpoint** [comment]
If anyone cares, I had the same and the issue was that I was installing cwltool via conda from the bioconda rather than the conda-forge channel. So use `mamba create conda-forge::cwltool`.
