### ISSUE TITLE
AttributeError: 'list' object has no attribute 'startswith' when giving a list to outputbinding

### ISSUE THREAD

**Issue by philloooo** [common-workflow-language/cwltool#43]
So I am trying to use an input array in an outputbinding, but I got this error.
Example cwl:
```
inputs:
  - id: "#ids"
    type:
      type: array
      items: string
    default: null
    inputBinding:
      prefix: --ids
outputs:
  - id: "#files"
    type:
      type: array
      items: File
    outputBinding:
      glob:
        engine: node-engine.cwl
        script: |
          {
          return inputs["keys"];
          }
```
Error:
```
Exception while running job
Traceback (most recent call last):
  File "/Users/yajing/Documents/.venv/lib/python2.7/site-packages/cwltool/job.py", line 179, in run
    outputs = self.collect_outputs(self.outdir)
  File "/Users/yajing/Documents/.venv/lib/python2.7/site-packages/cwltool/draft2tool.py", line 196, in collect_output_ports
    ret[fragment] = self.collect_output(port, builder, outdir)
  File "/Users/yajing/Documents/.venv/lib/python2.7/site-packages/cwltool/draft2tool.py", line 214, in collect_output
    r.extend([{"path": g, "class": "File"} for g in builder.fs_access.glob(os.path.join(outdir, gb))])
  File "/Users/yajing/Documents/.venv/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'list' object has no attribute 'startswith'
[job 4418143504] completed permanentFail
Final process status is permanentFail
Workflow error:
  Process status is ['permanentFail']
```
By cwl draft3, `glob` should be able to handle an array right?

**Comment by tetron** [comment]
Fixed in a9553372b950fbb0598a831256d51e17aba9490a
