### ISSUE TITLE
Valid workflow cannot have RDF generated due to lack of urlencoding

### ISSUE THREAD

**Issue by MarkRobbo** [common-workflow-language/cwltool#444]
## Problem

When running

```
cwltool --validate https://raw.githubusercontent.com/ProteinsWebTeam/ebi-metagenomics-cwl/f6b5196bd493b0872ee6e63aa3499738bb7d53d6/workflows/emg-pipeline-v3.cwl
```

The workflow passes validation without issue. However when trying to generate RDF

```
cwltool --print-rdf https://raw.githubusercontent.com/ProteinsWebTeam/ebi-metagenomics-cwl/f6b5196bd493b0872ee6e63aa3499738bb7d53d6/workflows/emg-pipeline-v3.cwl
```

```
I'm sorry, I couldn't load this CWL file, try again with --debug for more information.
The error was: "https://raw.githubusercontent.com/ProteinsWebTeam/ebi-metagenomics-cwl/f6b5196bd493b0872ee6e63aa3499738bb7d53d6/tools/biom-convert-table.yaml#table_type/Function table" does not look like a valid URI, I cannot serialize this as N3/Turtle. Perhaps you wanted to urlencode it?
```

URLs generated by cwltool are not urlencoded before generating the Turtle representation and so an error is thrown. These should be urlencoded or cwltool more restrictive on the types of symbols allowed.

## Workflow Code

[Overall workflow](https://raw.githubusercontent.com/ProteinsWebTeam/ebi-metagenomics-cwl/f6b5196bd493b0872ee6e63aa3499738bb7d53d6/workflows/emg-pipeline-v3.cwl)

[Problem file with space in symbols](https://github.com/ProteinsWebTeam/ebi-metagenomics-cwl/blob/master/tools/biom-convert-table.yaml)

## Your Environment
* cwltool version: 1.0.20170622090721

**Comment by tetron** [comment]
Good catch.  IIRC the spec doesn't put any restrictions on identifiers, although maybe it should.  I think urlencoding is probably the right fix.

**Comment by manu-chroma** [comment]
Running with cwltool master:

``` pytb
(venv) [venv] ~/github/cwltool · (master±) $ cwltool --debug --validate https://raw.githubusercontent.com/ProteinsWebTeam/ebi-metagenomics-cwl/f6b5196bd493b0872ee6e63aa3499738bb7d53d6/workflows/emg-pipeline-v3.cwl                 21:31:35
/home/manu/github/cwltool/venv/bin/cwltool 1.0.20170812174804
https://raw.githubusercontent.com/ProteinsWebTeam/ebi-metagenomics-cwl/f6b5196bd493b0872ee6e63aa3499738bb7d53d6/workflows/emg-pipeline-v3.cwl:1:1: unrecognized extension field `http://schema.org/license`.  Did you include a $schemas section?
https://raw.githubusercontent.com/ProteinsWebTeam/ebi-metagenomics-cwl/f6b5196bd493b0872ee6e63aa3499738bb7d53d6/workflows/emg-pipeline-v3.cwl:1:1: unrecognized extension field `http://schema.org/copyrightHolder`.  Did you include a $schemas section?
No handlers could be found for logger "rdflib.term"
^CTraceback (most recent call last):
  File "/home/manu/github/cwltool/venv/bin/cwltool", line 11, in <module>
    load_entry_point('cwltool', 'console_scripts', 'cwltool')()
  File "/home/manu/github/cwltool/cwltool/main.py", line 831, in main
    makeTool, make_tool_kwds)
  File "/home/manu/github/cwltool/cwltool/load_tool.py", line 260, in make_tool
    tool = makeTool(processobj, **kwargs)
  File "/home/manu/github/cwltool/cwltool/workflow.py", line 40, in defaultMakeTool
    return Workflow(toolpath_object, **kwargs)
  File "/home/manu/github/cwltool/cwltool/workflow.py", line 518, in __init__
    self.steps.append(WorkflowStep(step, n, **kwargs))
  File "/home/manu/github/cwltool/cwltool/workflow.py", line 677, in __init__
    resolver=kwargs.get("resolver"))
  File "/home/manu/github/cwltool/cwltool/load_tool.py", line 287, in load_tool
    makeTool, kwargs if kwargs else {})
  File "/home/manu/github/cwltool/cwltool/load_tool.py", line 260, in make_tool
    tool = makeTool(processobj, **kwargs)
  File "/home/manu/github/cwltool/cwltool/workflow.py", line 40, in defaultMakeTool
    return Workflow(toolpath_object, **kwargs)
  File "/home/manu/github/cwltool/cwltool/workflow.py", line 518, in __init__
    self.steps.append(WorkflowStep(step, n, **kwargs))
  File "/home/manu/github/cwltool/cwltool/workflow.py", line 677, in __init__
    resolver=kwargs.get("resolver"))
  File "/home/manu/github/cwltool/cwltool/load_tool.py", line 285, in load_tool
    strict=strict, fetcher_constructor=fetcher_constructor)
  File "/home/manu/github/cwltool/cwltool/load_tool.py", line 199, in validate_document
    processobj, metadata = document_loader.resolve_all(workflowobj, fileuri)
  File "/home/manu/github/schema_salad/schema_salad/ref_resolver.py", line 785, in resolve_all
    newctx.add_schemas(document[u"$schemas"], file_base)
  File "/home/manu/github/schema_salad/schema_salad/ref_resolver.py", line 369, in add_schemas
    self.idx[six.text_type(s)] = None
  File "/home/manu/github/schema_salad/schema_salad/ref_resolver.py", line 78, in __setitem__
    return super(NormDict, self).__setitem__(self.normalize(key), value)
KeyboardInterrupt
```
