### ISSUE TITLE
Windows 10 issue

### ISSUE THREAD

**Issue by xamgore** [common-workflow-language/cwltool#514]
Execution of `cwltool --version --debug` fails on Windows 10. I did `pip install cwltool`.

## Full Traceback
```pytb
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\cwltool.exe\__main__.py", line 5, in <module>
  File "c:\program files\python36\lib\site-packages\cwltool\main.py", line 22, in <module>
    import schema_salad.validate as validate
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "c:\program files\python36\lib\site-packages\past\translation\__init__.py", line 341, in load_module
    mod = imp.load_module(fullname, *self.found)
  File "c:\program files\python36\lib\imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "c:\program files\python36\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "c:\program files\python36\lib\site-packages\schema_salad\validate.py", line 3, in <module>
    import avro.schema
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "c:\program files\python36\lib\site-packages\past\translation\__init__.py", line 396, in load_module
    if detect_python2(source, self.pathname):
  File "c:\program files\python36\lib\site-packages\past\translation\__init__.py", line 222, in detect_python2
    with open('/tmp/original_code.py', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/original_code.py'
```

## Your Environment
* python version
Python 3.6.2

**Comment by kapilkd13** [comment]
Similar issue https://github.com/common-workflow-language/cwltool/issues/499 A PR has been made for it here https://github.com/common-workflow-language/schema_salad/pull/125/files I guess a new release of schema-salad will solve this.

**Comment by xamgore** [comment]
@kapilkd13 oh, thanks.

**Comment by kapilkd13** [comment]
@xamgore  If its urgent, I would suggest you to source install `schema-salad`. In the meantime I will try to get a fresh release of schema-salad.

**Comment by xamgore** [comment]
@kapilkd13 no-no, thanks :) I can wait a week or two.

**Comment by mr-c** [comment]
I've released [schema-salad v 2.6.20170806163416](https://pypi.python.org/pypi/schema-salad/2.6.20170806163416)

**Comment by kapilkd13** [comment]
Thanks @mr-c  😃 I tested with pip install, works Fine!!

**Comment by xamgore** [comment]
Yeah, that's fine, thank you, @mr-c!
