### ISSUE TITLE
CWL+Toil+Restarts produces "Got workflow error"

### ISSUE THREAD

**Issue by evan-wehi** [common-workflow-language/cwltool#541]
I'm sure that is really fits in with the template. I have large workflow, 10x human genomes, ~15 steps about a week of runtime. I've had to restart it because our cluster failed and initially the restart seemed to work well, it ran for several more days. It then failed with the following:
```
Got workflow error
Traceback (most recent call last):
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/cwltool/main.py", line 281, in single_job_executor
    r.run(**kwargs)
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/cwltool/job.py", line 307, in run
    stageFiles(self.generatemapper, ignoreWritable=self.inplace_update, symLink=True)
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/cwltool/process.py", line 227, in stageFiles
    os.symlink(p.resolved, p.target)
OSError: [Errno 17] File exists
ERROR:cwltool:Got workflow error
Traceback (most recent call last):
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/cwltool/main.py", line 281, in single_job_executor
    r.run(**kwargs)
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/cwltool/job.py", line 307, in run
    stageFiles(self.generatemapper, ignoreWritable=self.inplace_update, symLink=True)
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/cwltool/process.py", line 227, in stageFiles
    os.symlink(p.resolved, p.target)
OSError: [Errno 17] File exists
DEBUG:toil.fileStore:LOG-TO-MASTER: Job 'file:///stornext/HPCScratch/PapenfussLab/projects/ovary-work/pdx-genome/tools/src/tools/samtools-index.cwl' samtools index s/k/jobRYYJes used 4002.83% (80.1 GB [85960163328B] used, 2.0 GB [2147483648B] requested) at the end of its run.
WARNING:toil.fileStore:LOG-TO-MASTER: Job used more disk than requested. Please reconsider modifying the user script to avoid the chance  of failure due to incorrectly requested resources. Job 'file:///stornext/HPCScratch/PapenfussLab/projects/ovary-work/pdx-genome/tools/src/tools/samtools-index.cwl' samtools index s/k/jobRYYJes used 4002.83% (80.1 GB [85960163328B] used, 2.0 GB [2147483648B] requested) at the end of its run.
DEBUG:toil.fileStore:CACHE: Obtained lock on file /home/thomas.e/tmp/toil-8f27be6d-d41a-4567-bf63-6b298c5302fe-e0b198a6-1d82-4bc3-9fd8-97741b77688b/cache-8f27be6d-d41a-4567-bf63-6b298c5302fe/.cacheLock
DEBUG:toil.fileStore:LOG-TO-MASTER: Successfully deleted local copies of file with ID 'g/C/tmpRxqHOu.tmp'.
DEBUG:toil.fileStore:CACHE: Released lock
DEBUG:toil.fileStore:CACHE: Obtained lock on file /home/thomas.e/tmp/toil-8f27be6d-d41a-4567-bf63-6b298c5302fe-e0b198a6-1d82-4bc3-9fd8-97741b77688b/cache-8f27be6d-d41a-4567-bf63-6b298c5302fe/.cacheLock
DEBUG:toil.fileStore:CACHE: Released lock
DEBUG:toil.fileStore:CACHE: Obtained lock on file /home/thomas.e/tmp/toil-8f27be6d-d41a-4567-bf63-6b298c5302fe-e0b198a6-1d82-4bc3-9fd8-97741b77688b/cache-8f27be6d-d41a-4567-bf63-6b298c5302fe/.cacheLock
DEBUG:toil.fileStore:CACHE: Released lock
Traceback (most recent call last):
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/toil/worker.py", line 340, in main
    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/toil/job.py", line 1289, in _runner
    returnValues = self._run(jobGraph, fileStore)
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/toil/job.py", line 1234, in _run
    return self.run(fileStore)
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 306, in run
    **opts)
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/cwltool/main.py", line 289, in single_job_executor
    raise WorkflowException(Text(e))
WorkflowException: [Errno 17] File exists
ERROR:toil.worker:Exiting the worker because of a failed job on host trqn-n51538.hpc.wehi.edu.au
WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'file:///stornext/HPCScratch/PapenfussLab/projects/ovary-work/pdx-genome/tools/src/tools/samtools-index.cwl' samtools index s/k/jobRYYJes with ID s/k/jobRYYJes to 0
<=========
```

If I restart it just produces the same error. Not sure what other information I should provide.

Here is some version info:
```
(toil-env) [thomas.e@torquelord ovary]$ cwltoil --version
3.9.1
(toil-env) [thomas.e@torquelord ovary]$ cwltool --version
/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/bin/cwltool 1.0.20170822192924
```

**Comment by evan-wehi** [comment]
This is a cross post: https://github.com/BD2KGenomics/toil/issues/1872

**Comment by mr-c** [comment]
Hey @evan-wehi , I think this is more of a toil issue, so I'm going to close this for now.
