### ISSUE TITLE
UnboundLocalError: local variable 'dockerimg' referenced before assignment

### ISSUE THREAD

**Issue by gijzelaerr** [common-workflow-language/cwltool#552]
```
.virtualenv/bin/cwltool \
	--enable-ext \
	--outdir results \
	--cachedir cache \
	workflow.cwl \
	job.cwl
.virtualenv/bin/cwltool 1.0.20171017195544
Resolved 'workflow.cwl' to 'file:///home/gijs/prefactor-cwl/workflow.cwl'
[workflow workflow.cwl] start
[step createmap_cal] start
Unexpected exception
Traceback (most recent call last):
  File "/home/gijs/prefactor-cwl/.virtualenv/local/lib/python2.7/site-packages/cwltool/workflow.py", line 810, in job
    **kwargs):
  File "/home/gijs/prefactor-cwl/.virtualenv/local/lib/python2.7/site-packages/cwltool/draft2tool.py", line 268, in job
    if dockerimg:
UnboundLocalError: local variable 'dockerimg' referenced before assignment
[step createmap_cal] Cannot make job: local variable 'dockerimg' referenced before assignment
[workflow workflow.cwl] completed permanentFail
{
    "mapfile": null
}
Final process status is permanentFail
```

CWL files: https://github.com/gijzelaerr/prefactor-cwl/tree/9bd863af640a75a69342d7a2e890d60cfe15f002

**Comment by mr-c** [comment]
Confirmed with this single line test:
```
cwltool --cachedir cache https://raw.githubusercontent.com/gijzelaerr/prefactor-cwl/9bd863af640a75a69342d7a2e890d60cfe15f002/workflow.cwl --ms $(mktemp -d)
```
