### ISSUE TITLE
unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by gijzelaerr** [common-workflow-language/cwltool#553]
```
$ .virtualenv/bin/cwltool ndppp_prep_cal.cwl --msin data/L591513_SB000_uv.MS
.virtualenv/bin/cwltool 1.0.20171017195544
Resolved 'ndppp_prep_cal.cwl' to 'file:///home/gijs/prefactor-cwl/ndppp_prep_cal.cwl'
Got workflow error
Traceback (most recent call last):
start of ndppp_prep_cal step
  File "/home/gijs/prefactor-cwl/.virtualenv/local/lib/python2.7/site-packages/cwltool/main.py", line 283, in single_job_executor
    for r in jobiter:
  File "/home/gijs/prefactor-cwl/.virtualenv/local/lib/python2.7/site-packages/cwltool/draft2tool.py", line 496, in job
    j.command_line = flatten(list(map(builder.generate_arg, builder.bindings)))
  File "/home/gijs/prefactor-cwl/.virtualenv/local/lib/python2.7/site-packages/cwltool/builder.py", line 243, in generate_arg
    args.append(prefix + self.tostr(j))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
Workflow error, try again with --debug for more information:
unsupported operand type(s) for +: 'NoneType' and 'str'
```

CWL script:

https://github.com/gijzelaerr/prefactor-cwl/blob/393a99922fe84e161df1973bb30607295c0f9672/ndppp_prep_cal.cwl

**Comment by mr-c** [comment]
While the CWL description is wrong, the error experienced is worse and should be fixed. Thank you @gijzelaerr for the report
