### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by gijzelaerr** [common-workflow-language/cwltool#555]
```
$ .virtualenv/bin/cwltool --debug ndppp_prep_cal.cwl --msin data/L591513_SB000_uv.MS
.virtualenv/bin/cwltool 1.0.20171017195544
Resolved 'ndppp_prep_cal.cwl' to 'file:///home/gijs/prefactor-cwl/ndppp_prep_cal.cwl'
I'm sorry, I couldn't load this CWL file.  The error was:
Traceback (most recent call last):
  File "/home/gijs/prefactor-cwl/.virtualenv/local/lib/python2.7/site-packages/cwltool/main.py", line 818, in main
    skip_schemas=args.skip_schemas)
  File "/home/gijs/prefactor-cwl/.virtualenv/local/lib/python2.7/site-packages/cwltool/load_tool.py", line 214, in validate_document
    _convert_stdstreams_to_files(workflowobj)
  File "/home/gijs/prefactor-cwl/.virtualenv/local/lib/python2.7/site-packages/cwltool/load_tool.py", line 85, in _convert_stdstreams_to_files
    if out.get('type') == streamtype:
AttributeError: 'NoneType' object has no attribute 'get'
```

CWL file
https://github.com/gijzelaerr/prefactor-cwl/blob/master/ndppp_prep_cal.cwl

**Comment by mr-c** [comment]
I've update the original post to reference to the exact file that cause the unhelpful error
