### ISSUE TITLE
cwl-runner --pack is not idempotent

### ISSUE THREAD

**Issue by wgerlach** [common-workflow-language/cwltool#560]
---

## Expected Behavior
Running cwl-runner --pack on an already packed (normalized) cwl workflow should create the same file again.

## Actual Behavior
Id fields do get an additional path "main":
```text
cwl-runner --pack ./v1.0/null-expression1-tool.cwl ./v1.0/null-expression1-job.json > test.txt
cwl-runner --pack test.txt > test2.txt
diff test*
--- test.txt
+++ test2.txt
@@ -9,13 +9,13 @@
         {
             "type": "Any", 
             "default": "the-default", 
-            "id": "#main/i1"
+            "id": "#main/main/i1"
         }
     ], 
     "outputs": [
         {
             "type": "int", 
-            "id": "#main/output"
+            "id": "#main/main/output"
         }
     ], 
     "expression": "$({'output': (inputs.i1 == 'the-default' ? 1 : 2)})", 
```

## Workflow Code
```
See compliance tests
v1.0/null-expression1-tool.cwl

```

## Full Traceback
```pytb
NA
```

## Your Environment
* cwltool version: 1.0.20171017195544
Check using ``cwltool --version``

**Comment by mr-c** [comment]
Thank you @wgerlach for this report; I concur with that this is a bug and this feature should be made to be idempotent.

**Comment by anton-khodak** [comment]
Another error (but the same scope) with running a packed workflow: 
```
Tool definition failed initialization:
Tool file contains graph of multiple objects, must specify one of #main, #wc2-tool.cwl
Traceback (most recent call last):
  File "/Users/anton/Programming/CWL/cwltool/cwltool/main.py", line 841, in main
    makeTool, make_tool_kwds)
  File "/Users/anton/Programming/CWL/cwltool/cwltool/load_tool.py", line 249, in make_tool
    urllib.parse.urldefrag(i["id"])[1] for i in resolveduri
cwltool.errors.WorkflowException: Tool file contains graph of multiple objects, must specify one of #main, #wc2-tool.cwl
```
