### ISSUE TITLE
An execution of a packed workflow fails

### ISSUE THREAD

**Issue by anton-khodak** [common-workflow-language/cwltool#574]
## Expected Behavior
cwltool executes a workflow after packing exactly the same way as a normal workflow.

## Actual Behavior
Workflow fails

## Steps to reproduce
```
cd /path/to/cwltool
cwltool --pack cwltool/schemas/v1.0/v1.0/count-lines6-wf.cwl > cwltool/schemas/v1.0/v1.0/count-lines6-wf-packed.cwl
cwltool  cwltool/schemas/v1.0/v1.0/count-lines6-wf-packed.cwl  cwltool/schemas/v1.0/v1.0/count-lines6-job.json
```

## Full Traceback
```
Resolved 'v1.0/v1.0/count-lines6-wf-packed.cwl' to 'file:///Users/anton/Programming/CWL/cwltool/cwltool/schemas/v1.0/v1.0/count-lines6-wf-packed.cwl'
Tool definition failed initialization:
Tool file contains graph of multiple objects, must specify one of #main, #wc3-tool.cwl
Traceback (most recent call last):
  File "/Users/anton/Programming/CWL/cwltool/cwltool/main.py", line 896, in main
    makeTool, make_tool_kwds)
  File "/Users/anton/Programming/CWL/cwltool/cwltool/load_tool.py", line 291, in make_tool
    urllib.parse.urldefrag(i["id"])[1] for i in resolveduri
cwltool.errors.WorkflowException: Tool file contains graph of multiple objects, must specify one of #main, #wc3-tool.cwl
```

## Your Environment
* cwltool version: 
1.0.20171107131604

**Comment by tetron** [comment]
If should run #main by default.  It used to do that and then was pulled out because it wasn't to spec, but I think it should do that and the spec should be updated.
