### ISSUE TITLE
[Regression] cwltool master does not pass the conformance test for user guide

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/cwltool#663]
cwltool in master branch (commit: 2f4196e2a806102a862caf0c6ea71179297b280c) does not pass the conformance test for [user guide](https://github.com/common-workflow-language/user_guide).
I confirmed pip version (1.0.20180211183944) of cwltool passes the conformance test.

The example of Section 17 fails in the conformance test.

## How to reproduce
```console
$ git clone https://github.com/common-workflow-language/user_guide
$ cd user_guide/_includes/cwl
$ cwltest --tool cwltool -n 12 --test conformance-test.yml
```

## Expected Behavior
The conformance test successfully finishes.

## Actual Behavior
The conformance test fails.

## Full Traceback
```console
/tmp/user_guide/_includes/cwl # cwltest --tool cwltool -n 12 --test conformance-test.yml
Test [12/14]
Test failed: cwltool --outdir=/tmp/tmp_RHzzk --quiet 17-metadata/metadata_example3.cwl 17-metadata/sample.yml
Test for section 17 (extended example)
Returned non-zero
No handlers could be found for logger "rdflib.term"
/usr/lib/python2.7/site-packages/rdflib/plugins/parsers/structureddata.py:30: UserWarning: html5lib not found! RDFa and Microdata parsers will not be available.
  'parsers will not be available.')
Could not load extension schema https://schema.org/docs/schema_org_rdfa.html: html5lib is not installed, cannot use RDFa and Microdata parsers.
17-metadata/metadata_example3.cwl:2:1: unrecognized extension field `https://schema.org/author`.  Did you include a $schemas section?
foreign properties set([u'http://edamontology.org/is_topic_of', u'http://purl.obolibrary.org/obo/edam#obsolete', u'http://edamontology.org/has_output', u'http://edamontology.org/has_topic', u'http://purl.obolibrary.org/obo/edam#operations', u'http://purl.obolibrary.org/obo/edam#edam', u'http://purl.obolibrary.org/obo/edam#topics', u'http://edamontology.org/is_identifier_of', u'http://edamontology.org/is_input_of', u'http://edamontology.org/has_identifier', u'http://edamontology.org/is_function_of', u'http://edamontology.org/is_output_of', u'http://edamontology.org/has_input', u'http://edamontology.org/has_function', u'http://purl.obolibrary.org/obo/edam#identifiers', u'http://edamontology.org/has_format', u'http://www.geneontology.org/formats/oboInOwl#SubsetProperty', u'http://purl.obolibrary.org/obo/edam#data', u'http://purl.obolibrary.org/obo/edam#events', u'http://purl.obolibrary.org/obo/edam#formats', u'http://edamontology.org/is_format_of'])
17-metadata/metadata_example3.cwl:2:1: unrecognized extension field `https://schema.org/contributor`.  Did you include a $schemas section?
foreign properties set([u'http://edamontology.org/is_topic_of', u'http://purl.obolibrary.org/obo/edam#obsolete', u'http://edamontology.org/has_output', u'http://edamontology.org/has_topic', u'http://purl.obolibrary.org/obo/edam#operations', u'http://purl.obolibrary.org/obo/edam#edam', u'http://purl.obolibrary.org/obo/edam#topics', u'http://edamontology.org/is_identifier_of', u'http://edamontology.org/is_input_of', u'http://edamontology.org/has_identifier', u'http://edamontology.org/is_function_of', u'http://edamontology.org/is_output_of', u'http://edamontology.org/has_input', u'http://edamontology.org/has_function', u'http://purl.obolibrary.org/obo/edam#identifiers', u'http://edamontology.org/has_format', u'http://www.geneontology.org/formats/oboInOwl#SubsetProperty', u'http://purl.obolibrary.org/obo/edam#data', u'http://purl.obolibrary.org/obo/edam#events', u'http://purl.obolibrary.org/obo/edam#formats', u'http://edamontology.org/is_format_of'])
17-metadata/metadata_example3.cwl:2:1: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?
foreign properties set([u'http://edamontology.org/is_topic_of', u'http://purl.obolibrary.org/obo/edam#obsolete', u'http://edamontology.org/has_output', u'http://edamontology.org/has_topic', u'http://purl.obolibrary.org/obo/edam#operations', u'http://purl.obolibrary.org/obo/edam#edam', u'http://purl.obolibrary.org/obo/edam#topics', u'http://edamontology.org/is_identifier_of', u'http://edamontology.org/is_input_of', u'http://edamontology.org/has_identifier', u'http://edamontology.org/is_function_of', u'http://edamontology.org/is_output_of', u'http://edamontology.org/has_input', u'http://edamontology.org/has_function', u'http://purl.obolibrary.org/obo/edam#identifiers', u'http://edamontology.org/has_format', u'http://www.geneontology.org/formats/oboInOwl#SubsetProperty', u'http://purl.obolibrary.org/obo/edam#data', u'http://purl.obolibrary.org/obo/edam#events', u'http://purl.obolibrary.org/obo/edam#formats', u'http://edamontology.org/is_format_of'])
17-metadata/metadata_example3.cwl:2:1: unrecognized extension field `https://schema.org/codeRepository`.  Did you include a $schemas section?
foreign properties set([u'http://edamontology.org/is_topic_of', u'http://purl.obolibrary.org/obo/edam#obsolete', u'http://edamontology.org/has_output', u'http://edamontology.org/has_topic', u'http://purl.obolibrary.org/obo/edam#operations', u'http://purl.obolibrary.org/obo/edam#edam', u'http://purl.obolibrary.org/obo/edam#topics', u'http://edamontology.org/is_identifier_of', u'http://edamontology.org/is_input_of', u'http://edamontology.org/has_identifier', u'http://edamontology.org/is_function_of', u'http://edamontology.org/is_output_of', u'http://edamontology.org/has_input', u'http://edamontology.org/has_function', u'http://purl.obolibrary.org/obo/edam#identifiers', u'http://edamontology.org/has_format', u'http://www.geneontology.org/formats/oboInOwl#SubsetProperty', u'http://purl.obolibrary.org/obo/edam#data', u'http://purl.obolibrary.org/obo/edam#events', u'http://purl.obolibrary.org/obo/edam#formats', u'http://edamontology.org/is_format_of'])
17-metadata/metadata_example3.cwl:2:1: unrecognized extension field `https://schema.org/dateCreated`.  Did you include a $schemas section?
foreign properties set([u'http://edamontology.org/is_topic_of', u'http://purl.obolibrary.org/obo/edam#obsolete', u'http://edamontology.org/has_output', u'http://edamontology.org/has_topic', u'http://purl.obolibrary.org/obo/edam#operations', u'http://purl.obolibrary.org/obo/edam#edam', u'http://purl.obolibrary.org/obo/edam#topics', u'http://edamontology.org/is_identifier_of', u'http://edamontology.org/is_input_of', u'http://edamontology.org/has_identifier', u'http://edamontology.org/is_function_of', u'http://edamontology.org/is_output_of', u'http://edamontology.org/has_input', u'http://edamontology.org/has_function', u'http://purl.obolibrary.org/obo/edam#identifiers', u'http://edamontology.org/has_format', u'http://www.geneontology.org/formats/oboInOwl#SubsetProperty', u'http://purl.obolibrary.org/obo/edam#data', u'http://purl.obolibrary.org/obo/edam#events', u'http://purl.obolibrary.org/obo/edam#formats', u'http://edamontology.org/is_format_of'])
17-metadata/metadata_example3.cwl:2:1: unrecognized extension field `https://schema.org/license`.  Did you include a $schemas section?
foreign properties set([u'http://edamontology.org/is_topic_of', u'http://purl.obolibrary.org/obo/edam#obsolete', u'http://edamontology.org/has_output', u'http://edamontology.org/has_topic', u'http://purl.obolibrary.org/obo/edam#operations', u'http://purl.obolibrary.org/obo/edam#edam', u'http://purl.obolibrary.org/obo/edam#topics', u'http://edamontology.org/is_identifier_of', u'http://edamontology.org/is_input_of', u'http://edamontology.org/has_identifier', u'http://edamontology.org/is_function_of', u'http://edamontology.org/is_output_of', u'http://edamontology.org/has_input', u'http://edamontology.org/has_function', u'http://purl.obolibrary.org/obo/edam#identifiers', u'http://edamontology.org/has_format', u'http://www.geneontology.org/formats/oboInOwl#SubsetProperty', u'http://purl.obolibrary.org/obo/edam#data', u'http://purl.obolibrary.org/obo/edam#events', u'http://purl.obolibrary.org/obo/edam#formats', u'http://edamontology.org/is_format_of'])
17-metadata/metadata_example3.cwl:2:1: unrecognized extension field `https://schema.org/keywords`.  Did you include a $schemas section?
foreign properties set([u'http://edamontology.org/is_topic_of', u'http://purl.obolibrary.org/obo/edam#obsolete', u'http://edamontology.org/has_output', u'http://edamontology.org/has_topic', u'http://purl.obolibrary.org/obo/edam#operations', u'http://purl.obolibrary.org/obo/edam#edam', u'http://purl.obolibrary.org/obo/edam#topics', u'http://edamontology.org/is_identifier_of', u'http://edamontology.org/is_input_of', u'http://edamontology.org/has_identifier', u'http://edamontology.org/is_function_of', u'http://edamontology.org/is_output_of', u'http://edamontology.org/has_input', u'http://edamontology.org/has_function', u'http://purl.obolibrary.org/obo/edam#identifiers', u'http://edamontology.org/has_format', u'http://www.geneontology.org/formats/oboInOwl#SubsetProperty', u'http://purl.obolibrary.org/obo/edam#data', u'http://purl.obolibrary.org/obo/edam#events', u'http://purl.obolibrary.org/obo/edam#formats', u'http://edamontology.org/is_format_of'])
17-metadata/metadata_example3.cwl:2:1: unrecognized extension field `https://schema.org/programmingLanguage`.  Did you include a $schemas section?
foreign properties set([u'http://edamontology.org/is_topic_of', u'http://purl.obolibrary.org/obo/edam#obsolete', u'http://edamontology.org/has_output', u'http://edamontology.org/has_topic', u'http://purl.obolibrary.org/obo/edam#operations', u'http://purl.obolibrary.org/obo/edam#edam', u'http://purl.obolibrary.org/obo/edam#topics', u'http://edamontology.org/is_identifier_of', u'http://edamontology.org/is_input_of', u'http://edamontology.org/has_identifier', u'http://edamontology.org/is_function_of', u'http://edamontology.org/is_output_of', u'http://edamontology.org/has_input', u'http://edamontology.org/has_function', u'http://purl.obolibrary.org/obo/edam#identifiers', u'http://edamontology.org/has_format', u'http://www.geneontology.org/formats/oboInOwl#SubsetProperty', u'http://purl.obolibrary.org/obo/edam#data', u'http://purl.obolibrary.org/obo/edam#events', u'http://purl.obolibrary.org/obo/edam#formats', u'http://edamontology.org/is_format_of'])
Got workflow error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cwltool/executors.py", line 97, in run_jobs
    for r in jobiter:
  File "/usr/lib/python2.7/site-packages/cwltool/draft2tool.py", line 337, in job
    builder = self._init_job(job_order, **kwargs)
  File "/usr/lib/python2.7/site-packages/cwltool/process.py", line 622, in _init_job
    checkFormat(builder.job[d], builder.do_eval(i["format"]), self.formatgraph)
  File "/usr/lib/python2.7/site-packages/cwltool/process.py", line 389, in checkFormat
    u"Incompatible file format %s required format(s) %s" % (af["format"], inputFormats))
ValidationException: Incompatible file format http://edamontology.org/format_2572 required format(s) https://edamontology.org/format_2572
Workflow error, try again with --debug for more information:
Incompatible file format http://edamontology.org/format_2572 required format(s) https://edamontology.org/format_2572

0 tests passed, 1 failures, 0 unsupported features
```

## Your Environment
* cwltool version: 
Check using ``cwltool --version``

```console
# cwltool --version
/usr/bin/cwltool 1.0.20180215163414
```

**Comment by mr-c** [comment]
`http` vs `https`, interesting

**Comment by mr-c** [comment]
@tom-tan Do you know which is the last version of `cwltool` & `schema_salad` that didn't exhibit this behavior?

@tetron What do you think about this?

**Comment by tom-tan** [comment]
> Do you know which is the last version of cwltool & schema_salad that didn't exhibit this behavior?

I find that commit 3d7ef753cd5024a111359bc366b291e2a03efc94 introduces this regression.
I used `git bisect` with the following script to find it.

```sh
#!/bin/sh

# issue663.sh

pip install -r requirements.txt
pip install --upgrade .
cd user_guide/_includes/cwl
cwltest --tool cwltool -n 12-15 --test conformance-test.yml
```

## How to reproduce
```
$ git clone git@github.com:common-workflow-language/cwltool.git
$ cd cwltool
$ git@github.com:common-workflow-language/user_guide.git
$ sed -ie 's/edam: http:/edam: https:/' user_guide/_includes/cwl/17-metadata/metadata_example3.cwl
$ git bisect start master d138c1d6ae3cbc28e66cf4137519211e7da60098
$ git bisect run /path/to/issue663.sh
```

**Comment by tom-tan** [comment]
I close this issue because I confirm that cwltool 1.0.20180403145700 (installed via pip) passes the conformance test (I am not sure which commit fixes this issue).

Thanks!
