### ISSUE TITLE
suggestion: "--input-dir" command-line option

### ISSUE THREAD

**Issue by anton-khodak** [common-workflow-language/cwltool#668]
Currently, if the job file `job.json` looks like:
```
{
  "input_file": {
    "class": "File",
    "path": "hello.txt"
  }
}
```
Then `hello.txt` must be in placed in the same directory with `job.json`. With `--input-dir` option one could specify a base path other than the parent directory of `job.json` to resolve file inputs with relative paths. With that, one can place `job.json` and file inputs separately and independently of one another.

**Comment by tetron** [comment]
Try. --basedir

**Comment by anton-khodak** [comment]
@tetron great, thank you. Then I will add a help message for `--basedir`

**Comment by anton-khodak** [comment]
Looks like there is a bug.

cat-tool.cwl:
```
#!/usr/bin/env cwl-runner

class: CommandLineTool
cwlVersion: v1.0

inputs:
  file1: File

outputs:
  output:
    type: File
    outputBinding: { glob: output }

baseCommand: [cat]

stdin: $(inputs.file1.path)
stdout: output
```
cat-job.json
```
{
    "file1": {
        "class": "File",
        "location": "hello.txt"
    }
}
```
`cat-tool` and `cat-job` are in `/Users/anton/Programming/CWL/cwltool/temp/`
command
```
cwltool --basedir /Users/anton/Programming/CWL/common-workflow-language/v1.0/v1.0 cat-tool.cwl cat-job.json
```
output:
```
/Users/anton/.virtualenvs/cwltool-py2/bin/cwltool 1.0.20180220121300
Resolved 'cat-tool.cwl' to 'file:///Users/anton/Programming/CWL/cwltool/temp/cat-tool.cwl'
Got workflow error
Traceback (most recent call last):
  File "/Users/anton/.virtualenvs/cwltool-py2/lib/python2.7/site-packages/cwltool/executors.py", line 97, in run_jobs
    for r in jobiter:
  File "/Users/anton/.virtualenvs/cwltool-py2/lib/python2.7/site-packages/cwltool/draft2tool.py", line 370, in job
    builder.pathmapper = self.makePathMapper(reffiles, builder.stagedir, **make_path_mapper_kwargs)
  File "/Users/anton/.virtualenvs/cwltool-py2/lib/python2.7/site-packages/cwltool/draft2tool.py", line 229, in makePathMapper
    separateDirs=kwargs.get("separateDirs", True))
  File "/Users/anton/.virtualenvs/cwltool-py2/lib/python2.7/site-packages/cwltool/pathmapper.py", line 229, in __init__
    self.setup(dedup(referenced_files), basedir)
  File "/Users/anton/.virtualenvs/cwltool-py2/lib/python2.7/site-packages/cwltool/pathmapper.py", line 282, in setup
    self.visit(fob, stagedir, basedir, copy=fob.get("writable"), staged=True)
  File "/Users/anton/.virtualenvs/cwltool-py2/lib/python2.7/site-packages/cwltool/pathmapper.py", line 271, in visit
    self.visitlisting(obj.get("secondaryFiles", []), stagedir, basedir, copy=copy, staged=staged)
  File "/Users/anton/.virtualenvs/cwltool-py2/lib/python2.7/site-packages/schema_salad/sourceline.py", line 157, in __exit__
    raise self.makeError(six.text_type(exc_value))
ValidationException: cat-job.json:4:9: [Errno 2] No such file or directory: '/Users/anton/Programming/CWL/cwltool/temp/hello.txt'
Workflow error, try again with --debug for more information:
cat-job.json:4:9: [Errno 2] No such file or directory:
                  '/Users/anton/Programming/CWL/cwltool/temp/hello.txt'
```
