### ISSUE TITLE
Using a singularity image

### ISSUE THREAD

**Issue by SpheMakh** [common-workflow-language/cwltool#728]
---

## Expected Behavior
Run software inside a singularity container specified via `DockerRequirement.dockerImageId` using an existing image.

## Actual Behavior
cwltool cannot find the image

## Workflow Code
```
cwlVersion: v1.0
class: CommandLineTool

hints:
  DockerRequirement:
      dockerImageId: gijzelaerr/spiel

baseCommand: [echo, hello]

inputs:
  []

outputs:
  []

```

## Full Traceback
```pytb
sphe@master001:~/spiel$ .virtualenv/bin/cwltool --debug --singularity singularity-run.cwl
.virtualenv/bin/cwltool 1.0.20180403145700
Resolved 'singularity-run.cwl' to 'file:///users/sphe/spiel/singularity-run.cwl'
Parsed job order from command line: {
    "id": "singularity-run.cwl"
}
[job singularity-run.cwl] initializing from file:///users/sphe/spiel/singularity-run.cwl
[job singularity-run.cwl] {}
[job singularity-run.cwl] path mappings is {}
[job singularity-run.cwl] command line bindings is [
    {
        "position": [
            -1000000, 
            0
        ], 
        "datum": "echo"
    }, 
    {
        "position": [
            -1000000, 
            1
        ], 
        "datum": "hello"
    }
]
Singularity error
Traceback (most recent call last):
  File "/users/sphe/spiel/.virtualenv/local/lib/python2.7/site-packages/cwltool/job.py", line 376, in run
    img_id = str(self.get_from_requirements(docker_req, True, pull_image, force_pull=kwargs.get("force_docker_pull")))
  File "/users/sphe/spiel/.virtualenv/local/lib/python2.7/site-packages/cwltool/singularity.py", line 98, in get_from_requirements
    raise WorkflowException(u"Container image %s not found" % r["dockerImageId"])
WorkflowException: Container image gijzelaerr/spiel not found
Workflow error, try again with --debug for more information:
Singularity is not available for this tool, try --no-container to disable Singularity, or install a user space Docker replacement like uDocker with --user-space-docker-cmd.: Container image gijzelaerr/spiel not found
Traceback (most recent call last):
  File "/users/sphe/spiel/.virtualenv/local/lib/python2.7/site-packages/cwltool/main.py", line 606, in main
    **vars(args))
  File "/users/sphe/spiel/.virtualenv/local/lib/python2.7/site-packages/cwltool/executors.py", line 29, in __call__
    return self.execute(*args, **kwargs)
  File "/users/sphe/spiel/.virtualenv/local/lib/python2.7/site-packages/cwltool/executors.py", line 70, in execute
    self.run_jobs(t, job_order_object, logger, **kwargs)
  File "/users/sphe/spiel/.virtualenv/local/lib/python2.7/site-packages/cwltool/executors.py", line 106, in run_jobs
    r.run(**kwargs)
  File "/users/sphe/spiel/.virtualenv/local/lib/python2.7/site-packages/cwltool/job.py", line 397, in run
    "--user-space-docker-cmd.: {1}".format(container, e))
WorkflowException: Singularity is not available for this tool, try --no-container to disable Singularity, or install a user space Docker replacement like uDocker with --user-space-docker-cmd.: Container image gijzelaerr/spiel not found
```

## Your Environment
* cwltool version: 
1.0.2018040314570

**Comment by mr-c** [comment]
Hello @SpheMakh. If you chance `dockerImageId` to `dockerPull` then the issue goes away for me.

**Comment by SpheMakh** [comment]
It works, thanks!
