### ISSUE TITLE
Permission denied: '/var/spool/cwl' while running with singularity

### ISSUE THREAD

**Issue by gijzelaerr** [common-workflow-language/cwltool#752]
while running toil with singularity we run into troubles:

repo: https://github.com/gijzelaerr/spiel/
command: make srun

```
Traceback (most recent call last):
  File "/users/gijs/spiel/.virtualenv/local/lib/python2.7/site-packages/cwltool/executors.py", line 108, in run_jobs
    r.run(**kwargs)
  File "/users/gijs/spiel/.virtualenv/local/lib/python2.7/site-packages/cwltool/job.py", line 404, in run
    runtime = self.create_runtime(env, rm_container, record_container_id, cidfile_dir, cidfile_prefix, **kwargs)
  File "/users/gijs/spiel/.virtualenv/local/lib/python2.7/site-packages/cwltool/singularity.py", line 232, in create_runtime
    self.add_volumes(self.generatemapper, runtime, stage_output=True)
  File "/users/gijs/spiel/.virtualenv/local/lib/python2.7/site-packages/cwltool/singularity.py", line 198, in add_volumes
    shutil.copytree(vol.resolved, vol.target)
  File "/usr/lib/python2.7/shutil.py", line 177, in copytree
    os.makedirs(dst)
  File "/users/gijs/spiel/.virtualenv/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/users/gijs/spiel/.virtualenv/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/var/spool/cwl'
```

**Comment by mr-c** [comment]
Perma-link to the repo: https://github.com/gijzelaerr/spiel/tree/f61c786398b85ed82ce53f87ed2bda922d6db00c
