### ISSUE TITLE
cwltool crashes when run by more than one person on the same host

### ISSUE THREAD

**Issue by drjrm3** [common-workflow-language/cwltool#789]
This issue tracker is for reporting bugs in cwltool (the CWL reference implementation) itself. Please use the [Gitter channel](https://gitter.im/common-workflow-language/common-workflow-language) or [Biostars forum](https://www.biostars.org/) for general questions about using cwltool to create/run workflows or issues not related to cwltool. Don't forget to use cwl tag when posting on Biostars Forum.

If you'd like to report a bug, fill out the template below and provide any extra information that may be useful / related to your problem. Ideally, you create an [a Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) reproducing the problem before opening an issue to ensure it's not caused by something in your code.

Before you submit, please delete this help text above the ---
Thanks!
---

## Expected Behavior
cwltool should run when more than one person on a host have used it.

## Actual Behavior
Instead of running it crashes with

```
[jmichael(BASH)@c-head001]: cwltool
Traceback (most recent call last):
  File "/hpcf/apps/python/install/3.5.2a/bin/cwltool", line 7, in <module>
    from cwltool.main import main
  File "/hpcf/apps/python/install/3.5.2a/lib/python3.5/site-packages/cwltool/main.py", line 18, in <module>
    import schema_salad.validate as validate
  File "/hpcf/apps/python/install/3.5.2a/lib/python3.5/site-packages/schema_salad/__init__.py", line 38, in <module>
    import avro
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/hpcf/apps/python/install/3.5.2a/lib/python3.5/site-packages/past/translation/__init__.py", line 396, in load_module
    if detect_python2(source, self.pathname):
  File "/hpcf/apps/python/install/3.5.2a/lib/python3.5/site-packages/past/translation/__init__.py", line 222, in detect_python2
    with open('/tmp/original_code.py', 'w') as f:
PermissionError: [Errno 13] Permission denied: '/tmp/original_code.py'
[jmichael(BASH)@c-head001]: 
```

## Workflow Code
N/A. Not even a help message shows.

## Full Traceback
```
[jmichael(BASH)@c-head001]: cwltool
Traceback (most recent call last):
  File "/hpcf/apps/python/install/3.5.2a/bin/cwltool", line 7, in <module>
    from cwltool.main import main
  File "/hpcf/apps/python/install/3.5.2a/lib/python3.5/site-packages/cwltool/main.py", line 18, in <module>
    import schema_salad.validate as validate
  File "/hpcf/apps/python/install/3.5.2a/lib/python3.5/site-packages/schema_salad/__init__.py", line 38, in <module>
    import avro
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/hpcf/apps/python/install/3.5.2a/lib/python3.5/site-packages/past/translation/__init__.py", line 396, in load_module
    if detect_python2(source, self.pathname):
  File "/hpcf/apps/python/install/3.5.2a/lib/python3.5/site-packages/past/translation/__init__.py", line 222, in detect_python2
    with open('/tmp/original_code.py', 'w') as f:
PermissionError: [Errno 13] Permission denied: '/tmp/original_code.py'
[jmichael(BASH)@c-head001]: 
```

## Your Environment
* cwltool version: 
version is unable to print.

## Notes:
This is related to https://github.com/common-workflow-language/cwltool/issues/499. The issue is in https://github.com/PythonCharmers/python-future/blob/master/src/past/translation/__init__.py where hardcoding of `/tmp/original_code.py` forces multiple users to attempt to overwrite the same file on multi-tenant servers.

**Comment by mr-c** [comment]
Thank you @drjrm3
Looks like it is time to fork `python-future` and apply https://github.com/PythonCharmers/python-future/pull/335
