### ISSUE TITLE
Having an array of enums as input causes a crash

### ISSUE THREAD

**Issue by anowlcalledjosh** [common-workflow-language/cwltool#821]
## Expected Behavior

Input of an array of enums should behave the same way as an array of strings (as long as the input is valid anyway).

## Actual Behavior

cwltool crashes when an input is an array of enums.

## Workflow Code

`tool.cwl`:

```yaml
cwlVersion: v1.0
class: CommandLineTool
baseCommand: echo
inputs:
  args:
    type:
      - type: array
        items:
          type: enum
          symbols:
            - foo
            - bar
    inputBinding:
      position: 1
outputs: []
```

`job.yml`:

```yaml
args: [foo]
```

## Full Traceback

```pytb
/Users/jh36/venv/bin/cwltool 1.0.20180711112827
Resolved 'tool.cwl' to 'file:///Users/jh36/tool.cwl'
Got workflow error
Traceback (most recent call last):
  File "/Users/jh36/venv/lib/python3.6/site-packages/avro/schema.py", line 493, in __init__
    raise SchemaParseException(fail_msg)
  File "/Users/jh36/venv/lib/python3.6/site-packages/avro/schema.py", line 740, in make_avsc_object
    doc = json_data.get('doc')
  File "/Users/jh36/venv/lib/python3.6/site-packages/avro/schema.py", line 457, in __init__
    self.set_prop('symbols', symbols)
  File "/Users/jh36/venv/lib/python3.6/site-packages/avro/schema.py", line 298, in __init__
    self.set_prop('name', name)
  File "/Users/jh36/venv/lib/python3.6/site-packages/avro/schema.py", line 275, in add_name
    return to_add
avro.schema.SchemaParseException: The name "args3ca4056c-da70-4e57-8a98-3007fe28d209" is already in use.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jh36/venv/lib/python3.6/site-packages/cwltool/executors.py", line 141, in run_jobs
    for job in jobiter:
  File "/Users/jh36/venv/lib/python3.6/site-packages/cwltool/command_line_tool.py", line 373, in job
    builder = self._init_job(job_order, runtimeContext)
  File "/Users/jh36/venv/lib/python3.6/site-packages/cwltool/process.py", line 654, in _init_job
    discover_secondaryFiles=getdefault(runtimeContext.toplevel, False)))
  File "/Users/jh36/venv/lib/python3.6/site-packages/cwltool/builder.py", line 260, in bind_input
    bindings.extend(self.bind_input(f, datum[f["name"]], lead_pos=lead_pos, tail_pos=f["name"], discover_secondaryFiles=discover_secondaryFiles))
  File "/Users/jh36/venv/lib/python3.6/site-packages/cwltool/builder.py", line 231, in bind_input
    avsc = AvroSchemaFromJSONData(t, self.names)
  File "/Users/jh36/venv/lib/python3.6/site-packages/avro/schema.py", line 750, in make_avsc_object
    return MapSchema(values, names, other_props)
  File "/Users/jh36/venv/lib/python3.6/site-packages/avro/schema.py", line 496, in __init__
avro.schema.SchemaParseException: Items schema (CommentedMap([('type', 'enum'), ('symbols', ['foo', 'bar']), ('name', 'args3ca4056c-da70-4e57-8a98-3007fe28d209')])) not a valid Avro schema: The name "args3ca4056c-da70-4e57-8a98-3007fe28d209" is already in use. (known names: ['File', 'File_class', 'Directory', 'Directory_class', 'Any', 'input_record_schema', 'args3ca4056c-da70-4e57-8a98-3007fe28d209', 'outputs_record_schema'])
Workflow error:
Items schema (CommentedMap([('type', 'enum'), ('symbols', ['foo', 'bar']), ('name', 'args3ca4056c-da70-4e57-8a98-3007fe28d209')])) not a valid Avro schema: The name "args3ca4056c-da70-4e57-8a98-3007fe28d209" is already in use. (known names: ['File', 'File_class', 'Directory', 'Directory_class', 'Any', 'input_record_schema', 'args3ca4056c-da70-4e57-8a98-3007fe28d209', 'outputs_record_schema'])
Traceback (most recent call last):
  File "/Users/jh36/venv/lib/python3.6/site-packages/avro/schema.py", line 493, in __init__
    raise SchemaParseException(fail_msg)
  File "/Users/jh36/venv/lib/python3.6/site-packages/avro/schema.py", line 740, in make_avsc_object
    doc = json_data.get('doc')
  File "/Users/jh36/venv/lib/python3.6/site-packages/avro/schema.py", line 457, in __init__
    self.set_prop('symbols', symbols)
  File "/Users/jh36/venv/lib/python3.6/site-packages/avro/schema.py", line 298, in __init__
    self.set_prop('name', name)
  File "/Users/jh36/venv/lib/python3.6/site-packages/avro/schema.py", line 275, in add_name
    return to_add
avro.schema.SchemaParseException: The name "args3ca4056c-da70-4e57-8a98-3007fe28d209" is already in use.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jh36/venv/lib/python3.6/site-packages/cwltool/executors.py", line 141, in run_jobs
    for job in jobiter:
  File "/Users/jh36/venv/lib/python3.6/site-packages/cwltool/command_line_tool.py", line 373, in job
    builder = self._init_job(job_order, runtimeContext)
  File "/Users/jh36/venv/lib/python3.6/site-packages/cwltool/process.py", line 654, in _init_job
    discover_secondaryFiles=getdefault(runtimeContext.toplevel, False)))
  File "/Users/jh36/venv/lib/python3.6/site-packages/cwltool/builder.py", line 260, in bind_input
    bindings.extend(self.bind_input(f, datum[f["name"]], lead_pos=lead_pos, tail_pos=f["name"], discover_secondaryFiles=discover_secondaryFiles))
  File "/Users/jh36/venv/lib/python3.6/site-packages/cwltool/builder.py", line 231, in bind_input
    avsc = AvroSchemaFromJSONData(t, self.names)
  File "/Users/jh36/venv/lib/python3.6/site-packages/avro/schema.py", line 750, in make_avsc_object
    return MapSchema(values, names, other_props)
  File "/Users/jh36/venv/lib/python3.6/site-packages/avro/schema.py", line 496, in __init__
avro.schema.SchemaParseException: Items schema (CommentedMap([('type', 'enum'), ('symbols', ['foo', 'bar']), ('name', 'args3ca4056c-da70-4e57-8a98-3007fe28d209')])) not a valid Avro schema: The name "args3ca4056c-da70-4e57-8a98-3007fe28d209" is already in use. (known names: ['File', 'File_class', 'Directory', 'Directory_class', 'Any', 'input_record_schema', 'args3ca4056c-da70-4e57-8a98-3007fe28d209', 'outputs_record_schema'])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jh36/venv/lib/python3.6/site-packages/cwltool/main.py", line 605, in main
    logger=_logger)
  File "/Users/jh36/venv/lib/python3.6/site-packages/cwltool/executors.py", line 39, in __call__
    return self.execute(*args, **kwargs)
  File "/Users/jh36/venv/lib/python3.6/site-packages/cwltool/executors.py", line 89, in execute
    self.run_jobs(process, job_order_object, logger, runtime_context)
  File "/Users/jh36/venv/lib/python3.6/site-packages/cwltool/executors.py", line 170, in run_jobs
    raise WorkflowException(Text(e))
cwltool.errors.WorkflowException: Items schema (CommentedMap([('type', 'enum'), ('symbols', ['foo', 'bar']), ('name', 'args3ca4056c-da70-4e57-8a98-3007fe28d209')])) not a valid Avro schema: The name "args3ca4056c-da70-4e57-8a98-3007fe28d209" is already in use. (known names: ['File', 'File_class', 'Directory', 'Directory_class', 'Any', 'input_record_schema', 'args3ca4056c-da70-4e57-8a98-3007fe28d209', 'outputs_record_schema'])
```

## Your Environment

* cwltool version: 1.0.20180711112827

**Comment by jmlord** [comment]
I am experiencing the same issue with arrays of enum, version 3.1.20240112164112. I didn't even get to running it, the tool crashed at `cwltool --make-template`. Here is a log :

```
$ cwltool --debug --make-template tools/data/cleanWDPA.cwl 
INFO /usr/bin/cwltool 3.1.20240112164112
INFO Resolved 'tools/data/cleanWDPA.cwl' to 'file:///home/jmlord/code/cwl/tools/data/cleanWDPA.cwl'
ERROR I'm sorry, I couldn't load this CWL file.
The error was:                                                                                                                                                                                                                
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cwltool/main.py", line 1133, in main
    make_template(tool, stdout)
  File "/usr/lib/python3/dist-packages/cwltool/main.py", line 753, in make_template
    generate_input_template(tool),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cwltool/main.py", line 341, in generate_input_template
    value, comment = generate_example_input(inp["type"], inp.get("default", None))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cwltool/main.py", line 203, in generate_example_input
    example, comment = generate_example_input(inptype[0], default)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cwltool/main.py", line 221, in generate_example_input
    first_item = cast(MutableSequence[CWLObjectType], inptype["items"])[0]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3/dist-packages/ruamel/yaml/comments.py", line 927, in __getitem__
    return ordereddict.__getitem__(self, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 0
```

The tool otherwise passes validation with `--validate`
