### ISSUE TITLE
Error while running bcbio workflow

### ISSUE THREAD

**Issue by FarahZKhan** [common-workflow-language/cwltool#828]
## Expected Behavior
The workflow should execute successfully creating RO. 

## Actual Behavior
Workflow fails with the following error: 
`Anonymous file object must have 'contents' and 'basename' fields.`

## Workflow Code

https://github.com/bcbio/test_bcbio_cwl/blob/master/somatic/somatic-workflow/main-somatic.cwl 

## Full Traceback
```pytb
(testing) farahk@4180L-142848-M:~/Documents/conformanceTest-CWLProv/test_bcbio_cwl/somatic/somatic-workflow$ cwltool --provenance ROtest main-somatic.cwl main-somatic-samples.json 
/Users/farahk/Documents/testing/bin/cwltool 1.0.20180702035104
[provenance] Temporary research object: /var/folders/bs/8fyl2nt50252htp1d2ct1rd1g51vtc/T/tmp0f6876w5
Resolved 'main-somatic.cwl' to 'file:///Users/farahk/Documents/conformanceTest-CWLProv/test_bcbio_cwl/somatic/somatic-workflow/main-somatic.cwl'
[provenance] Added packed workflow: workflow/packed.cwl
steps/alignment_to_rec.cwl:26:3: Unknown hint https://www.dnanexus.com/cwl#InputResourceRequirement
steps/prep_align_inputs.cwl:26:3: Unknown hint https://www.dnanexus.com/cwl#InputResourceRequirement
steps/process_alignment.cwl:27:3: Unknown hint https://www.dnanexus.com/cwl#InputResourceRequirement
steps/process_alignment.cwl:83:3: Unknown hint http://arvados.org/cwl#APIRequirement
steps/merge_split_alignments.cwl:26:3: Unknown hint https://www.dnanexus.com/cwl#InputResourceRequirement
steps/prep_samples_to_rec.cwl:26:3: Unknown hint https://www.dnanexus.com/cwl#InputResourceRequirement
steps/prep_samples.cwl:26:3: Unknown hint https://www.dnanexus.com/cwl#InputResourceRequirement
steps/postprocess_alignment_to_rec.cwl:26:3: Unknown hint https://www.dnanexus.com/cwl#InputResourceRequirement
steps/postprocess_alignment.cwl:27:3: Unknown hint https://www.dnanexus.com/cwl#InputResourceRequirement
steps/postprocess_alignment.cwl:54:3: Unknown hint http://arvados.org/cwl#APIRequirement
steps/combine_sample_regions.cwl:27:3: Unknown hint https://www.dnanexus.com/cwl#InputResourceRequirement
steps/combine_sample_regions.cwl:42:3: Unknown hint http://arvados.org/cwl#APIRequirement
steps/batch_for_variantcall.cwl:26:3: Unknown hint https://www.dnanexus.com/cwl#InputResourceRequirement
steps/get_parallel_regions.cwl:26:3: Unknown hint https://www.dnanexus.com/cwl#InputResourceRequirement
steps/variantcall_batch_region.cwl:27:3: Unknown hint https://www.dnanexus.com/cwl#InputResourceRequirement
steps/variantcall_batch_region.cwl:105:3: Unknown hint http://arvados.org/cwl#APIRequirement
steps/variantcall_batch_region.cwl:106:3: Unknown hint http://arvados.org/cwl#RuntimeConstraints
steps/concat_batch_variantcalls.cwl:27:3: Unknown hint https://www.dnanexus.com/cwl#InputResourceRequirement
steps/concat_batch_variantcalls.cwl:42:3: Unknown hint http://arvados.org/cwl#APIRequirement
steps/postprocess_variants.cwl:26:3: Unknown hint https://www.dnanexus.com/cwl#InputResourceRequirement
steps/compare_to_rm.cwl:26:3: Unknown hint https://www.dnanexus.com/cwl#InputResourceRequirement
steps/summarize_vc.cwl:26:3: Unknown hint https://www.dnanexus.com/cwl#InputResourceRequirement
steps/qc_to_rec.cwl:26:3: Unknown hint https://www.dnanexus.com/cwl#InputResourceRequirement
steps/pipeline_summary.cwl:27:3: Unknown hint https://www.dnanexus.com/cwl#InputResourceRequirement
steps/pipeline_summary.cwl:76:3: Unknown hint http://arvados.org/cwl#RuntimeConstraints
steps/multiqc_summary.cwl:26:3: Unknown hint https://www.dnanexus.com/cwl#InputResourceRequirement
[provenance] Finalizing Research Object
[provenance] Generated bagit metadata: /var/folders/bs/8fyl2nt50252htp1d2ct1rd1g51vtc/T/tmp0f6876w5
[provenance] Deleting existing /Users/farahk/Documents/conformanceTest-CWLProv/test_bcbio_cwl/somatic/somatic-workflow/ROtest
[provenance] Research Object saved to /Users/farahk/Documents/conformanceTest-CWLProv/test_bcbio_cwl/somatic/somatic-workflow/ROtest
Traceback (most recent call last):
  File "/Users/farahk/Documents/testing/bin/cwltool", line 11, in <module>
    sys.exit(main())
  File "/Users/farahk/Documents/testing/lib/python3.6/site-packages/cwltool/main.py", line 574, in main
    secret_store=runtimeContext.secret_store)
  File "/Users/farahk/Documents/testing/lib/python3.6/site-packages/cwltool/main.py", line 221, in init_job_order
    basedir=file_uri(str(input_basedir) + "/"))
  File "/Users/farahk/Documents/testing/lib/python3.6/site-packages/cwltool/main.py", line 288, in printdeps
    {"$include", "$schemas", "location"}, loadref)
  File "/Users/farahk/Documents/testing/lib/python3.6/site-packages/cwltool/process.py", line 933, in scandeps
    r.extend(scandeps(base, v, reffields, urlfields, loadref, urljoin=urljoin))
  File "/Users/farahk/Documents/testing/lib/python3.6/site-packages/cwltool/process.py", line 936, in scandeps
    r.extend(scandeps(base, d, reffields, urlfields, loadref, urljoin=urljoin))
  File "/Users/farahk/Documents/testing/lib/python3.6/site-packages/cwltool/process.py", line 939, in scandeps
    normalizeFilesDirs(r)
  File "/Users/farahk/Documents/testing/lib/python3.6/site-packages/cwltool/pathmapper.py", line 82, in normalizeFilesDirs
    visit_class(job, ("File", "Directory"), addLocation)
  File "/Users/farahk/Documents/testing/lib/python3.6/site-packages/cwltool/utils.py", line 234, in visit_class
    visit_class(d, cls, op)
  File "/Users/farahk/Documents/testing/lib/python3.6/site-packages/cwltool/utils.py", line 231, in visit_class
    visit_class(rec[d], cls, op)
  File "/Users/farahk/Documents/testing/lib/python3.6/site-packages/cwltool/utils.py", line 234, in visit_class
    visit_class(d, cls, op)
  File "/Users/farahk/Documents/testing/lib/python3.6/site-packages/cwltool/utils.py", line 229, in visit_class
    op(rec)
  File "/Users/farahk/Documents/testing/lib/python3.6/site-packages/cwltool/pathmapper.py", line 58, in addLocation
    raise validate.ValidationException("Anonymous file object must have 'contents' and 'basename' fields.")
schema_salad.validate.ValidationException: Anonymous file object must have 'contents' and 'basename' fields.
```

## Your Environment
* cwltool version: 
cwltool 1.0.20180702035104
Mac OS High Sierra

**Comment by mr-c** [comment]
I get an error running this without `--provenance`
```
Workflow error, try again with --debug for more information:
Output file path /var/lib/cwl/stg8dc33acf-dc9f-4d14-925c-38c981e754e5/b1-analysis_blocks.bed must be within designated output directory (/var/spool/cwl) or an input file pass through.
```

**Comment by mr-c** [comment]
Perhaps a bug with `--cache`

```
Raw output from /home/mcrusoe/cwltool/bcbio_cache/fe7d3920d9ec92d976f759ec567a0f63/cwl.output.json: {                                                 
    "vc_rec": [                                                                                                                                       
        {                                                                                                                                             
            "analysis": "variant",                                                                                                                    
            "batch_samples": [                                                                                                                        
                "Test2",                                                                                                                              
                "Test1"
            ],                                                                                                                                        
            "config__algorithm__callable_regions": {
                "class": "File",
                "path": "/var/lib/cwl/stgaa41a863-3253-4f23-92a6-2db7d5e3fec0/b1-analysis_blocks.bed"                                                 
            }, 
```

**Comment by FarahZKhan** [comment]
Without `--provenance` I get the following error: 
```
[job variantcall_batch_region] /private/tmp/docker_tmpyvezt3m7$ docker \
    run \
    -i \
    --volume=/private/tmp/docker_tmpyvezt3m7:/private/var/spool/cwl:rw \
    --volume=/private/var/folders/bs/8fyl2nt50252htp1d2ct1rd1g51vtc/T/tmpox99lyni:/tmp:rw \
    --volume=/Users/farahk/Documents/conformanceTest-CWLProv/test_bcbio_cwl/testdata/genomes/hg19/seq/hg19.fa:/private/var/lib/cwl/stga0ddf8ca-0815-424c-98b5-3f382f87575e/hg19.fa:ro \
    --volume=/Users/farahk/Documents/conformanceTest-CWLProv/test_bcbio_cwl/testdata/genomes/hg19/seq/hg19.fa.fai:/private/var/lib/cwl/stga0ddf8ca-0815-424c-98b5-3f382f87575e/hg19.fa.fai:ro \
    --volume=/Users/farahk/Documents/conformanceTest-CWLProv/test_bcbio_cwl/testdata/genomes/hg19/seq/hg19.dict:/private/var/lib/cwl/stga0ddf8ca-0815-424c-98b5-3f382f87575e/hg19.dict:ro \
    --volume=/Users/farahk/Documents/conformanceTest-CWLProv/test_bcbio_cwl/testdata/genomes/hg19/ucsc/hg19.2bit:/private/var/lib/cwl/stgea27fd09-996f-459e-ab07-395ad02778d7/hg19.2bit:ro \
    --volume=/Users/farahk/Documents/conformanceTest-CWLProv/test_bcbio_cwl/testdata/genomes/hg19/snpeff--hg19-wf.tar.gz:/private/var/lib/cwl/stg8ab181d6-f38d-46a2-baf0-651829cba474/snpeff--hg19-wf.tar.gz:ro \
    --volume=/Users/farahk/Documents/conformanceTest-CWLProv/test_bcbio_cwl/testdata/genomes/hg19/variation/dbsnp_132.vcf.gz:/private/var/lib/cwl/stg987d7c21-32d6-460e-a054-dd03be801455/dbsnp_132.vcf.gz:ro \
    --volume=/Users/farahk/Documents/conformanceTest-CWLProv/test_bcbio_cwl/testdata/genomes/hg19/variation/dbsnp_132.vcf.gz.tbi:/private/var/lib/cwl/stg987d7c21-32d6-460e-a054-dd03be801455/dbsnp_132.vcf.gz.tbi:ro \
    --volume=/Users/farahk/Documents/conformanceTest-CWLProv/test_bcbio_cwl/testdata/genomes/hg19/variation/cosmic-v68-hg19.vcf.gz:/private/var/lib/cwl/stg4505dcac-5cdd-411d-b801-0db6e2745a66/cosmic-v68-hg19.vcf.gz:ro \
    --volume=/Users/farahk/Documents/conformanceTest-CWLProv/test_bcbio_cwl/testdata/genomes/hg19/variation/cosmic-v68-hg19.vcf.gz.tbi:/private/var/lib/cwl/stg4505dcac-5cdd-411d-b801-0db6e2745a66/cosmic-v68-hg19.vcf.gz.tbi:ro \
    --volume=/Users/farahk/Documents/conformanceTest-CWLProv/test_bcbio_cwl/testdata/genomes/hg19/coverage/problem_regions/GA4GH/test.bed.gz:/private/var/lib/cwl/stg87011b35-72f2-475a-97c9-de5e4add54eb/test.bed.gz:ro \
    --volume=/Users/farahk/Documents/conformanceTest-CWLProv/test_bcbio_cwl/testdata/genomes/hg19/coverage/problem_regions/GA4GH/test.bed.gz.tbi:/private/var/lib/cwl/stg87011b35-72f2-475a-97c9-de5e4add54eb/test.bed.gz.tbi:ro \
    --volume=/Users/farahk/Documents/conformanceTest-CWLProv/test_bcbio_cwl/testdata/genomes/hg19/coverage/problem_regions/GA4GH/test2.bed.gz:/private/var/lib/cwl/stgaacb2599-568c-438c-b502-e6528a652e90/test2.bed.gz:ro \
    --volume=/Users/farahk/Documents/conformanceTest-CWLProv/test_bcbio_cwl/testdata/genomes/hg19/coverage/problem_regions/GA4GH/test2.bed.gz.tbi:/private/var/lib/cwl/stgaacb2599-568c-438c-b502-e6528a652e90/test2.bed.gz.tbi:ro \
    --volume=/Users/farahk/Documents/conformanceTest-CWLProv/test_bcbio_cwl/testdata/genomes/hg19/rtg--hg19.sdf-wf.tar.gz:/private/var/lib/cwl/stg28d52932-b095-466d-8167-674219da62fa/rtg--hg19.sdf-wf.tar.gz:ro \
    --volume=/private/tmp/docker_tmp3mjq46g2/align/Test1/Test1-sort.bam:/private/var/lib/cwl/stg82abea61-ecc1-4270-b49e-239c8f795983/Test1-sort.bam:ro \
    --volume=/private/tmp/docker_tmp3mjq46g2/align/Test1/Test1-sort.bam.bai:/private/var/lib/cwl/stg82abea61-ecc1-4270-b49e-239c8f795983/Test1-sort.bam.bai:ro \
    --volume=/private/tmp/docker_tmpln2n0af7/align/Test1/Test1-sort-callable_sample.bed:/private/var/lib/cwl/stg39f8080b-3d40-4ca2-9169-919297f272ec/Test1-sort-callable_sample.bed:ro \
    --volume=/private/tmp/docker_tmpav51_6wy/regions/Test1-analysis_blocks.bed:/private/var/lib/cwl/stgb107523c-e2f9-4cff-a503-1a1cd7bfdaa1/Test1-analysis_blocks.bed:ro \
    --workdir=/private/var/spool/cwl \
    --read-only=true \
    --user=1582362444:1793139257 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/private/var/spool/cwl \
    --env=MPLCONFIGDIR=. \
    quay.io/bcbio/bcbio-vc \
    bcbio_nextgen.py \
    runfn \
    variantcall_batch_region \
    cwl \
    sentinel_runtime=cores,2,ram,4096 \
    sentinel_parallel=batch-parallel \
    sentinel_outputs=vrn_file_region,region_block \
    sentinel_inputs=batch_rec:record,region_block:var \
    run_number=0
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 227, in <module>
    runfn.process(kwargs["args"])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/runfn.py", line 58, in process
    out = fn(fnargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 268, in variantcall_batch_region
    return genotype.variantcall_batch_region(*args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 442, in variantcall_batch_region
    [_region_to_coords(r) for r in region_block], out_file)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/gatk.py", line 170, in haplotype_caller
    parallel_gc=_use_spark(num_cores, gatk_type))
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 351, in run_gatk
    cl = fix_missing_spark_user(cl, prog, params)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 151, in fix_missing_spark_user
    user = getpass.getuser()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/getpass.py", line 158, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1582362444'
[job variantcall_batch_region] Job error:
Error validating output record. the `vrn_file_region` field is not valid because
  value is a list, expected File or null
 in {
    "vrn_file_region": [],
    "region_block": []
}
[job variantcall_batch_region] completed permanentFail
[step variantcall_batch_region] completed permanentFail
[workflow variantcall] completed permanentFail
[step variantcall] completed permanentFail
[workflow ] completed permanentFail
```

**Comment by FarahZKhan** [comment]
It runs fine without the `--provenance` flag now. 
So I am back to the initial issue i.e. 
```
Traceback (most recent call last):
  File "/home/ubuntu/cwlprov_testing/bin/cwltool", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/cwlprov_testing/lib/python3.6/site-packages/cwltool/main.py", line 575, in main
    secret_store=runtimeContext.secret_store)
  File "/home/ubuntu/cwlprov_testing/lib/python3.6/site-packages/cwltool/main.py", line 222, in init_job_order
    basedir=file_uri(str(input_basedir) + "/"))
  File "/home/ubuntu/cwlprov_testing/lib/python3.6/site-packages/cwltool/main.py", line 289, in printdeps
    {"$include", "$schemas", "location"}, loadref)
  File "/home/ubuntu/cwlprov_testing/lib/python3.6/site-packages/cwltool/process.py", line 921, in scandeps
    r.extend(scandeps(base, v, reffields, urlfields, loadref, urljoin=urljoin))
  File "/home/ubuntu/cwlprov_testing/lib/python3.6/site-packages/cwltool/process.py", line 924, in scandeps
    r.extend(scandeps(base, d, reffields, urlfields, loadref, urljoin=urljoin))
  File "/home/ubuntu/cwlprov_testing/lib/python3.6/site-packages/cwltool/process.py", line 927, in scandeps
    normalizeFilesDirs(r)
  File "/home/ubuntu/cwlprov_testing/lib/python3.6/site-packages/cwltool/pathmapper.py", line 82, in normalizeFilesDirs
    visit_class(job, ("File", "Directory"), addLocation)
  File "/home/ubuntu/cwlprov_testing/lib/python3.6/site-packages/cwltool/utils.py", line 233, in visit_class
    visit_class(d, cls, op)
  File "/home/ubuntu/cwlprov_testing/lib/python3.6/site-packages/cwltool/utils.py", line 230, in visit_class
    visit_class(rec[d], cls, op)
  File "/home/ubuntu/cwlprov_testing/lib/python3.6/site-packages/cwltool/utils.py", line 233, in visit_class
    visit_class(d, cls, op)
  File "/home/ubuntu/cwlprov_testing/lib/python3.6/site-packages/cwltool/utils.py", line 228, in visit_class
    op(rec)
  File "/home/ubuntu/cwlprov_testing/lib/python3.6/site-packages/cwltool/pathmapper.py", line 58, in addLocation
    raise validate.ValidationException("Anonymous file object must have 'contents' and 'basename' fields.")
```
