### ISSUE TITLE
All of cwltool v1.0 travis tests are suddenly failing today

### ISSUE THREAD

**Issue by SooLee** [common-workflow-language/cwltool#863]
## Expected Behavior
We have been running these CWLs and input json with no problems until yesterday. Suddenly they're failing, when we install a new version of `cwltool`.

## Actual Behavior
```
Tool definition failed initialization:
Syntax error while parsing a flow mapping
  in "file:///home/travis/build/4dn-dcic/pipelines-cwl/tests/test_input_json/hi-c-processing-pairs.input.json", line 1, column 1
expected ',' or '}', but got '<scalar>'
  in "file:///home/travis/build/4dn-dcic/pipelines-cwl/tests/test_input_json/hi-c-processing-pairs.input.json", line 16, column 15
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/cwltool/main.py", line 491, in main
    loadingContext.overrides_list, tool_file_uri)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/cwltool/main.py", line 166, in load_job_order
    job_order_object, _ = loader.resolve_ref(job_order_file, checklinks=False)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 572, in resolve_ref
    doc = self.fetch(doc_url, inject_ids=(not mixin))
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/schema_salad/sourceline.py", line 164, in __exit__
    raise self.makeError(six.text_type(exc_value))
RuntimeError: Syntax error while parsing a flow mapping
  in "file:///home/travis/build/4dn-dcic/pipelines-cwl/tests/test_input_json/hi-c-processing-pairs.input.json", line 1, column 1
expected ',' or '}', but got '<scalar>'
  in "file:///home/travis/build/4dn-dcic/pipelines-cwl/tests/test_input_json/hi-c-processing-pairs.input.json", line 16, column 15
Traceback (most recent call last):
  File "/home/travis/build/4dn-dcic/pipelines-cwl/tests/json_null_test.py", line 9, in <module>
    s = json.load(sys.stdin)
  File "/opt/python/2.7.14/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/opt/python/2.7.14/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/python/2.7.14/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/python/2.7.14/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

## Workflow Code
The input json file `file:///home/travis/build/4dn-dcic/pipelines-cwl/tests/test_input_json/hi-c-processing-pairs.input.json` looks as below
```
{ 
    "chromsizes": {
        "class": "File", 
        "path": "../test_files/hg38.mainonly.chrom.sizes"
    }, 
    "input_pairs": [
        {
            "class": "File", 
            "path": "../test_files/test2.pairs.gz"
        }
    ], 
    "restriction_file": {
        "class": "File", 
        "path": "../test_files/hg38_HindIII_new.+chr.txt"
    },
    "nthreads":1,
    "min_res":500000,
    "custom_res": "500000,1000000,2000000",
    "maxmem":"2g",
    "chunksize":10000000,
    "mapqfilter_juicer": 30
}
```

## Your Environment
* cwltool version: v1.0

**Comment by tetron** [comment]
The timing is suspicious, this might be #861, an interim fix is in the works.

**Comment by mr-c** [comment]
A release that fixes this has been released. Thank you @SooLee for your report!
