### ISSUE TITLE
File handles are leaked with --parallel

### ISSUE THREAD

**Issue by sersorrel** [common-workflow-language/cwltool#888]
cwltool fails with tracebacks like this on very large workflows when using `--parallel`:

```pytb
Failed to evaluate expression:
Expression evaluation error:
[Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/ubuntu/cwltool/cwltool/expression.py", line 293, in do_eval
    strip_whitespace=strip_whitespace)
  File "/home/ubuntu/cwltool/cwltool/expression.py", line 231, in interpolate
    debug=debug, js_console=js_console)
  File "/home/ubuntu/cwltool/cwltool/expression.py", line 196, in evaluator
    debug=debug, js_console=js_console)
  File "/home/ubuntu/cwltool/cwltool/sandboxjs.py", line 334, in execjs
    fn, timeout=timeout, js_console=js_console, force_docker_pull=force_docker_pull, debug=debug)
  File "/home/ubuntu/cwltool/cwltool/sandboxjs.py", line 161, in exec_js_process
    new_proc = new_js_proc(js_engine_code, force_docker_pull=force_docker_pull)
  File "/home/ubuntu/cwltool/cwltool/sandboxjs.py", line 86, in new_js_proc
    dockerimgs = subprocess.check_output(["docker", "images", "-q", nodeimg]).decode('utf-8')
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 667, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/usr/lib/python3.6/subprocess.py", line 1177, in _get_handles
    c2pread, c2pwrite = os.pipe()
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cwltool/cwltool/command_line_tool.py", line 91, in run
    ev = self.builder.do_eval(self.script)
  File "/home/ubuntu/cwltool/cwltool/builder.py", line 424, in do_eval
    strip_whitespace=strip_whitespace)
  File "/home/ubuntu/cwltool/cwltool/expression.py", line 296, in do_eval
    raise WorkflowException("Expression evaluation error:\n%s" % e)
cwltool.errors.WorkflowException: Expression evaluation error:
[Errno 24] Too many open files
```

Originally I thought this was caused by #842, because that would stop the spawned processes from going out of scope and therefore stop the pipes being destroyed, but I can reproduce this on cwltool version 1.0.20180721142728, which was before that change.

`lsof` indicates that the problem is definitely that pipes are being left open:

```console
$ ulimit -n
1024
$ lsof -nPc cwltool | tail
cwltool 8788 ubuntu 1010r     FIFO   0,12      0t0 17470325 pipe
cwltool 8788 ubuntu 1011w     FIFO   0,12      0t0 17470442 pipe
cwltool 8788 ubuntu 1012r     FIFO   0,12      0t0 17471664 pipe
cwltool 8788 ubuntu 1013w     FIFO   0,12      0t0 17470413 pipe
cwltool 8788 ubuntu 1014w     FIFO   0,12      0t0 17471664 pipe
cwltool 8788 ubuntu 1016w     FIFO   0,12      0t0 17470465 pipe
cwltool 8788 ubuntu 1019w     FIFO   0,12      0t0 17470315 pipe
cwltool 8788 ubuntu 1021r     FIFO   0,12      0t0 17470316 pipe
cwltool 8788 ubuntu 1022w     FIFO   0,12      0t0 17470316 pipe
cwltool 8788 ubuntu 1023w     FIFO   0,12      0t0 17470325 pipe
```

Maybe the processes in `cwltool.sandboxjs.localdata` aren't getting properly garbage-collected when the thread dies? But this example would seem to show that that's not how CPython behaves:

```python
import time
import threading

localdata = threading.local()

class Node(object):
    def __init__(self):
        self.name = threading.currentThread().name
        print('  new node process on %s' % self.name)

    def __del__(self):
        print('  __del__ for node process on %s' % self.name)

def access_thlocal():
    if not hasattr(localdata, "procs"):
        localdata.procs = {}
    print("started thread {}".format(threading.current_thread().name))
    localdata.procs["foo"] = Node()

for i in range(0, 10):
    threading.Thread(target=access_thlocal).start()
time.sleep(1)
```

which results in this output:

```
started thread Thread-1
  new node process on Thread-1
  __del__ for node process on Thread-1
started thread Thread-2
  new node process on Thread-2
  __del__ for node process on Thread-2
started thread Thread-3
  new node process on Thread-3
  __del__ for node process on Thread-3
started thread Thread-4
  new node process on Thread-4
  __del__ for node process on Thread-4
started thread Thread-5
  new node process on Thread-5
  __del__ for node process on Thread-5
started thread Thread-6
  new node process on Thread-6
  __del__ for node process on Thread-6
started thread Thread-7
  new node process on Thread-7
  __del__ for node process on Thread-7
started thread Thread-8
  new node process on Thread-8
  __del__ for node process on Thread-8
started thread Thread-9
  new node process on Thread-9
  __del__ for node process on Thread-9
started thread Thread-10
  new node process on Thread-10
  __del__ for node process on Thread-10
```

Presumably something else is keeping a reference to the Node.js processes and stopping them from being destroyed...

**Comment by tetron** [comment]
A little confused by your last comment with the patches, I think you're saying those are things you tried but it didn't solve the problem?

I wonder if a solution would be to fix the --parallel implementation to use a thread pool, so the threads (and the associated Node.js processes) get recycled.  This would also avoid the overhead of starting lots of new Node.js processes.

**Comment by anowlcalledjosh** [comment]
Yes, sorry, I was trying a few things but none of them fixed it.

**Comment by jfouret** [comment]
Hi,

Concerning the file handle, on system-side I was able to fix it using `ulimit -n 1048576`. However you need to be sudo to do that. And because it's a limitation linked to the kernel you cannot extend it within a container.

However, at some point, a new error was raised:

```
[2020-11-12 20:54:43] INFO [job fastqc_198] Max memory used: 6543MiB
[2020-11-12 20:54:43] ERROR filedescriptor out of range in select()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cwltool/expression.py", line 397, in do_eval
    else 2,
  File "/usr/local/lib/python3.6/dist-packages/cwltool/expression.py", line 301, in interpolate
    js_console=js_console,
  File "/usr/local/lib/python3.6/dist-packages/cwltool/expression.py", line 256, in evaluator
    js_console=js_console,
  File "/usr/local/lib/python3.6/dist-packages/cwltool/sandboxjs.py", line 362, in execjs
    fn, timeout, js_console=js_console, force_docker_pull=force_docker_pull
  File "/usr/local/lib/python3.6/dist-packages/cwltool/sandboxjs.py", line 305, in exec_js_process
    rready, wready, _ = select.select(rselect, wselect, [])
ValueError: filedescriptor out of range in select()
[2020-11-12 20:54:43] ERROR [job fastqc_198] Job error:
```
This post suggest using a `poll` in place of a `select` to fix the problem: https://stackoverflow.com/questions/7695701/filedescriptor-out-of-range-in-select-when-using-pythons-subprocess-with-rs

**Comment by tetron** [comment]
@sersorrel @jfouret could you see if pull request #1367 fixes this for you?

**Comment by mr-c** [comment]
We believe this was fixed in https://github.com/common-workflow-language/cwltool/pull/1367 . Please feel free to reopen this issue and leave a comment if the problem persists.
