### ISSUE TITLE
Some ext tests fail on Windows

### ISSUE THREAD

**Issue by psafont** [common-workflow-language/cwltool#890]
There are 2 types of non-transient failures on Windows using Docker:
- Problems to overwrite a file, on `test_write_write_conflict`\[[log](https://ci.commonwl.org/blue/organizations/jenkins/cwltool/detail/PR-850/20/pipeline/#step-19-log-455)\] the file doesn't get updated, on `test_double_overwrite`\[[log](https://ci.commonwl.org/blue/organizations/jenkins/cwltool/detail/PR-850/18/pipeline/#step-19-log-92)\] it only gets updated once.
- Problems to create folders on `test_disable_dir_overwrite_without_ext`:
```
Error collecting output for parameter 'out':
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3: Traceback (most recent call last):
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3: 
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3:   File "c:\jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\cwltool\command_line_tool.py", line 601, in collect_output_ports
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3:     compute_checksum=compute_checksum)
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3: 
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3:   File "c:\jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\cwltool\command_line_tool.py", line 766, in collect_output
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3:     adjustFileObjs(r, revmap)
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3: 
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3:   File "c:\jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\cwltool\pathmapper.py", line 46, in adjustFileObjs
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3:     visit_class(rec, ("File",), op)
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3: 
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3:   File "c:\jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\cwltool\utils.py", line 210, in visit_class
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3:     visit_class(rec[d], cls, op)
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3: 
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3:   File "c:\jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\cwltool\utils.py", line 213, in visit_class
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3:     visit_class(d, cls, op)
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3: 
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3:   File "c:\jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\cwltool\utils.py", line 208, in visit_class
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3:     op(rec)
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3: 
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3:   File "c:\jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\cwltool\command_line_tool.py", line 165, in revmap_file
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3:     u"file pass through." % (path, builder.outdir))
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3: 
C:jenkins\workspace\cwltool_PR-850-5IQF7Z2DEV6462R5RK5SND5K4PBWDJ6EGRCQUCWDYNLCK5KY67ZA\tests\wf\updatedir.cwl:13:3: cwltool.errors.WorkflowException: Output file path C:/Users/Dan/AppData/Local/Temp/tmpwjra_6lk/inp/blurb must be within designated output directory (/var/spool/cwl) or an input file pass through.
```

**Comment by mr-c** [comment]
We no longer support running in MS Windows, but we do support running in the Windows Subsystem for Linux 2: https://github.com/common-workflow-language/cwltool#ms-windows-users
