### ISSUE TITLE
Error when workflow calls tool w/custom type twice

### ISSUE THREAD

**Issue by johnbradley** [common-workflow-language/cwltool#907]
## Expected Behavior
Users should be able to validate/run workflows that use tools with custom types.

## Actual Behavior
Running command: 
```
cwltool --validate myworkflow.cwl
```
Results in this error:
```
I'm sorry, I couldn't load this CWL file, try again with --debug for more information.
The error was: Expected CommentedMap or CommentedSeq, got <type 'list'>: 
`[u'file:///private/tmp/bugtest/mytypes.yml#table_type/item1', 
u'file:///private/tmp/bugtest/mytypes.yml#table_type/item2']`
```

## Workflow Code
File: `myworkflow.yml`
```
cwlVersion: v1.0
class: Workflow
requirements:
  - $import: mytypes.yml
inputs:
  table_type:
    type: mytypes.yml#table_type
outputs: []
steps:
  first_time:
    run: mytool.cwl
    in:
      table_type: table_type
    out: []
  second_time:
    run: mytool.cwl
    in:
      table_type: table_type
    out: []
```

## Tool Code
File: `mytool.yml`
```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: echo
requirements:
  - $import: mytypes.yml
inputs:
  table_type:
    type: mytypes.yml#table_type
outputs: []
```

## Custom Types
File: `mytypes.yml`
```
class: SchemaDefRequirement
types:
  - name: table_type
    type: enum
    symbols:
      - item1
      - item2
```

## Full Traceback
```pytb
Traceback (most recent call last):
  File "/private/tmp/bugtest/env/lib/python2.7/site-packages/cwltool/main.py", line 605, in main
    metadata, uri, loadingContext)
  File "/private/tmp/bugtest/env/lib/python2.7/site-packages/cwltool/load_tool.py", line 346, in make_tool
    tool = loadingContext.construct_tool_object(processobj, loadingContext)
  File "/private/tmp/bugtest/env/lib/python2.7/site-packages/cwltool/workflow.py", line 54, in default_make_tool
    return Workflow(toolpath_object, loadingContext)
  File "/private/tmp/bugtest/env/lib/python2.7/site-packages/cwltool/workflow.py", line 531, in __init__
    loadingContext.prov_obj))
  File "/private/tmp/bugtest/env/lib/python2.7/site-packages/cwltool/workflow.py", line 619, in __init__
    toolpath_object["run"], loadingContext)
  File "/private/tmp/bugtest/env/lib/python2.7/site-packages/cwltool/load_tool.py", line 372, in load_tool
    metadata=loadingContext.metadata)
  File "/private/tmp/bugtest/env/lib/python2.7/site-packages/cwltool/load_tool.py", line 284, in validate_document
    workflowobj, fileuri, checklinks=do_validate)
  File "/private/tmp/bugtest/env/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 873, in resolve_all
    val, base_url+subscope, file_base=file_base, checklinks=False)
  File "/private/tmp/bugtest/env/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 903, in resolve_all
    val, base_url, file_base=file_base, checklinks=False)
  File "/private/tmp/bugtest/env/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 873, in resolve_all
    val, base_url+subscope, file_base=file_base, checklinks=False)
  File "/private/tmp/bugtest/env/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 903, in resolve_all
    val, base_url, file_base=file_base, checklinks=False)
  File "/private/tmp/bugtest/env/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 873, in resolve_all
    val, base_url+subscope, file_base=file_base, checklinks=False)
  File "/private/tmp/bugtest/env/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 814, in resolve_all
    raise Exception("Expected CommentedMap or CommentedSeq, got %s: `%s`" % (type(document), document))
```

## Your Environment
macOS Sierra 10.12.6
Python 2.7.14
cwltool  1.0.20180912090223

## NOTES
I tested with the previous cwltool version(1.0.20180906112546) and I didn't have this issue.
 If I install the previous version then install the latest version you don't have this problem.
This problem seems to be related to `ruamel.yaml==0.15.66`. If you have `ruamel.yaml==0.15.51` it works fine.

**Comment by mr-c** [comment]
Thank you @johnbradley , the `ruamel.yaml` version has been capped at 0.15.51 in the latest cwltool release: 1.0.20180923172926
