### ISSUE TITLE
schema_salad.validate.ValidationException when subworkflow contains SchemaDefRequirement

### ISSUE THREAD

**Issue by jeremiahsavage** [common-workflow-language/cwltool#909]
The most recent release (1.0.20180912090223) of cwltool fails on the below workflow, while the prior release (1.0.20180906112546) succeeds.

1.0.20180912090223:
```
$ git clone https://github.com/jeremiahsavage/cwl-schemadef-subworkflow.git
$ cd cwl-schemadef-subworkflow
$ cwltool --debug transform.cwl transform.yml
/home/jeremiah/.virtualenvs/cwl20180912090223/bin/cwltool 1.0.20180912090223
Resolved 'transform.cwl' to 'file:///home/jeremiah/cwl-schemadef-subworkflow/transform.cwl'
Validation exception
Traceback (most recent call last):
  File "/home/jeremiah/.virtualenvs/cwl20180912090223/lib/python3.6/site-packages/cwltool/workflow.py", line 619, in __init__
    toolpath_object["run"], loadingContext)
  File "/home/jeremiah/.virtualenvs/cwl20180912090223/lib/python3.6/site-packages/cwltool/load_tool.py", line 372, in load_tool
    metadata=loadingContext.metadata)
  File "/home/jeremiah/.virtualenvs/cwl20180912090223/lib/python3.6/site-packages/cwltool/load_tool.py", line 284, in validate_document
    workflowobj, fileuri, checklinks=do_validate)
  File "/home/jeremiah/.virtualenvs/cwl20180912090223/lib/python3.6/site-packages/schema_salad/ref_resolver.py", line 919, in resolve_all
    self.validate_links(document, u"", all_doc_ids)
  File "/home/jeremiah/.virtualenvs/cwl20180912090223/lib/python3.6/site-packages/schema_salad/ref_resolver.py", line 1091, in validate_links
    raise errors[0]
schema_salad.validate.ValidationException: fastq_clean_pe.cwl:5:1: checking field `requirements`
fastq_clean_pe.cwl:7:5:   checking item
fastq_clean_pe.cwl:8:5:     checking field `types`
fastq_clean_pe.cwl:9:9:       checking object `readgroup_meta_type`
readgroup.yml:3:5:         checking field `fields`
readgroup.yml:3:5:           checking object `DS`
readgroup.yml:7:9:             `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:           checking object `DT`
readgroup.yml:9:9:             `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:           checking object `FO`
readgroup.yml:11:9:             `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:           checking object `KS`
readgroup.yml:15:9:             `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:           checking object `PI`
readgroup.yml:19:9:             `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:           checking object `PM`
readgroup.yml:23:9:             `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:           checking object `PU`
readgroup.yml:25:9:             `type` field is list, expected string, list, or a dict.
fastq_clean_pe.cwl:9:9:       checking object `readgroup_fastq_pe_file`
readgroup.yml:31:5:         checking field `fields`
readgroup.yml:31:5:           checking object `readgroup_meta_pe_file`
readgroup.yml:37:9:             Field `type` references unknown identifier `readgroup_meta_type`, tried readgroup_meta_pe_file#readgroup_meta_type
Tool definition failed initialization:
Tool definition file:///home/jeremiah/cwl-schemadef-subworkflow/fastq_clean_pe.cwl failed validation:
fastq_clean_pe.cwl:5:1:   checking field `requirements`
fastq_clean_pe.cwl:7:5:     checking item
fastq_clean_pe.cwl:8:5:       checking field `types`
fastq_clean_pe.cwl:9:9:         checking object `readgroup_meta_type`
readgroup.yml:3:5:           checking field `fields`
readgroup.yml:3:5:             checking object `DS`
readgroup.yml:7:9:               `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:             checking object `DT`
readgroup.yml:9:9:               `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:             checking object `FO`
readgroup.yml:11:9:               `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:             checking object `KS`
readgroup.yml:15:9:               `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:             checking object `PI`
readgroup.yml:19:9:               `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:             checking object `PM`
readgroup.yml:23:9:               `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:             checking object `PU`
readgroup.yml:25:9:               `type` field is list, expected string, list, or a dict.
fastq_clean_pe.cwl:9:9:         checking object `readgroup_fastq_pe_file`
readgroup.yml:31:5:           checking field `fields`
readgroup.yml:31:5:             checking object `readgroup_meta_pe_file`
readgroup.yml:37:9:               Field `type` references unknown identifier `readgroup_meta_type`, tried readgroup_meta_pe_file#readgroup_meta_type
Traceback (most recent call last):
  File "/home/jeremiah/.virtualenvs/cwl20180912090223/lib/python3.6/site-packages/cwltool/workflow.py", line 619, in __init__
    toolpath_object["run"], loadingContext)
  File "/home/jeremiah/.virtualenvs/cwl20180912090223/lib/python3.6/site-packages/cwltool/load_tool.py", line 372, in load_tool
    metadata=loadingContext.metadata)
  File "/home/jeremiah/.virtualenvs/cwl20180912090223/lib/python3.6/site-packages/cwltool/load_tool.py", line 284, in validate_document
    workflowobj, fileuri, checklinks=do_validate)
  File "/home/jeremiah/.virtualenvs/cwl20180912090223/lib/python3.6/site-packages/schema_salad/ref_resolver.py", line 919, in resolve_all
    self.validate_links(document, u"", all_doc_ids)
  File "/home/jeremiah/.virtualenvs/cwl20180912090223/lib/python3.6/site-packages/schema_salad/ref_resolver.py", line 1091, in validate_links
    raise errors[0]
schema_salad.validate.ValidationException: fastq_clean_pe.cwl:5:1: checking field `requirements`
fastq_clean_pe.cwl:7:5:   checking item
fastq_clean_pe.cwl:8:5:     checking field `types`
fastq_clean_pe.cwl:9:9:       checking object `readgroup_meta_type`
readgroup.yml:3:5:         checking field `fields`
readgroup.yml:3:5:           checking object `DS`
readgroup.yml:7:9:             `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:           checking object `DT`
readgroup.yml:9:9:             `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:           checking object `FO`
readgroup.yml:11:9:             `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:           checking object `KS`
readgroup.yml:15:9:             `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:           checking object `PI`
readgroup.yml:19:9:             `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:           checking object `PM`
readgroup.yml:23:9:             `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:           checking object `PU`
readgroup.yml:25:9:             `type` field is list, expected string, list, or a dict.
fastq_clean_pe.cwl:9:9:       checking object `readgroup_fastq_pe_file`
readgroup.yml:31:5:         checking field `fields`
readgroup.yml:31:5:           checking object `readgroup_meta_pe_file`
readgroup.yml:37:9:             Field `type` references unknown identifier `readgroup_meta_type`, tried readgroup_meta_pe_file#readgroup_meta_type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeremiah/.virtualenvs/cwl20180912090223/lib/python3.6/site-packages/cwltool/main.py", line 605, in main
    metadata, uri, loadingContext)
  File "/home/jeremiah/.virtualenvs/cwl20180912090223/lib/python3.6/site-packages/cwltool/load_tool.py", line 346, in make_tool
    tool = loadingContext.construct_tool_object(processobj, loadingContext)
  File "/home/jeremiah/.virtualenvs/cwl20180912090223/lib/python3.6/site-packages/cwltool/workflow.py", line 54, in default_make_tool
    return Workflow(toolpath_object, loadingContext)
  File "/home/jeremiah/.virtualenvs/cwl20180912090223/lib/python3.6/site-packages/cwltool/workflow.py", line 531, in __init__
    loadingContext.prov_obj))
  File "/home/jeremiah/.virtualenvs/cwl20180912090223/lib/python3.6/site-packages/cwltool/workflow.py", line 625, in __init__
    (toolpath_object["run"], validate.indent(str(vexc))))
cwltool.errors.WorkflowException: Tool definition file:///home/jeremiah/cwl-schemadef-subworkflow/fastq_clean_pe.cwl failed validation:
fastq_clean_pe.cwl:5:1:   checking field `requirements`
fastq_clean_pe.cwl:7:5:     checking item
fastq_clean_pe.cwl:8:5:       checking field `types`
fastq_clean_pe.cwl:9:9:         checking object `readgroup_meta_type`
readgroup.yml:3:5:           checking field `fields`
readgroup.yml:3:5:             checking object `DS`
readgroup.yml:7:9:               `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:             checking object `DT`
readgroup.yml:9:9:               `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:             checking object `FO`
readgroup.yml:11:9:               `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:             checking object `KS`
readgroup.yml:15:9:               `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:             checking object `PI`
readgroup.yml:19:9:               `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:             checking object `PM`
readgroup.yml:23:9:               `type` field is list, expected string, list, or a dict.
readgroup.yml:3:5:             checking object `PU`
readgroup.yml:25:9:               `type` field is list, expected string, list, or a dict.
fastq_clean_pe.cwl:9:9:         checking object `readgroup_fastq_pe_file`
readgroup.yml:31:5:           checking field `fields`
readgroup.yml:31:5:             checking object `readgroup_meta_pe_file`
readgroup.yml:37:9:               Field `type` references unknown identifier `readgroup_meta_type`, tried readgroup_meta_pe_file#readgroup_meta_type
(cwl20180912090223) [jeremiah@localhost cwl-schemadef-subworkflow]$ 
```

1.0.20180906112546:
```
$ cwltool transform.cwl transform.yml 
/home/jeremiah/.virtualenvs/cwl20180906112546/bin/cwltool 1.0.20180906112546
Resolved 'transform.cwl' to 'file:///home/jeremiah/cwl-schemadef-subworkflow/transform.cwl'
[workflow ] start
[workflow ] starting step fastq_clean_pe
[step fastq_clean_pe] start
[workflow fastq_clean_pe] start
[workflow fastq_clean_pe] starting step fastq_cleaner_pe
[step fastq_cleaner_pe] start
['docker', 'pull', 'alpine']
Using default tag: latest
Trying to pull repository docker.io/library/alpine ... 
sha256:621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528: Pulling from docker.io/library/alpine
Digest: sha256:621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528
Status: Image is up to date for docker.io/alpine:latest
[job fastq_cleaner_pe] /tmp/tmp7lwn0_kc$ docker \
    run \
    -i \
    --volume=/tmp/tmp7lwn0_kc:/var/spool/cwl:rw \
    --volume=/tmp/tmpoxltf5zu:/tmp:rw \
    --volume=/home/jeremiah/cwl-schemadef-subworkflow/L001_R1_001.fastq.gz:/var/lib/cwl/stgd7d52eab-c4c3-4fdb-b402-5e6695e7251a/L001_R1_001.fastq.gz:ro \
    --volume=/home/jeremiah/cwl-schemadef-subworkflow/L001_R2_001.fastq.gz:/var/lib/cwl/stg7674ce9c-378b-4dad-8190-4fd1b3105e3f/L001_R2_001.fastq.gz:ro \
    --workdir=/var/spool/cwl \
    --read-only=true \
    --user=1000:1000 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/var/spool/cwl \
    alpine \
    touch \
    fastq1 \
    fastq2
[job fastq_cleaner_pe] completed success
[step fastq_cleaner_pe] completed success
[workflow fastq_clean_pe] completed success
[step fastq_clean_pe] completed success
[workflow ] completed success
{}
Final process status is success
$ 
```

**Comment by jeremiahsavage** [comment]
with the most recent version of cwltool, this issue no longer occurs.
```
(cwl) [jeremiah@localhost cwl-schemadef-subworkflow]$ cwltool transform.cwl transform.yml
/home/jeremiah/.virtualenvs/cwl/bin/cwltool 1.0.20181012180214
Resolved 'transform.cwl' to 'file:///home/jeremiah/cwl-schemadef-subworkflow/transform.cwl'
[workflow ] start
[workflow ] starting step fastq_clean_pe
[step fastq_clean_pe] start
[workflow fastq_clean_pe] start
[workflow fastq_clean_pe] starting step fastq_cleaner_pe
[step fastq_cleaner_pe] start
['docker', 'pull', 'alpine']
Using default tag: latest
Trying to pull repository docker.io/library/alpine ... 
sha256:621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528: Pulling from docker.io/library/alpine
Digest: sha256:621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528
Status: Image is up to date for docker.io/alpine:latest
[job fastq_cleaner_pe] /tmp/tmpoijpqhxv$ docker \
    run \
    -i \
    --volume=/tmp/tmpoijpqhxv:/mrEDED:rw \
    --volume=/tmp/tmp_sorkhs7:/tmp:rw \
    --volume=/home/jeremiah/cwl-schemadef-subworkflow/L001_R1_001.fastq.gz:/var/lib/cwl/stgb08cb6b1-59e2-47c7-b1d9-e3702a36dcec/L001_R1_001.fastq.gz:ro \
    --volume=/home/jeremiah/cwl-schemadef-subworkflow/L001_R2_001.fastq.gz:/var/lib/cwl/stg23d949db-6bf7-4280-8be4-d08e65c86e34/L001_R2_001.fastq.gz:ro \
    --workdir=/mrEDED \
    --read-only=true \
    --user=1000:1000 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/mrEDED \
    alpine \
    touch \
    fastq1 \
    fastq2
[job fastq_cleaner_pe] completed success
[step fastq_cleaner_pe] completed success
[workflow fastq_clean_pe] completed success
[step fastq_clean_pe] completed success
[workflow ] completed success
{}
Final process status is success
```

**Comment by mr-c** [comment]
@jeremiahsavage Thanks for the update!
