### ISSUE TITLE
CWLProv: needs to add running the conformance test to regular testing

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#916]
- [ ] add `./run_test.sh RUNNER=cwltool EXTRA="--provenance $PWD/RO_test"` to ci.commonwl.org

--- 

- [ ] 55 "Test InitialWorkDirRequirement linking input files and capturing secondaryFiles on input and output. Also tests the use of a variety of parameter references  and expressions in the secondaryFiles field. "
- [ ] 87 "Test directories in secondaryFiles" 
- [ ] 118 Test empty writable dir with InitialWorkDirRequirement inside Docker
```
Traceback (most recent call last):                             
  File "/home/mcrusoe/cwltool/cwltool/executors.py", line 167, in run_jobs
    job.run(runtime_context)                                                                 
  File "/home/mcrusoe/cwltool/cwltool/job.py", line 498, in run                                                                                       
    self._execute(runtime, env, runtimeContext)                                                                                                       
  File "/home/mcrusoe/cwltool/cwltool/job.py", line 332, in _execute                                                                                  
    outputs, runtimeContext.process_run_id, str(self.name))                                                                                            
  File "/home/mcrusoe/cwltool/cwltool/provenance.py", line 839, in generate_output_prov                                                               
    entity = self.declare_artefact(value)                                      
  File "/home/mcrusoe/cwltool/cwltool/provenance.py", line 736, in declare_artefact                                                                   
    (entity, _, _) = self.declare_file(value)
  File "/home/mcrusoe/cwltool/cwltool/provenance.py", line 571, in declare_file                                                                       
    (sec_entity, _, _) = self.declare_file(sec)
  File "/home/mcrusoe/cwltool/cwltool/provenance.py", line 514, in declare_file                                                                       
    raise ValueError("Must have class:File: %s" % value)                                                    
ValueError: Must have class:File: {'basename': 'input.txt_idx8', 'location': 'file:///tmp/tmpvswaqxeb/input.txt_idx8', 'class': 'Directory'}          
Workflow error, try again with --debug for more information:                              
Must have class:File: {'basename': 'input.txt_idx8', 'location': 'file:///tmp/tmpvswaqxeb/input.txt_idx8', 'class': 'Directory'}     
```

---

- [ ] 61 "Test parameter evaluation, no support for JS expressions"
- [ ] 62 "Test parameter evaluation, with support for JS expressions"
- [ ] 73 "Test record type output binding."
(`"@id": "urn:uuid:8238136c-4736-44a2-a6cc-16fbc789fdd8"` in the output records

---

- [ ] 90 "Test file literal as input"
- [ ] 120 "Test file literal as input without Docker"
```
/home/mcrusoe/cwltool/env3/bin/cwltool 1.0
Resolved 'v1.0/cat3-tool.cwl' to 'file:///home/mcrusoe/common-workflow-language/v1.0/v1.0/cat3-tool.cwl'
Got workflow error
Traceback (most recent call last):
  File "/home/mcrusoe/cwltool/cwltool/executors.py", line 164, in run_jobs
    runtime_context.research_obj)
  File "/home/mcrusoe/cwltool/cwltool/provenance.py", line 459, in evaluate
    self.used_artefacts(customised_job, self.workflow_run_uri)
  File "/home/mcrusoe/cwltool/cwltool/provenance.py", line 821, in used_artefacts
    entity = self.declare_artefact(value)
  File "/home/mcrusoe/cwltool/cwltool/provenance.py", line 736, in declare_artefact
    (entity, _, _) = self.declare_file(value)
  File "/home/mcrusoe/cwltool/cwltool/provenance.py", line 531, in declare_file
    with fsaccess.open(location, "rb") as fhandle:
  File "/home/mcrusoe/cwltool/cwltool/stdfsaccess.py", line 41, in open        
    return open(self._abs(fn), mode)                    
FileNotFoundError: [Errno 2] No such file or directory: '_:221ad84f-daa1-48b7-bfee-8f28dae22ed8'                                                       
Workflow error, try again with --debug for more information:
[Errno 2] No such file or directory: '_:221ad84f-daa1-48b7-bfee-8f28dae22ed8'
```

**Comment by mr-c** [comment]
`./run_test.sh RUNNER=cwltool EXTRA="--provenance $PWD/RO_test" -n55`
 to run a single test

To debug a single test, adapt the command that is run. For example:

`/home/mcrusoe/cwltool/env3/bin/cwltool --provenance /home/mcrusoe/common-workflow-language/RO_test --outdir=/tmp/tmpxn1z84do 'v1.0/search.cwl#main' v1.0/search-job.json`
I would 
```
cd v1.0
cwltool --provenance RO_test --debug  'v1.0/search.cwl#main' v1.0/search-job.json
```

and, if need be,
```
pip install ipdb
ipdb $(which cwltool) --provenance RO_test --debug  'v1.0/search.cwl#main' v1.0/search-job.json
```
