### ISSUE TITLE
test_hello_workflow  failure on MS Windows

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#958]
```
Traceback (most recent call last):

  File "c:\jenkins\workspace\cwltool_jenkinsfile_upgrade-6OTLDHGBVKNOZ56QTWPIRZFBNKMBA4BIOLKLXZ2QMX535JO2PHLQ\cwltool\executors.py", line 169, in run_jobs

    job.run(runtime_context)

  File "c:\jenkins\workspace\cwltool_jenkinsfile_upgrade-6OTLDHGBVKNOZ56QTWPIRZFBNKMBA4BIOLKLXZ2QMX535JO2PHLQ\cwltool\job.py", line 422, in run

    self._execute([], env, runtimeContext)

  File "c:\jenkins\workspace\cwltool_jenkinsfile_upgrade-6OTLDHGBVKNOZ56QTWPIRZFBNKMBA4BIOLKLXZ2QMX535JO2PHLQ\cwltool\job.py", line 256, in _execute

    job_order, runtimeContext.process_run_id, str(self.name))

  File "c:\jenkins\workspace\cwltool_jenkinsfile_upgrade-6OTLDHGBVKNOZ56QTWPIRZFBNKMBA4BIOLKLXZ2QMX535JO2PHLQ\cwltool\provenance.py", line 811, in used_artefacts

    entity = self.declare_artefact(value)

  File "c:\jenkins\workspace\cwltool_jenkinsfile_upgrade-6OTLDHGBVKNOZ56QTWPIRZFBNKMBA4BIOLKLXZ2QMX535JO2PHLQ\cwltool\provenance.py", line 703, in declare_artefact

    (entity, _) = self.declare_string(value)

  File "c:\jenkins\workspace\cwltool_jenkinsfile_upgrade-6OTLDHGBVKNOZ56QTWPIRZFBNKMBA4BIOLKLXZ2QMX535JO2PHLQ\cwltool\provenance.py", line 673, in declare_string

    data_file = self.research_object.add_data_file(byte_s, content_type=TEXT_PLAIN)

  File "c:\jenkins\workspace\cwltool_jenkinsfile_upgrade-6OTLDHGBVKNOZ56QTWPIRZFBNKMBA4BIOLKLXZ2QMX535JO2PHLQ\cwltool\provenance.py", line 1416, in add_data_file

    os.rename(tmp.name, path)

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Dan\\AppData\\Local\\Temp\\tmp6d3u8k6c' -> 'C:\\Users\\Dan\\AppData\\Local\\Temp\\tmpxqcye_ck\\data\\26\\260807aefd9032a48a0d88d4ff7110a5bbfaea3d'

Workflow error, try again with --debug for more information:

[WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Dan\\AppData\\Local\\Temp\\tmp6d3u8k6c' -> 'C:\\Users\\Dan\\AppData\\Local\\Temp\\tmpxqcye_ck\\data\\26\\260807aefd9032a48a0d88d4ff7110a5bbfaea3d'
```

**Comment by mr-c** [comment]
We no longer support running in MS Windows, but we do support running in the Windows Subsystem for Linux 2: https://github.com/common-workflow-language/cwltool#ms-windows-users
