### ISSUE TITLE
mapSubject error needs fixing

### ISSUE THREAD

**Issue by ranijames** [common-workflow-language/cwltool#989]
Hello All, 

I have a CWL script which uses edit inplace for editing the results in the working directory, but the CWL.

## Expected Behavior
It should run and give me the output
## Actual Behavior
it complains,

Duplicate keys will become an error in future releases, and are errors
by default when using the new API.

  warnings.warn(DuplicateKeyFutureWarning(*args))
Tool definition failed validation:
("mapSubject '%s' value '%s' is not a dictand does not have a mapPredicate", '-class', None)
## Workflow Code
```
cwlVersion: v1.0
class: CommandLineTool
doc: Sp

baseCommand: [python,-m,spladder.spladder]

hints:
  cwltool:InplaceUpdateRequirement:
    inplaceUpdate: true
requirements:
  EnvVarRequirement:
     envDef:
       PYTHONPATH: /cluster/home/usr/spladder/python
  -class: InlineJavascriptRequirement
  -class: InitialWorkDirRequirement
  listing: 
   - entry: $(inputs.spladder_dir)
     writable: true


inputs:
 spladder_gtf: 
  type: File
  inputBinding:
   position: 3
   prefix: -a
 spladder_bams: 
  type: File[]
  inputBinding:
   position: 1
   prefix: -b
   itemSeparator: ","
  secondaryFiles: .bai
 spladder_dir:
  type: Directory
  inputBinding:
   position: 2
   prefix: -o
 spladder_phase2:
  type: string
  inputBinding:
   position: 4
   prefix: -T
 spladder_merge_graphs:
  type: string
  inputBinding:
    position: 5
    prefix: -M
 spladder_qmode:
  type: string
  inputBinding:
    position: 7
    prefix: --qmode
 spladder_quantify_graph:
  type: string
  inputBinding:
    position: 6
    prefix: --quantify_graph


outputs:
 spladder_out:
  type: Directory
  outputBinding:
   glob: $(inputs.spladder_dir.basename)

$namespaces:
  cwltool: http://commonwl.org/cwltool#
```

## Full Traceback
```
found duplicate key "-class" with value "InitialWorkDirRequirement" (original value: "InlineJavascriptRequirement")
  in "file:///cluster/home/aalva/Projects/PHRT-Immuno/scripts/cwl/spladder_part3.cwl", line 15, column 3

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become an error in future releases, and are errors
by default when using the new API.

  warnings.warn(DuplicateKeyFutureWarning(*args))
Tool definition failed validation:
("mapSubject '%s' value '%s' is not a dictand does not have a mapPredicate", '-class', None)
Traceback (most recent call last):
  File "/cluster/home/aalva/software/anaconda/envs/py2/lib/python2.7/site-packages/cwltool/main.py", line 657, in main
    do_validate=loadingContext.do_validate)
  File "/cluster/home/aalva/software/anaconda/envs/py2/lib/python2.7/site-packages/cwltool/load_tool.py", line 284, in validate_document
    workflowobj, fileuri, checklinks=do_validate)
  File "/cluster/home/aalva/software/anaconda/envs/py2/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 861, in resolve_all
    self._resolve_idmap(document, loader)
  File "/cluster/home/aalva/software/anaconda/envs/py2/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 639, in _resolve_idmap
    "and does not have a mapPredicate", k, v)
ValidationException: ("mapSubject '%s' value '%s' is not a dictand does not have a mapPredicate", '-class', None)
```

## Your Environment
* cwltool version: 
Check using ``cwltool v1.0``

**Comment by mr-c** [comment]
Hello @ranijames 

Two things are going on here:
1. Mixing `- class: SomeRequirement` and `OtherRequirement: {}` styles in the same block;
2. In YAML one needs a space after the `-` prefix of array entries: `- Class` not `-Class`

Here's a revised version:

``` cwl
requirements:
  EnvVarRequirement:
     envDef:
       PYTHONPATH: /cluster/home/usr/spladder/python
  InlineJavascriptRequirement: {}
  InitialWorkDirRequirement: {}
    listing: 
     - entry: $(inputs.spladder_dir)
       writable: true
```

**Comment by mr-c** [comment]
@ranijames I had an extra `{}` after the `InitialWorkDirRequirement:`; I've updated my comment to fix that

**Comment by ranijames** [comment]
Ok, I get the same error

**Comment by ranijames** [comment]
@mr-c Thanks its now working!

**Comment by ranijames** [comment]
> @ranijames I had an extra `{}` after the `InitialWorkDirRequirement:`; I've updated my comment to fix that I am using `hints:
  cwltool:InplaceUpdateRequirement:
    inplaceUpdate: true` in order to let CWL detects and read the existing files in the designatated output dir (splatter_dir). But, somehow CWL in the able script is not doing its job.
I am using `cwltool --enable-ext spa.cwl part4.yml` to run the tool

Thanks, I have a additional question to this,

**Comment by ranijames** [comment]
@mr-c I have added new question/issue >>https://github.com/common-workflow-language/cwltool/issues/993

**Comment by ranijames** [comment]
@mr-c I did not get the results, the program is staring from the first step. Although few results are there
